### ISSUE TITLE
SearchServer should deal with bogus request

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1053]
Many requests on the `SearchServer`originating from _http://portal.ejpd.admin.ch/etcmobile_ ending in HTTP 500

curl 'http://mf-chsdi3.dev.bgdi.ch/rest/services/api/SearchServer?lang=de&type=locations&searchText=tr%E8fl&'

```
[Wed Oct 08 11:18:26 2014] [error] [client 10.220.4.40]     return codecs.utf_8_decode(input, errors, True)
[Wed Oct 08 11:18:26 2014] [error] [client 10.220.4.40] UnicodeDecodeError: 'utf8' codec can't decode  byte 0xe8 in position 2: invalid continuation byte
```

**Comment by gjn** [comment]
Funny fact:

`nice_subscriber` approach works in mf-chsdi3 using `buildout/bin/pserve production.ini`. It does NOT work using `buildout/bin/pserve production.ini` and it does NOT work as mod_wsgi behind apache.

As indicated [here](https://groups.google.com/forum/#!topic/pylons-discuss/qLglgrgpoho), it might be related to the debug_toolbar - but I can't see how it gets in the way in mod_wsgi.

**Comment by gjn** [comment]
See #1609
