### ISSUE TITLE
Luftbild does not contain width/height

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1074]
Probably a data error. Luftbild under [1] does not contain widht/height, resulting in a not working luftbild viewer [2]. [2] is the link in the html popup. Note the 'none' values...

[1] http://map.geo.admin.ch/?ch.swisstopo.lubis-luftbilder_schwarzweiss=19790470160318&lang=de&topic=luftbilder&X=190000.00&Y=660000.00&zoom=1&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss&catalogNodes=1179,1180,1186
[2] http://api3.geo.admin.ch/luftbilder/viewer.html?lang=de&layer=ch.swisstopo.lubis-luftbilder_schwarzweiss&title=Bildnummer&height=None&width=None&bildnummer=19790470160318&datenherr=swisstopo

**Comment by ltclm** [comment]
there is a width and height value in the database for this image.
```sql
select ebkey,image_width,image_height FROM luftbilder_swisstopo_bw where ebkey = '19790470160318';
     ebkey      | image_width | image_height
----------------+-------------+--------------
 19790470160318 |       16858 |        16857
```
If you are opening this fullresviewer the "normal way" the image is displayed correctly:
![image](https://cloud.githubusercontent.com/assets/5286659/5646679/225d7e9c-967f-11e4-9d2a-366813641725.png)

In the url above in the ticket the parameters ``width`` and ``height`` are missing, the url should look like this:
http://api3.geo.admin.ch/luftbilder/viewer.html?lang=de&width=16858&layer=ch.swisstopo.lubis-luftbilder_schwarzweiss&bildnummer=19790470160318&title=Bildnummer&rotation=0&datenherr=swisstopo&height=16857

**Comment by cedricmoullet** [comment]
@gjn could you please check that it's still an issue ?

**Comment by ltclm** [comment]
here some examples of recently generated lubis tiles on s3 by igis:
```bash
07.02.2015 20:04:46 20047020035329 Image folder created
07.02.2015 20:04:46 20047020035321 Image folder created
07.02.2015 20:04:46 19880610170171 Image folder created
07.02.2015 20:04:46 19950010043801 Image folder created
07.02.2015 20:04:46 19880610087146 Image folder created
07.02.2015 20:04:46 19950010033774 Image folder created
07.02.2015 20:04:46 20047020025333 Image folder created
07.02.2015 20:04:46 19991420113917 Image folder created
07.02.2015 20:04:46 20047020035319 Image folder created
07.02.2015 20:04:46 19950010033779 Image folder created
07.02.2015 20:04:46 20002090045109 Image folder created
07.02.2015 20:04:46 20002090045106 Image folder created
07.02.2015 20:04:46 20002090045101 Image folder created
```
These images will yet not have width/height values in the database.
But we could use the xml file which is generated automatically to get these information:
p.e. for point 19880610087146
http://aerialimages0.geo.admin.ch/tiles/19880610087146/tilemapresource.xml

**Comment by gjn** [comment]
Fixed on next deploy.
