### ISSUE TITLE
featureId's returned from identify service contains float instead of int

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1082]
Service url:
https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometryType=esriGeometryPoint&geometry=567280,193190&imageDisplay=1,1,1&mapExtent=0,0,1,1&tolerance=500&layers=all:ch.swisstopo.swissboundaries3d-kanton-flaeche.fill,ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill&returnGeometry=false

The results contains featureId's in the form `630.0`, even when they are integers and the property is defined as integer in the model (https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/stopo.py#L64).

Most probably other services are affected as well.

**Comment by AFoletti** [comment]
Are you sure that the problem is in the model? The model already defines the ID as integer.

**Comment by gjn** [comment]
Yes, as said in the In the OP ` featureId's in the form 630.0, even when they are integers and the property is defined as integer`

**Comment by procrastinatio** [comment]
Hem, lloks like https://github.com/geoadmin/mf-chsdi3/pull/1145 fixed this issue.

**Comment by AFoletti** [comment]
confirmed. It's fixed
