### ISSUE TITLE
Fail gracefully if raster files not present

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1167]
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/lib/raster/georaster.py#L19

Currently, if raster files are not present, the complete application does not start (Because rasters are initialized at startup).

Make this more robust and let only the services fail that rely on the rasters to be present but let the application startup normally.

**Comment by loicgasser** [comment]
Solved via https://github.com/geoadmin/mf-chsdi3/commit/bc852847c12585b225196bfa3f46443cbb65bdbc#diff-10dd1aff3770717dfc4c7a0d88eb461d
