### ISSUE TITLE
Background layers are missing in the layer lists

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1172]
http://api3.geo.admin.ch/api/faq/index.html#available-layers

**Comment by cedricmoullet** [comment]
@loicgasser could you hardcode this ?

**Comment by loicgasser** [comment]
Those layers are not in the view_bod_layer_info_en because of attribute filter bodsearch = True.

@ltclm : I think it's better to remove this filter from the the view and adpat sphinx/chsdi accordingly.
Should be pretty straightforward. What do you think?

**Comment by loicgasser** [comment]
@ltclm 
ok I hard code in the doc. I just red the previous comments sorry.
