### ISSUE TITLE
Sanitize SQL query

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1179]
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/lib/validation/mapservice.py#L94

**Comment by cedricmoullet** [comment]
@loicgasser what are the next steps here ?

**Comment by procrastinatio** [comment]
See my comment https://github.com/geoadmin/mf-chsdi3/pull/1210#issuecomment-72888596
