### ISSUE TITLE
Query tool: ch.swisstopo.geologie-geologischer_atlas

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1180]
The layer ch.swisstopo.geologie-geologischer_atlas is using the same data like ch.swisstopo.geologie-geocover for the tooltips, thus it is configured as queryable=true.
The new query tool cannot read the queryable attributes using the service url:
http://mf-chsdi3.int.bgdi.ch/rest/services/all/MapServer/ch.swisstopo.geologie-geologischer_atlas?lang=de

**Comment by loicgasser** [comment]
Solved via #1183
