### ISSUE TITLE
Print: black border around PNG

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1194]
PNG tiles issues from raster dataset have a not so nice black border in some area

![border](https://cloud.githubusercontent.com/assets/1236739/5650486/1e96f9d0-969f-11e4-9dbc-c1996acb1772.jpg)

You may try with the Atlas geéologique or any raster dataset (PNG from vector is always OK)

**Comment by procrastinatio** [comment]
Quite strange, I though it was an artefact of the print server only, but we have the same in the Mapproxy's WMS service using the WTMS tiles. Looks like, it is in the tiles.

**Comment by cedricmoullet** [comment]
@procrastinatio could you put a test link ?

**Comment by procrastinatio** [comment]
Try with `ch.swisstopo.hiks-siegfried` (but any raster layer have the same pattern). Print somewhere here: http://map.geo.admin.ch/?X=217125.00&Y=558350.00&zoom=4&lang=fr&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.hiks-siegfried

**Comment by procrastinatio** [comment]
OK, my magic `.pngjepg`do not display this pattern anymore. So you may close it.
