### ISSUE TITLE
oid should not be used as id in the models

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1198]
```
-----Ursprüngliche Nachricht-----
Von: Moullet Cédric swisstopo 
Gesendet: Donnerstag, 8. Januar 2015 15:57
An: _swisstopo-webgis; _swisstopo-webgis; Clausen Marcel swisstopo; Gerber Urs swisstopo
Betreff: RE: Customer feedback

Really a bad bug
@Marcel: could you have a look ? Quite a prio 1 ;-) Thanks Urs !
Cédric

-----Message d'origine-----
De : webgis@swisstopo.ch [mailto:webgis@swisstopo.ch] Envoyé : jeudi 8 janvier 2015 15:55 À : _swisstopo-webgis Objet : Customer feedback

urs.gerber@swisstopo.ch just sent a feedback:
 mehrfach klicken auf Kachel ergibt unterschiedliche, z.T. nicht korrekte Objekt-Informationen zu Kacheln/Kartenblattern; oft auch bei mehrmaligem Klicken auf gleiche Kachel. 
Permalink: http://map.geo.admin.ch/?X=174199.92&Y=660000.00&zoom=1&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=1538&layers=ch.swisstopo.skitourenkarte-50.metadata&layers_opacity=0.75. 

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; .NET4.0E; rv:11.0) like Gecko
```
This layer is using the database internal value oid as id in the model but this value is not the same on our two clusters:
http://api3.geo.admin.ch/1420635330/rest/services/swisstopo/MapServer/ch.swisstopo.skitourenkarte-50.metadata/88736240/htmlPopup?imageDisplay=1920,754,96&lang=de&mapExtent=180000,-14300.079999999987,1140000,362699.92000000004

```bash
$ psql -c "Select oid,lknr,name from datenstand.view_gridstand_lkski where oid = 88736240;" -d stopo -U www-data -h 10.220.5.94
   oid    | lknr |  name
----------+------+---------
 88736240 | 247S | Sardona
(1 Zeile)

$ psql -c "Select oid,lknr,name from datenstand.view_gridstand_lkski where oid = 88736240;" -d stopo -U www-data -h 10.220.6.23
   oid    | lknr |    name
----------+------+------------
 88736240 | 254S | Interlaken
(1 Zeile)
```
There is the same issue for the layer 
https://github.com/geoadmin/mf-chsdi3/search?utf8=%E2%9C%93&q=id+%3D+Column%28%27oid%27

We have two options now:
1) we are using the pg_dump option ``-o, --oids                   include OIDs in dump`` with our deploy script and the problem will be fixed after the next complete database deploy of stopo and bafu
2) we are changing the model configuration for these two layers and use a stable column for the id (p.e. bgdi_id)

I let you decide @cedricmoullet @daguer

**Comment by cedricmoullet** [comment]
We need to use a stable id

**Comment by ltclm** [comment]
@loicgasser  is it possible to use text columns as id in the model:
 https://github.com/geoadmin/mf-chsdi3/blob/064d487f31db836ca65f893558c3db1227d1f873/chsdi/models/vector/stopo.py#L54

**Comment by loicgasser** [comment]
yes see
https://github.com/geoadmin/mf-chsdi3/blob/064d487f31db836ca65f893558c3db1227d1f873/chsdi/models/vector/stopo.py#L232

**Comment by ltclm** [comment]
Should be fixed with this pr
https://github.com/geoadmin/mf-chsdi3/pull/1200
@loicgasser  could you please test the changes with the new query tool, i was not able to install the latest code in my home.

**Comment by loicgasser** [comment]
Fixed via https://github.com/geoadmin/mf-chsdi3/pull/1200
