### ISSUE TITLE
[WMS] Bruit Ferroviaire Down [err 500]

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-chsdi3#1205]
http://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bafu.laerm-bahnlaerm_nacht&CRS=EPSG%3A21781&STYLES=&WIDTH=1858&HEIGHT=1072&BBOX=195500%2C-78000%2C1124500%2C458000

**Comment by kandre** [comment]
http://wms-geo.dev.bgdi.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bafu.laerm-bahnlaerm_nacht&CRS=EPSG%3A21781&STYLES=&WIDTH=1858&HEIGHT=1072&BBOX=195500%2C-78000%2C1124500%2C458000

is down as well. These layers are on prod for one year already, I wonder if it is down for a long time. I check the wms and the database

**Comment by AFoletti** [comment]
@kandre, your link does not lead anywhere ;)
@ponceta, this layer does not exist anymore.

You can close the ticket :)

**Comment by AFoletti** [comment]
wait, my bad... got confused.
the layer does exist. we should look at the issue

**Comment by kandre** [comment]
Yep sorry the second link was wrong but it is down anyway

**Comment by ponceta** [comment]
We have ch.bav.laerm-emissionsplan_eisenbahn_nacht and ch.bav.laerm-emissionsplan_eisenbahn_tag in the get cap but layers are not available.

**Comment by kandre** [comment]
@ponceta those are other layers, different from ch.bafu.laerm-bahnlaerm_nacht and tag, dont be confused.

ch.bav.laerm-emissionsplan_eisenbahn_nacht and tag are available: 

http://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bav.laerm-emissionsplan_eisenbahn_nacht&CRS=EPSG%3A21781&STYLES=&WIDTH=1858&HEIGHT=1072&BBOX=195500%2C-78000%2C1124500%2C458000

The error 500 are with ch.bafu.laerm-bahnlaerm_nacht and ch.bafu.laerm-bahnlaerm_tag

It might come from a corrupt tiff file (although this tiff was the input data for the integration), I am checking that with gdal.

**Comment by ponceta** [comment]
Yes, was talking about 
http://map.geo.admin.ch/?X=204884.74&Y=577223.57&zoom=3&lang=en&topic=ech&bgLayer=voidLayer&layers=WMS%7C%7CNighttime%20railway%20noise%7C%7Chttp:%2F%2Fwms.geo.admin.ch%2F%7C%7Cch.bafu.laerm-bahnlaerm_nacht&layers_opacity=0.8

**Comment by ponceta** [comment]
Duplicate with https://redmine.prod.bgdi.ch/issues/5621
