### ISSUE TITLE
Create composite labels

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1206]
related to https://github.com/geoadmin/mf-chsdi3/pull/1174

**Comment by procrastinatio** [comment]
Printing this is going to be challenging.

**Comment by cedricmoullet** [comment]
@loicgasser what are the next steps here ?

**Comment by loicgasser** [comment]
Here I am talking about composite labels for features. When one needs more than one attribute of the model to create a label or wants to add (translated) text to the label.
So next step is first solve https://github.com/geoadmin/mf-chsdi3/issues/1219 and then take care of this issue.
