### ISSUE TITLE
GetCap content and layer title

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1215]
http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml

-> ch.swisstopo.pixelkarte-farbe should not have >Landeskarte 1:25&amp;#39;000 | LK25 as title since it's not only a 1:25'000
-> content (title, description) should be checked in Arcgis. Is the content readable (special character, accent) ?

**Comment by loicgasser** [comment]
In response header Content-Type:text/xml; charset=UTF-8

so yes should be able to treat it correctly

**Comment by ltclm** [comment]
The content in the database is
``Landeskarte 1:25'000 | LK25 `` 
This string is somehow converted into:
``
Landeskarte 1:25&amp;amp;#39;000 | LK25 
``
@loicgasser Any idea, why is the apostrophe converted?

**Comment by loicgasser** [comment]
@ltclm ok for title
But for ch.swisstopo.pixelkarte-farbe <Layer> is not present in test. Any idea?

**Comment by ltclm** [comment]
@mariokeusen do we have a geocat entry for the base layers ch.swisstopo.pixelkarte-farbe|grau ?
If not we have to translate these layers manually in the bod to fix this issue in the wmts getcap.

**Comment by loicgasser** [comment]
@ltclm I know why, it is not part of the inspire topic.

**Comment by ltclm** [comment]
@loicgasser 
The base layer is not part of the topics ech and inspire. You can checkt the view bod.re.view_bod_wmts_getcapabilities_de.
But i wonder why this base layer is visible in the prod getcap then! What is the dev url of the getcap service?

**Comment by loicgasser** [comment]
because of the all tag... Which make it not apply any filter... So I will fix in a separate PR.
Thanks, I wasn't sure about the base layers.

**Comment by procrastinatio** [comment]
Side note, everywhere in title, abstract the apostrophe *'* (#39 or u+0027)  and the right single quotation mark  *’* (#8219 or u+2019) are used interchangeably, which is wrong.

**Comment by cedricmoullet** [comment]
@loicgasser what are the next steps here ?

**Comment by loicgasser** [comment]
@ltclm
In the view `view_bod_wmts_getcapabilities_themes_fr` base layers are visible in fk_dataset_id (list of layers separated with commas)
Should we always remove them from getCap?
For ech/inspire/all ?

**Comment by loicgasser** [comment]
@procrastinatio Part 1 is ok, I know you're working on part 2, so I give it to you.

**Comment by procrastinatio** [comment]
Part 2 is OK. Layer titles has been enhanced and customized for ESRI ArcGis.

**Comment by procrastinatio** [comment]
@ltclm I think is is done.
