### ISSUE TITLE
Use more relevant label for ch.astra.unfaelle-personenschaeden_alle

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1221]
Open http://map.geo.admin.ch/?X=159611.50&Y=538693.48&zoom=5&lang=fr&topic=vu&bgLayer=ch.swisstopo.pixelkarte-grau&catalogNodes=1318&layers=ch.astra.unfaelle-personenschaeden_alle

Use select by rectangle

cannot really understand this label...
Use Unfallschwerekategorie instead.

**Comment by cedricmoullet** [comment]
@daguer could you please handle this issue ?

**Comment by AFoletti** [comment]
The 5 Unfaelle layers had as label the weekday in the original sphinx indexes.
Since the switch to the models for the select-by-rectangle results, the label is wrong. It's not consistent between the 5 layers and most of the time plain wrong.
That's not the first case... we should maybe test each label to check if it corresponds to the original "sphinx" one.
I would switch the label to weekday then. There is a way to handle language-dependant columns for the label? In sphinx it was possible

**Comment by loicgasser** [comment]
@AFoletti About language specific label, will be available soon. See:
https://github.com/geoadmin/mf-chsdi3/pull/1277

**Comment by AFoletti** [comment]
@loicgasser thanks for the head-up!
@daguer it will be maybe good to use the new multilingual possibility for this one, once it's available

**Comment by cedricmoullet** [comment]
@daguer @AFoletti @loicgasser  how do we proceed here ?

**Comment by AFoletti** [comment]
the issue mentioned by @loicgasser is merged. The multilanguage label is then a reality.

I think that it would make sense if someone in the integration team takes the responsibility to check the coherence of each label and maybe use the new multilanguage option where it makes sense.
@daguer , could you take care of that?

**Comment by gjn** [comment]
@loicgasser @AFoletti What about multi-column labels? ;=)

**Comment by AFoletti** [comment]
@gjn I'm not aware of multi-column labels at the moment. Are they present?
If yes: @loicgasser , it's possible to concatenate directly into the model?

**Comment by gjn** [comment]
No, not present now, but in sphinx, we supported them for queryable layers.

**Comment by loicgasser** [comment]
Regarding composite labels, there is an open issue for that. See: https://github.com/geoadmin/mf-chsdi3/issues/1206
@daguer please change the label as explained initially, this is a one line and 5 translations commit.

**Comment by cedricmoullet** [comment]
@daguer could you please adapt this ?

**Comment by cedricmoullet** [comment]
@daguer ??

**Comment by daguer** [comment]
Attribut change to accidenttype_de
PR #1413
