### ISSUE TITLE
Test WMTS GetCap

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1223]
Check that for each `LayerRef`, there is an associated `Identifier`

**Comment by loicgasser** [comment]
we have `<% layers = theme.fk_dataset_id.split(',')  %>` to determine the LayerRef
so from the themes and
`layers` from GetCap model...

**Comment by procrastinatio** [comment]
Where is it missing ?

**Comment by procrastinatio** [comment]
Should be a `NOT NULL`condition in the database.

See http://api3.geo.admin.ch/rest/services/aviation/1.0.0/WMTSCapabilities.xml

and *ch.bafu.schutzgebiete-aulav_auen*

**Comment by cedricmoullet** [comment]
@loicgasser what are the next steps here ?

**Comment by loicgasser** [comment]
@ltclm Has it been implemented in DB?

**Comment by cedricmoullet** [comment]
@ltclm ?

**Comment by ltclm** [comment]
> Should be a NOT NULLcondition in the database.
See http://api3.geo.admin.ch/rest/services/aviation/1.0.0/WMTSCapabilities.xml
and ch.bafu.schutzgebiete-aulav_auen

I am not sure whether I understood the problem here...
@procrastinatio / @loicgasser 
Every layer has to be in an inpsire theme?

**Comment by loicgasser** [comment]
@rfrancel since you are working on the wmts, there tests we have to add to control the integrity of the WMTS getCap document.

In `Themes` check that for each `LayerRef` there is an associated `Identifier` in `Contents-Layer` .
Check that in each layer `Contents-Layer` the `TileMatrixSet` can be found in the `TileMatrixSet-Identifier` section.

http://www.gdal.org/frmt_wmts.html

Look if we could add the `ZeroBlockHttpCodes` and `ZeroBlockOnServerException` optional sections.

Doable for you?

**Comment by rfrancel** [comment]
Yes I guess. I'll look into it.

**Comment by loicgasser** [comment]
done
