### ISSUE TITLE
[Query tool] Paging results for identify

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1230]
Get rid of maximum results of 100 or 200 features. Implement paging

See https://github.com/geoadmin/mf-geoadmin3/issues/2087

All services should be updated or not ?

**Comment by loicgasser** [comment]
I propose to name this parameter `offset` which takes an integer only.

**Comment by gjn** [comment]
There are several parts to the proposed query tool extension. The most important one is to inform the user if there are more results than our hard limit. The lower priority is then to show all results/paging.

So we need to know the total results of a query. For this, I would add the total results (COUNT of the query) to the results (Results would be json with `{results: [...], totalResults: xxxx}.

**Comment by loicgasser** [comment]
Fixed via https://github.com/geoadmin/mf-chsdi3/pull/1266
