### ISSUE TITLE
[API] Uncaught TypeError: Cannot read property 'Ha' of undefined

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-chsdi3#1231]
This is a bug noticed on https://github.com/geoadmin/web-dashboard/issues/27

But also present in the user group of api3 since 
https://groups.google.com/forum/#!topic/geoadmin-api/tEahQrUAjlw

I'm trying to locate the changes/modifications that cause this.
@oterral had a look yesterday too.
Any hints are welcome

**Comment by oterral** [comment]
it's not the same bug as in the google group. I close it as it's specific to the dashboard specific
