### ISSUE TITLE
Wrong ID

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1233]
I don't know who integrated/updated those layers recently I give it to you, but you can pass it forward if you know who did.

ch.swisstopo.verschiebungsvektoren-tsp1
ch.swisstopo.verschiebungsvektoren-tsp2

For those layers the id start with a 0 which is bad. Because 0 is evaluated to false in Javascript and it breaks the app.

Please fix ASAP.

In the future never start with a 0.

**Comment by AFoletti** [comment]
Do you mean the feature ID in the model?
Should be enough to switch to bgdi_id

**Comment by alcapat** [comment]
bgdi_id start with 0 too :-(

**Comment by AFoletti** [comment]
hm, then it was a bgdi_id not filled by the script, but from a wrongly-configured FME counter

Maybe it's better to ask @daguer to look at it. If I'm not wrong he integrated those.

**Comment by daguer** [comment]
Problem resolved. There is no 0 more... (id and bgdi_id). 
Tables deployed on T, I and P.
The PR to update the model is made.

**Comment by loicgasser** [comment]
@daguer please add the associated tables in remember to deploy. (if not done yet)

**Comment by loicgasser** [comment]
Thanks
