### ISSUE TITLE
[Print]: multigeometries are not supported

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1265]
KML deals with multigeomtries well, but the resulting vector layer may not be printed, as the mapfish print server crashes with _MultiGeometry_

Work around:
* Server-side transformation of multigeometries to simple ones, either on the ogcproxy or the printproxy.
* Client-side, when parsing the KML
* Using MapFish v3

**Comment by loicgasser** [comment]
Using MapFish v3 would make more sense to me

**Comment by cedricmoullet** [comment]
Wont fix in V2
