### ISSUE TITLE
Error 500 on sachplan

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1279]
http://api3.geo.admin.ch/1423674319/rest/services/sachplan/MapServer/ch.bav.sachplan-infrastruktur-schiene_kraft/71-M-02-0174/htmlPopup?imageDisplay=1280,685,96&lang=de&mapExtent=714263.7625080498,74512.21874827833,727063.7625080498,81362.21874827833

**Comment by davidoesch** [comment]
@mariokeusen FYI

**Comment by gjn** [comment]
Strange mapExtent.

**Comment by loicgasser** [comment]
Probablement un problème dans une mako, je regarde ça en prio en début de semaine.

**Comment by AFoletti** [comment]
looks like the error comes only for a subset of the features (PlanningMeasures, for instance)
Checking that

**Comment by AFoletti** [comment]
fixed in referenced PR
