### ISSUE TITLE
Legends too large

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#1300]
Max size of a legend should be 480px. It's not the case for some layers.

**Comment by davidoesch** [comment]
If to large use thumbnail and link to png directly

**Comment by cedricmoullet** [comment]
@AFoletti ?

**Comment by loicgasser** [comment]
@AFoletti is this still an issue? I feel we have been more attentive recently regarding this topic.
Shall we check them all or shall we close this issue?

**Comment by AFoletti** [comment]
yes, we were more attentive in the last months and I adapted a few.
Still, a comprehensive test of every legend image I think it would be good

**Comment by loicgasser** [comment]
Ok I take it then.
