### ISSUE TITLE
Migrate from Lubis 2D to Lubis 3D

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1308]
ch.swisstopo.lubis-luftbilder_schwarzweiss
ch.swisstopo.lubis-luftbilder_farbe
ch.swisstopo.lubis-luftbilder_infrarot
ch.swisstopo.lubis-bildstreifen

**Comment by davidoesch** [comment]
Third dimension? Which one? Time?

**Comment by loicgasser** [comment]
height

**Comment by loicgasser** [comment]
This has been changed. OK now
