### ISSUE TITLE
Correct class names in models

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#1315]
As @procrastinatio pointed out at least a couple of times, our naming scheme for the classes in the models is not consistent.

@kandre and I we will scroll every model and adapt them to the CapWords convention

**Comment by loicgasser** [comment]
CapWords is not best partice for naming tables or views, please don't

* SQL keywords: upper case
* names (identifiers): lower case with underscore

**Comment by AFoletti** [comment]
ok. But then, should we make those models consistent or not? And if yes, which convention should we use?

**Comment by loicgasser** [comment]
Yes would be nice to have naming convention. I support the effort.

**Comment by AFoletti** [comment]
@loicgasser could you please make a suggestion of a naming convention?

**Comment by loicgasser** [comment]
Ok I will.

**Comment by procrastinatio** [comment]
Simply use [PEP8](https://www.python.org/dev/peps/pep-0008/#id34), especially *Naming Styles*

**Comment by loicgasser** [comment]
We use the CapWords convention class names in python.
