### ISSUE TITLE
Geoms check for esriGeoms definitions

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1336]
At the moment it is possible to use 
`rings` with `esriGeometryPolyline`
and
`paths` with `esriGeometryPolygon`
while we should not be able to do so. (Reverse is true as well)

See:
https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry={"paths":[[[675000,245000],[660000,260000],[620000,250000]]]}&geometryType=esriGeometryPolyline&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=5&layers=all:ch.bafu.bundesinventare-bln

and

https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry={"rings":[[[675000,245000],[660000,260000],[620000,250000]]]}&geometryType=esriGeometryPolyline&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=5&layers=all:ch.bafu.bundesinventare-bln

-> result is different as well

Doc at: http://help.arcgis.com/en/arcgisserver/10.0/apis/rest/geometry.html

**Comment by procrastinatio** [comment]
Who is using esriGeom by the way ? nobody
