### ISSUE TITLE
Get rid of buildout and use Makefile

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1338]
Like in c2cgeoportal I think they made the right decision.
It is older but way more stable.

**Comment by gjn** [comment]
See https://github.com/camptocamp/c2cgeoportal

**Comment by loicgasser** [comment]
I would put a higher prio to this issue. to be discussed.

**Comment by gjn** [comment]
Ding ding.

**Comment by loicgasser** [comment]
probably as happy your are.
