### ISSUE TITLE
Setup our own python package index server

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1340]
At the moment rely on c2c pypi index which is down sometimes, this can be dangerous as we don't have any control over that.

We could do it using.
https://pypi.python.org/pypi/pypiserver

**Comment by procrastinatio** [comment]
I think we should upgrade the bootstrap.py version and ditch the custom distribute package from c2c in the firste place. The rest in only a cache.

**Comment by procrastinatio** [comment]
In the first place, we should not build on `int`and `prod`...
