### ISSUE TITLE
Non-existing layer in geocatalog

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1342]
![image](https://cloud.githubusercontent.com/assets/3306154/6783850/65099234-d17c-11e4-81fe-76dd8a9950c5.png)

What is this layer? It is not in the layer config either.

Error is on prod as well.

**Comment by AFoletti** [comment]
that's an ongoing integration
if that's really on prod that's of course an error. We will eliminate that for the upcoming deploy
@pfanguin could you please take care of that?

**Comment by pfanguin** [comment]
This layer is not on prod, only on dev.

**Comment by loicgasser** [comment]
I was sure I saw it on prod yesterday. Did you deploy the bod? Anyway this is solved now. Thanks
