### ISSUE TITLE
Hover effect on KML in API

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1349]
In API, an hover effect should be visible when the mouse is over a feature.
http://mf-chsdi3.dev.bgdi.ch/ltmoc/examples/geoadmin_kml.html

**Comment by cedricmoullet** [comment]
And not only on KML, but on all features like in map.geo.admin.ch

**Comment by procrastinatio** [comment]
Make this once preview is the new default mode.

**Comment by procrastinatio** [comment]
We must provide an OL 5 API before.
