### ISSUE TITLE
WMTS: integrate 'zeitreihen' layer in GetCapabilities

### ISSUE THREAD

**Issue by beat-github** [geoadmin/mf-chsdi3#1361]
and please check usage custom .jpegpng tiles with ArcGis

**Comment by procrastinatio** [comment]
So layer 'ch.swisstopo.zeitreihen' is in the WMTS and the *api*

Both QGis and ArcGis don't like extension '.jpegpng'.

**Comment by beat-github** [comment]
though we implement use the layer 'ch.swisstopo.zeitreihen' by the way of format="image/png"

**Comment by cedricmoullet** [comment]
Not doable.
