### ISSUE TITLE
Launching integration tests: missing data

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-chsdi3#1367]
Hi,

I cloned the project locally and I tried to launch the tests with `./nose_test.sh -i` but they failed because they require the following file: `swissalti3d/kombo_2m_dhm25/index.dbf`.

I tried some free samples available at http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/height/dhm25.html. With these samples I had data of Matterhorn and Wabern. However, when I try to use them with the test suite, I get `IndexError: list index out of range`. So I guess they are not valid data set.

Can you tell me where to get the data? It would be much easier for me to be able to launch your test suite. If this data set cannot be made publicly available, can you at least indicate this in the README?

**Comment by cedricmoullet** [comment]
This dataset is not freely available. You can remove this test from your fork.
