### ISSUE TITLE
loader.js

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1383]
Remove apache proxy as we always have trouble with it.

`/loader.js --> /<timestamp>/uncachec_loader.js`

**Comment by gjn** [comment]
What kind of troubles do we have?

**Comment by procrastinatio** [comment]
Same as tc-geodesy...

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-chsdi3/pull/1443
