### ISSUE TITLE
Make 'temperaturmessstationen.mako' rendering more stable

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1390]
We have observed that nosetests sometimes fail because of this mako:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/templates/htmlpopup/temperaturmessnetz.mako

It should be made more robust, especially when failing to
a) get external resource and
b) parsing the external resource
the service should still work.

Maybe similar to https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/templates/htmlpopup/hydromessstationen.mako

**Comment by AFoletti** [comment]
solved
