### ISSUE TITLE
Deploy snapshot without nosetests

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1391]
The deploysnapshot command should be possible without running nosetests (as option to the script), whithout changing the default behaviour.

Use case:
./deploysnapshot xxxx prod fails (but _after_ nosetests run with prod environment, so there's no need to re-run the nosetests)

**Comment by gjn** [comment]
PR ready: https://github.com/geoadmin/mf-chsdi3/pull/1394

**Comment by loicgasser** [comment]
Solved via https://github.com/geoadmin/mf-chsdi3/pull/1394
