### ISSUE TITLE
[Print] Do use 'main' per default

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1395]
For now we have 45 print server war on tomcat, almost all of them are only copies from 'main'. I would like to reduce this number.

I propose, per default, only on _mf-chsdi3_  `main`will buildout install the print server. 

So in `mf-geoadmin3`, we have to split the `API_URL` into `API_URL` and `PRINT_URL`, both beeing the same unless specified.

Eventually, it would also be nice to have it's own set of hostname for the print service.

Any thought ?

**Comment by gjn** [comment]
+1.

I would also strongly suggest to have seperate print service.

**Comment by gjn** [comment]
As well as seperate mapproxy service.

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-chsdi3/pull/1446
