### ISSUE TITLE
[geodata] release notes 20150422 are not complete

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#1402]
http://api3.geo.admin.ch/releasenotes/index.html
Geodata information is not complete in the latest release notes. The following data updates should be added to the table:
ch.blw.alpprodukte
ch.blw.bergprodukte
ch.bafu.schutzgebiete-paerke_nationaler_bedeutung
ch.swisstopo.swisstlm3d-wanderwege

**Comment by ponceta** [comment]
Release notes did not went on prod last deploy since they were merged too late https://github.com/geoadmin/mf-chsdi3/pull/1388, there was no emergency deploy to fix this but a test has been added to prevent this to happen in the future.

http://mf-chsdi3.dev.bgdi.ch/releasenotes/index.html

**Comment by daguer** [comment]
4 updated layers added in releasenotes
