### ISSUE TITLE
Add a cleanbranch script

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#1409]
We could allow the remove of a branch from our environment

When we want to remove a branch we need to remove : 

- [x]  the print war in tomcat
- [ ] the folder in the vhost
- [ ] the apache config file in the vhost

**Comment by gjn** [comment]
We need the same in mf-geoadmin3.

This could be something for @ponceta @kandre . Just look what the deploybranch command does and do the reverse. First focus on dev.

**Comment by loicgasser** [comment]
we need to clean the .war files as well. this is why the print was down yesterday. too many print configs..

**Comment by procrastinatio** [comment]
For tomcat, see https://github.com/geoadmin/mf-chsdi3/pull/1446
