### ISSUE TITLE
BIG hole in swissimage: Gruyere or not gruyere that is the question

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1412]
http://map.geo.admin.ch/?X=173942.78&Y=656304.16&zoom=6&lang=en&topic=ech&bgLayer=ch.swisstopo.swissimage

**Comment by gjn** [comment]
Military?

**Comment by ltclm** [comment]
I have regenerated the tiles. 
Have no idea how this could happen....

**Comment by oterral** [comment]
I confirm it's fixed on prod. Thx @ltclm
