### ISSUE TITLE
Inform api list before updating to ol 3.5

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1423]
Since ol3.4 -> ol3.5 update contains some breaking changes, we should inform our api list 2-3 weeks in advance before deploying an update.

We should also try to provide them a test-link where they can test the updated API beforehand.

**Comment by davidoesch** [comment]
And add the instruction / how to use a previous version of the loader

**Comment by gjn** [comment]
We don't support 'previous loaders'.

**Comment by davidoesch** [comment]
This is a pitty - was the case in api2. User could go back to a previous version.... A set and forget method.

What are the pros  of not offering this?

**Comment by gjn** [comment]
- Less maintenance.
- sometimes updates to services might break older API's. So in theory, we would need to test all old versions of the API's -> again more maintenance cost
- older API's only support old layers (don't get update versions)

But I think we could introduced old versioned api's. @cedricmoullet ?

**Comment by cedricmoullet** [comment]
In API2, we offered this only because of varnish cache. This was not real versioning. As indicated by @gjn , there are key things (service compatibility, layer list) that make me think that we can't offer old versions without increasing importantly the maintenance costs.

**Comment by davidoesch** [comment]
Ok
