### ISSUE TITLE
Support/Service GDAL readable data sources 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#1445]
*Situation*
Layer ch.meteoschweiz.globalstrahlung-monatlich will be delivered frequently with via NetCDF , one delivery per month. all those files will be transfered to our filesystem and used as a timeenabled  source in UMM . the gdal lib will be used by UMM

*Task*
a tooltip service, pref  GetFeatureInfo WMS provided by UMM for gdal readable datasources is needed

*Action*
Build a service which enables fsdi to provide tooltips for datasets readable by gdal

*Result*
we enabled our feature /tooltip service to support a wide range data formats : customers can deliver realtime data as files we turn it into a REST service ...

Service has to be live mid july ( go live BFE solarkataster portal in October)

@gjn  and @cedricmoullet for more technical Details @ltclm is happy to give you the full technical story

**Comment by cedricmoullet** [comment]
@ltclm How can we solve this issue ?

**Comment by ltclm** [comment]
afaik there is no issue, mapserver should be used for data interaction -> tooltips.
We need to extent the chsdi feature/tooltip service to use  mapserver getfeatureinfo in the backend. With this enhancement we are ably to query any datasource (gdal/ogr) via mapserver.
For globalstrahlung use case (netcdf -> gdal -> mapserver -> wms) the mapserver part is working.
The getfeatureinfo service should be wrapped by chsdi to get and display feature info.

**Comment by AFoletti** [comment]
the GetFeatureInfo wrap in chsdi is already a request for the eMapis project. Nice to see it has other uses that that one ;)

**Comment by cedricmoullet** [comment]
@ltclm do we plan to go in prod with this ?

**Comment by gjn** [comment]
Data is integrated in principle. See https://github.com/geoadmin/mf-chsdi3/pull/1829

@davidoesch What data formats do we want exactly to support a) for this data b) general for all data?

**Comment by davidoesch** [comment]
for a) this data
NetCDF http://www.unidata.ucar.edu/publications/factsheets/current/factsheet_netcdf.pdf

for b) general for other data : realtime data formats
all NTH
GTFS (traffic)
GRIB (wetaher data https://weather.gc.ca/grib/what_is_GRIB_e.html)
GIF animated ( yes, weather radar)
Streaming formats ATOM, KML

**Comment by gjn** [comment]
@ltclm as I understand, datasource for the wms getfeatuerinfo is the db. We have a model in chsdi for access of this data directly in chsdi3. So we would not need to wrap wms requests to support tooltip/featureInfo. If the user wants WMS GetFeatureInfo, then this needs to be done on the WMS side. What do you think?

@davidoesch Let's discuss this tomorrow. Because I think the tooltip/getfeatureInfo is not enough to provide such a service. How does a user discover a feature? How does he select a specific feature? This might be dataset dependant.

**Comment by ltclm** [comment]
the initial idea was to provide the whole time series (120 Monthly values) with wms getfeature info based on vrt files referencing several netcdf files. This is not possible without changing fixing mapserver. I can give you more detailed information if needed.
We now have all  the  raster data in the database, so chsdi can generate everything from there without mapserver->gdal->netcdf.

But it is possible to provide a wms layer based on single netcdf files which can be used with a time-parameter. p.e. time=YYYYMM and get the information (getmap, getfeatureinfo, etc.) for a given month.

**Comment by loicgasser** [comment]
@davidoesch status here? https://github.com/geoadmin/wms-bgdi/pull/42 was reverted.
What do we really need to implement? This is still not clear for me...

**Comment by davidoesch** [comment]
for now we can run this layer like this, but for the future ( longterm we will have requests like in https://github.com/geoadmin/mf-chsdi3/issues/1445#issuecomment-173160895 )

**Comment by gjn** [comment]
@cedricmoullet How to continue with this? It's first priority...

**Comment by gjn** [comment]
Everything is in db now and auto-imported every week. So we can close this.
