### ISSUE TITLE
API documentation: Iframe example agnostic src url

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-chsdi3#1451]
Iframe src url should be agnostic in order to get actual protocol (http or https) from the webpage

**Comment by kandre** [comment]
@gjn Would be nice for this deploy as it crashes our iframe exmaple on int. What do you think ?

**Comment by kandre** [comment]
#1452

**Comment by gjn** [comment]
#1453 should fix this. We can always use https, and it will work on http sites.
