### ISSUE TITLE
Clean static files

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-chsdi3#1458]
Currently the folder chsdi/static contains 131MB of images specific to you. Can they be remove of this project or at least managed in a subrepo? It would avoid us to have those huge unnecessary data.

cc @tigerfoot

**Comment by gjn** [comment]
Inside our team, we have little experience with submodules, so we would prefer to keep everything together in one repository.

Also 131MB is not much these days.

**Comment by loicgasser** [comment]
Agree
