### ISSUE TITLE
Get rid of _parse_ts or update boto

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1474]
The _parse_ts function has some risks because it depends on current locale [1]. We should try to get rid of it. So instead of using accessing the s3 bucked object [here](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/files.py#L228) and [here](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/files.py#L238), we could directly set `last_updated=now`.

[1] https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior

**Comment by gjn** [comment]
@loicgasser @procrastinatio I think we were really unlucky. We are using boto 2.29.1. A fix for the parse_ts troubles was introduced with 2.30 by https://github.com/boto/boto/commit/35e0b983fa55922f2d65ba298d25a72b5ced8663 which gets rid of the trouble of parsing a string like `Wed, 27 May 2015 18:37:00 GMT` with boto's parse_ts function.

So we can either to the above to be on the safe side or update boto and use its parse_ts function again. Thoughts?

**Comment by loicgasser** [comment]
Let s leave it as it is and I ll update boto/change this function as part of my PR we can merge after the deploy. This will give us the time to test the while thing. Ultimately your call.

**Comment by gjn** [comment]
Agree with that.

**Comment by procrastinatio** [comment]
Agree.

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-chsdi3/pull/1466
