### ISSUE TITLE
MapProxy: WMTSCapabilities.EPSG.2056.xml not in all langs

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1478]
https://mf-chsdi3.int.bgdi.ch/1.0.0/WMTSCapabilities.EPSG.2056.xml not available in all langs

**Comment by procrastinatio** [comment]
So [FR](https://wmts10.geo.admin.ch/1.0.0/WMTSCapabilities.EPSG.2056.xml?lang=fr) and [DE](https://wmts10.geo.admin.ch/1.0.0/WMTSCapabilities.EPSG.2056.xml?lang=de)
