### ISSUE TITLE
Store kml files gzipped

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1488]
According to [1], it should be possible to store and serve gzipped files (in our case kml) to S3. In order to do that, we need to gzip the file and put the content-encoding header accordingly when storing the file to S3.

The downside is that clients that don't support the deflate option (Accept-Encoding: deflate, gzip,...). Most browser do support this options, but I didn't find a list of clients _not_ supporting it. Does anyone know?

[1] http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3

**Comment by procrastinatio** [comment]
Yes, it works (I have done tests), but for now requests on _public.geo.admin.ch_ only count for a few [ppm](http://en.wikipedia.org/wiki/Parts-per_notation). So if we really want to reduce the bandwith, we would gain much more improving S3 caching or further optimizing PNG

The main issue is not [storing files in S3](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/files.py#L207), it is managing metadata when backuping and restoring.

Maybe a duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2362

**Comment by loicgasser** [comment]
We need to have only one type of files per bucket. (so no kmz)
I propose that we gzip all the kml files we already have.

Then we would know that Content-Encoding is always 'gzip' and Content-Type is always 'application/vnd.google-earth.kml+xml' and Content-Length is set automatically on S3.

@gjn delflate option is transparent is all browsers nowadays. http://webmasters.stackexchange.com/questions/22217/which-browsers-handle-content-encoding-gzip-and-which-of-them-has-any-special

**Comment by procrastinatio** [comment]
So please merge https://github.com/geoadmin/mf-chsdi3/pull/1473 before as a lot as been refactored, efore I'll dot it.

**Comment by gjn** [comment]
References misses mobile browsers. And maybe exotic clients that _could_ be used to download those kml's.

**Comment by procrastinatio** [comment]
@gjn Varnish will gunzip the file for the client not sending *Accept-Encoding: gzip*. So, no souci.

**Comment by gjn** [comment]
This is working fine. Thanks alot.
