### ISSUE TITLE
service public transportation Stationboard 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#1492]
Situation
with ch.bav.haltestellen-oev we will have public transportation points displayed on the map. The tooltip should contain (NTH) at least some information regarding the connections. We can't use SBB  service (since there is no official API and roting is not TU independent)  or transport.opendata.ch (not official)

Task
- [x] Arrival-/Departure times at stops, will be provided on data.geo.admin.ch by third party 
- [x] data will be delivered to data.geo.admin.ch/ch.bav.haltestellen-oev/ 
- [x] add delivered data to BGDI DB
- [ ] build a stationboard service with *same* parameter as in http://transport.opendata.ch/#stationboard more http://transport.opendata.ch/ 
- [x] add in the tooltip template of ch.bav.haltestellen-oev as in http://www.timeforcoffee.ch/ the next three connections

UI
- [x] Filter by
-- line number and a box around as in timeforcoffee (MUST v2)
-- direction 
-- departure time ( countdown !)

- [x] if departure info is missing: create a msgid display: no data available
- [ ] replace title "next departure "Your next departures from + "stationname"
- [x] countdown in minutes (not hours) and bold font as in timeforcoffee.ch (MUST v2)
- [ ] countdown if smaller than 5 min:bold font and red
- [ ] countdown if now :red symbols as in http://www.fahrplanfelder.ch/en/explanations/explanation-of-symbols.html#c160
- [x] content tooltip: reduce it to the next 4, add as well the station name as in the DI formular, 
- [x] add a link at the bottom to expert tooltip containing all the tooltip info according to the spec and the next 25 departures

Must for v1:
- [x]  Code review backend: gjin 
- [x] Code review backend: oteral
- [x] Dokumentation in api3.geo.admin.ch as "Service Stationboard" , based on http://transport.opendata.ch/#stationboard , incl a migration help as well
- [x] 	Ersatz Haltestellen TLM durch Haltestellen BAV in swisssearch -> mit Marcel

Must for v2:( update 16 december)
- [x] tooltip: change "Next departures from STATION" to " STATION :next departures to "
- [x] expert tooltip: put link to object into footer as in https://api3.geo.admin.ch/rest/services/swisstopo/MapServer/ch.swisstopo.lubis-luftbilder_schwarzweiss/19652280023398/extendedHtmlPopup?lang=en
- [x] resize icon to same size as in zoom=11 for zoom=12 and zoom=13 (since we have complains that the tooltip does not work on those zoomleve, due to missing the center....so lets reduce the icons size) 

FYI @mariokeusen @AFoletti @ltclm @cedricmoullet

**Comment by davidoesch** [comment]
this one : use the http://gtfs.geops.ch/ complete feed stop_times.txt Arrival-/Departure times at stops, here I have to double check with BAV .. data is already cleaned....

**Comment by davidoesch** [comment]
Data will be delivered by geops onto our infra data.geo.admin.ch

**Comment by procrastinatio** [comment]
So this will be a single fully denormalized flat file with all departures for all stations for a given period (one week) ?

**Comment by davidoesch** [comment]
one file is the goal, BAV is spec, the Datenintgerationformular

**Comment by mariokeusen** [comment]
I have received a message from geOps. They have delivered something on data.geo.admin.ch/ch.bav.haltestellen-oev:
departures.zip, containing a CSV table with totally flat structure (4GBs large).

Could you please make a check, if the delivery is useful in order to reach the above described goal?

**Comment by procrastinatio** [comment]
[departures.zip](http://data.geo.admin.ch/ch.bav.haltestellen-oev                                                                                                                 /departures.zip) (684 MB)


Format

```
stop,time,type,label,destination,via
8507110,2015-08-13T16:32:00Z,0,9,"Wabern, Tram-Endstation","Bern, Zytglogge; Bern, Bärenplatz; Bern, Bahnhof; Bern, Hirschengraben; Bern, Monbijou; Bern, Sulgenau; Bern, Wander; Bern, Schönegg; Bern, Sandrain; Wabern, Gurtenbahn"
8590099,2015-08-14T13:48:00Z,3,29,"Wabern, Lindenweg","Köniz, Steinhölzli Märit; Bern, Steinhölzli; Köniz, Lerbermatt; Bern, Morillon; Wabern, Gurtenbahn; Wabern, Eichholz; Wabern, Camping Eichholz; Wabern, Weyergut; Wabern, Weyerstrasse; Wabern, Bächtelen; Wabern, Kleinwa

```

**Comment by davidoesch** [comment]
@procrastinatio I can not find teh stop ids (8590099, 8590099) in the DB for ch.bav.haltestellen-oev integerated by @AFoletti 

-> can you both confirm this? if yes BAV has to redeliver the stationboard since otherwise we will not be able to link the stationboard with ch.bav.haltestellen-oev

**Comment by AFoletti** [comment]
the IDs are stored in the "nummer" attribute

**Comment by davidoesch** [comment]
@procrastinatio if I enter "Wabern, Tram-Endstation" in http://transport.opendata.ch/examples/stationboard.html "  I get "8571395" and not "8507110 "  _ me_stupid?

"station":{"id":"008571395","name":"Wabern, Tram-Endstation","score":null,"coordinate":{"type":"WGS84"
,"x":46.928024,"y":7.452641},"distance":null},"stationboard":[{"stop":{"station":{"id":"8571395","name"
:"Wabern, Tram-Endstation","score":null,"coordinate":{"type":"WGS84","x":46.928024,"y":7.452641}

**Comment by AFoletti** [comment]
@pfanguin , could you please add some info about you work about this ticket until now?

Some more info about the tooltip ( @davidoesch correct me if I miss something):
- please implement the possibility to filter the departures per "label" et "destination". 
- the tooltips (normal and extended) should have a way to filter by those two attributes (something like a drop-down menu?).
- according to the data model, each station has 0..1 transport type. This helps you because you do not need to filter by transportation type

**Comment by davidoesch** [comment]
Filter for
-- line number
-- direction 
-- departure time ( countdown !)

**Comment by AFoletti** [comment]
line number = label
direction = destination
departure time: do you really want a filter on that? Something like set the clock and see the next three connections starting from that time?

**Comment by davidoesch** [comment]
from a UI perspective there I assume are 3 colums, so a filter (A-Z and Z-A) in the head row for all three rows make sense and easier to use...

**Comment by gjn** [comment]
Departure time is most important info; so we need to be able to filter on it on db side. It's like http://www.timeforcoffee.ch/ but with interactive map.

**Comment by chregu** [comment]
JFYI: We're currently trying to add more real-time departure data to the timeforcoffee API. Maybe it's of interest for you

**Comment by pfanguin** [comment]
Test link: 

https://mf-geoadmin3.dev.bgdi.ch/fap_oev/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bav.haltestellen-oev&layers_opacity=0.75&X=152084.00&Y=538184.00&zoom=9

**Comment by davidoesch** [comment]
Tooltip does not show / activated on mobile  ios / safari / chrome

**Comment by pfanguin** [comment]
It's work now. Staging actually : 

- 10 next departures
- no refreshing 
- Destination
- Type transportation
- Line number

**Comment by davidoesch** [comment]
Ah nice

@pfanguin

A) departure info is missing
http://www.awesomescreenshot.com/image/677338/92825274de2554ef88a3d3a3f4321366
for https://mf-chsdi3.dev.bgdi.ch/fap_oev_service/shorten/67afdc4c70
-> in such cases, if there is really no info (check sources): create a
msgid display: no data available

B) Type transportation icon  in first row: not needed , line number is
enough, sapce saved

C) replace title "next departure "Your next departures from + "stationname"

D) date: not needed: remove yyyy/mm/dd ( will then fit as well on mobile

E) countdown : add a col add the end with how many min left (5' etc) to
departure time in bold. if now: add symsbols as in
http://www.fahrplanfelder.ch/en/explanations/explanation-of-symbols.html#c160
 or you add fontawesome for
train: http://fortawesome.github.io/Font-Awesome/icon/train/
bus/tram/cablecar http://fortawesome.github.io/Font-Awesome/icon/bus/
ship: http://fortawesome.github.io/Font-Awesome/icon/ship/

F) content tooltip: reduce it to the next 4, add as well the station name
as in the DI formualr, add a link at the bottom to expert tooltip
containing all the tooltip info according to the spec and the next 25
departures

Filtering : ask oterral/jeiziner how it was done in "object information" so
we can use the same interface . for each col add a simple button
http://fortawesome.github.io/Font-Awesome/icon/sort/ which activates on
first click sorting on col (make sort icon on this col red) and  inverts on
second click, default: time departure


@mario
missing:
-legend
-abstract is really really rudimentary (remember this is what is in the
search afterwards , kapitel 1.1 is a good base for it
file:///C:/Users/Eltern/Downloads/2%2529_V1_d.pdf

- Detail description: http://www.fahrplanfelder.ch/ check with BAV but this
is a must-- Order data: http://www.fahrplanfelder.ch/ check with BAV but
this is a must  , really nice if we could add here the data.geo.admin.ch
link as well


Thanks all!

**Comment by pfanguin** [comment]
Test link https://mf-geoadmin3.dev.bgdi.ch/fap_oev/
Staging :
- refresh page every seconds
- waiting time 

Next step : 
Filter by destination

**Comment by davidoesch** [comment]
Nice

-my comment: takes quite a while the tooltip connection loads ( use eg 2G
emulation under chrome)

-Filtering : ask oterral/jeiziner how it was done in "object information"
so we can use the same interface . for each col add a simple button
http://fortawesome.github.io/Font-Awesome/icon/sort/ which activates on
first click sorting on col (make sort icon on this col red) and  inverts on
second click, default: time departure

-added those points below to
https://github.com/geoadmin/mf-chsdi3/issues/1492

   -

    if departure info is missing: create a msgid display: no data available
   -  replace title "next departure "Your next departures from +
   "stationname"
   -  countdown in minutes and bold font
   -  countdown if smaller than 5 min:bold font and red
   -  countdown if now :red symbols as in
   http://www.fahrplanfelder.ch/en/explanations/explanation-of-symbols.html#c160
   -  content tooltip: reduce it to the next 4, add as well the station
   name as in the DI formular,
   -  add a link at the bottom to expert tooltip containing all the tooltip
   info according to the spec and the next 25 departures

@mario
missing:
-legend
-abstract is really really rudimentary (remember this is what is in the
search afterwards , kapitel 1.1 is a good base for it
file:///C:/Users/Eltern/Downloads/2%2529_V1_d.pdf

**Comment by gjn** [comment]
Can't wait to have this in!

It seems that left-click does not always work. On same point, it sometimes work, sometimes doesn't. In the network tab, I see requests to transports service being made.

A request every second is quite heavy. Is this a must or can it be reduced? (We should use server side events for this...but I doubt our infra is ready for it)

**Comment by gjn** [comment]
The requests continue, even when I close the htmlpopup. We should stop the requests in such a case.

**Comment by AFoletti** [comment]
plus, if you close the tooltip the requests are not stopped

**Comment by davidoesch** [comment]
why not solve this on client side? load the the data of the next ten
minutes and  let the countdown be done in tooltip. after 10 minutes (or
when no conenctions are left to show: load then from server new data)

**Comment by oterral** [comment]
You can put a refresh button on top of the list, to avoid the infinite request.

**Comment by davidoesch** [comment]
Na --- in 2015 refresh Button- come on: Why not solve it on client side? Download once the next ten minutes. Then show a timeout. On mobile: continuing requests won't work anyway--- so IMHO go for a client side approach

**Comment by gjn** [comment]
Long term, we need server-side events for this kind of data.

Now, we do reasoable polling on client. Every second is way too much. Every minute should be enough for this kind of data.

**Comment by pfanguin** [comment]
Staging : 

- Filtering by destination
- Refresh every minute
- Stop refresh after 20 request 
- Next five departures by destination


Next : 
- If empty data return "no data"
- Code optimization

Test link : https://mf-geoadmin3.dev.bgdi.ch/fap_oev/

**Comment by davidoesch** [comment]
The Filter position has to be improved- below station name

Then we need the filter as well applicable for the line number. See timeforcoffe.ch .




As regarding the spec: the filter makes more sense than the sort.


The loading on mobile takes very long (20sec)




Since this tooltip is mainly used on mobile : keep loading performs bin mind

**Comment by davidoesch** [comment]
first feeback added above
- countdown in minutes (not hours) and bold font as in timeforcoffee.ch otherwise it is not clear what the last col is (1:02 can be an actual hour)

- line number and a box around as in timeforcoffee : otherwise line number 10 could mean in 10min

**Comment by davidoesch** [comment]
@pfanguin 
Must for v2:( update 16 december)
- [ ] tooltip: change "Next departures from STATION" to " STATION :next departures to "
- [ ] expert tooltip: put link to object into footer as in https://api3.geo.admin.ch/rest/services/swisstopo/MapServer/ch.swisstopo.lubis-luftbilder_schwarzweiss/19652280023398/extendedHtmlPopup?lang=en
- [ ] resize icon to same size as in zoom=11 for zoom=12 and zoom=13 (since we have complains that the tooltip does not work on those zoomleve, due to missing the center....so lets reduce the icons size)

**Comment by gjn** [comment]
@pfanguin Can you update the states of the todo's in Dave's list?

**Comment by gjn** [comment]
ping @pfanguin

**Comment by pfanguin** [comment]
Todo : 
- Filter (column) ? 
I don't know if it is still actual ? @davidoesch ?

**Comment by davidoesch** [comment]
Filter by col not needed.

**Comment by gjn** [comment]
@davidoesch Can we close this?
