### ISSUE TITLE
Print post query produces a 500

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1497]
![image](https://cloud.githubusercontent.com/assets/319676/8053895/e910cd7c-0e94-11e5-91b9-a7db64808c43.png)

**Comment by cedricmoullet** [comment]
These requests are generated by monitor.us

**Comment by procrastinatio** [comment]
MapFish Print v2 is not very fault tolerant. Almost any error [1] in the spec file makes the server crash. 

[1] Missing parameter, invalid valid, missing ressource, etc.
