### ISSUE TITLE
Datenstand problem 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#1511]
From Marcel:

Die Zeit stimmt hier immer noch nicht überein? Dies war letzte Woche bereits mehrmals nicht korrekt.
![test](https://cloud.githubusercontent.com/assets/621420/8155051/6e00cca8-1340-11e5-9896-9e12a3859ce5.jpg)

**Comment by procrastinatio** [comment]
We did check the BOD, the `datenstand`are correct. But the link to the legend is cached: _http://api3.geo.admin.ch/1433939002/rest/services/ech/MapServer/ch.bazl.luftfahrthindernis/legend?lang=fr_  So for this type of layer, it would be better not to cache (use _http://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bazl.luftfahrthindernis/legend?lang=fr) or lower the cache period to a smaller intervall than the data actualisation.

**Comment by cedricmoullet** [comment]
@procrastinatio could you prepare a PR ?

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/2430

**Comment by procrastinatio** [comment]
map.geo.admin.ch makes uncached requests on the legend service.
