### ISSUE TITLE
Some External WMS (via ogcproxy)  doesn't work on prod and int but works on dev

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#1513]
Fail:

https://api3.geo.admin.ch/ogcproxy?url=http%3A%2F%2Fwww.geoservice.apps.be.ch%2Fgeoservice%2Fservices%2Fa4p%2Fa4p_planungwms_d_fk_s%2FMapServer%2FWMSServer%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0

Success:

https://mf-chsdi3.dev.bgdi.ch/ogcproxy?url=http%3A%2F%2Fwww.geoservice.apps.be.ch%2Fgeoservice%2Fservices%2Fa4p%2Fa4p_planungwms_d_fk_s%2FMapServer%2FWMSServer%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0

**Comment by procrastinatio** [comment]
What are the errror ?

**Comment by cedricmoullet** [comment]
@oterral still the case ?

**Comment by oterral** [comment]
Can't reproduce
