### ISSUE TITLE
geojson layers ignore maxResolution

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#1515]
The new geoJson layertype ignore the maxResolution parameter from the LayersConfig.

Layersconfig: http://mf-chsdi3.demo.bgdi.ch/ltfoa_treasurehunt/rest/services/all/MapServer/layersConfig?lang=de
(search for ".treasurehunt")

app: http://mf-geoadmin3.demo.bgdi.ch/ltfoa_geoadmintrasurehunt/?X=206055.20&Y=607357.63&zoom=0&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.treasurehunt

This development is needed for the treasurehunt update running now

**Comment by procrastinatio** [comment]
Fix in https://github.com/geoadmin/mf-geoadmin3/pull/2437
