### ISSUE TITLE
Fix GeoJSON example because of OL3.6

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1523]
http://api3.geo.admin.ch/examples/geoadmin_geojson.html
Something like
-    var vectorSource = new ol.source.GeoJSON({
-        url: "{% url 'geojson_data' %}"
+    var vectorSource = new ol.source.Vector({
+        url: "{% url 'geojson_data' %}",
+        format: new ol.format.GeoJSON({defaultDataProjection : 'EPSG:21781'})
     });

**Comment by kandre** [comment]
This pending PR #1507 should fix the non longer supported class GeoJSON (now incuded in Vector class) with ol3.6
