### ISSUE TITLE
Move GeoJSON layer to https

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1532]
in `layersConfig`, but `data.geo.admin.ch` has not support for https now... The host should be moved beyond the standard combo.

This is no problem in _map.geo.admin.ch_ : because we use `ogcproxy`, but only  in the API3.

**Comment by procrastinatio** [comment]
`data.geo.admin.ch`will support HTTPS

**Comment by procrastinatio** [comment]
Did change the sources for `geojson`type int the `layerjs` table. Should be solved with the next BOD deploy.

**Comment by cedricmoullet** [comment]
@procrastinatio is it solved ?

**Comment by procrastinatio** [comment]
From my point of view yes.
