### ISSUE TITLE
[Print] north arrow looks unprofessional

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1535]
according to customer feedback. See [morges](http://map.morges.ch/) for a nice example.

![morges](https://cloud.githubusercontent.com/assets/1236739/8425624/e86191a8-1f07-11e5-831e-dfcf2f77c43f.png)

**Comment by davidoesch** [comment]
application north arrow: let it as ist is
PDF north arrow: the one from morges is nice

**Comment by gjn** [comment]
@davidoesch New print arrow:
![image](https://cloud.githubusercontent.com/assets/2572317/19306841/d624b532-9077-11e6-89da-11995e584731.png)

Go?


https://github.com/geoadmin/service-print/pull/19

**Comment by davidoesch** [comment]
Clear go

**Comment by gjn** [comment]
Will be deployed next week.
