### ISSUE TITLE
swisssearch result: if no fullmatch found - return this as info 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#1537]
Feedback from veloland

Situation
if entered "öllwk" in search service, as result there is no perfect match as expected. Use case: if there is no perfect match- provide info to client that there is none and no result will be shown on client side

task: adapt service

- [ ] capture the return in swisssearch service of fuzzy search
- [ ] show the fuzzy results after the place search 
- [ ] in a new line in italic and bold not the grey background as "Ajouter a carte"
 the line is called: 
DE : "Meinten Sie ..."
FR : "Vouliez-vous dire .. "
EN  " Did you mean ..."
IT " Forse cercavi ..."
RM "tge manegiais Vus cun quai? "

@ltclm will look if sphinx returns a QS info which might be useful to  drop certain suggestions

**Comment by ltclm** [comment]
Hi Loic, could you take care of that, im not sure if we have to change the sphinxservice itself. It is probably just mf-chsdi.

**Comment by loicgasser** [comment]
There are several ways to approach the problem. Either we simply tell the end user we didn t find any exact match and we re actually providing our best guess, either we add a parameter in the search request to activate/deactivate the fuzzy search.

At the moment the whole thing is handled server side if I recall correctly.
We perform a first search query and if no results are found we perform a second query and then we return the results. Can you confirm my first guess is correct please?

**Comment by ltclm** [comment]
yes, there are two queries: https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/search.py#L118

If the second query is performed, the result has to be declared as fuzzy search result in the gui.
@davidoesch please confirm.

**Comment by gjn** [comment]
So this means we remove the fuzzy search again (which impacts map.geo)?

**Comment by cedricmoullet** [comment]
@davidoesch ?

**Comment by davidoesch** [comment]
No we don't remove the fuzzy search because it makes sense for map Geo . The problem is that it does not make any sense to show any results if user enters nonsense like "lleönki" etc. in geo   Admin we can live with this in map. Wanderland not. Questions: can we improve fuzzy search: show no results if there is absolutely no match or indicate in the service where is a perfect string match. A parameter to switch off the fuzzy search might make sense in the service

**Comment by cedricmoullet** [comment]
We need to discuss this in details. @ltclm could you setup a meeting ?

**Comment by gjn** [comment]
so how much fuzzy is acceptable? no easy decision. Maybe sphinx doc offers some input.

**Comment by davidoesch** [comment]
as discussed today
next steps

- [ ] capture the return in swisssearch service of fuzzy search
- [ ] show the fuzzy results after the place search 
- [ ] in a new line in italic and bold not the grey background as "Ajouter a carte"
 the line is called: 
DE : "Meinten Sie ..."
FR : "Vouliez-vous dire .. "
EN  " Did you mean ..."
IT " Forse cercavi ..."
RM "tge manegiais Vus cun quai? "

@ltclm will look if sphinx returns a QS info which might be useful to  drop certain suggestions

**Comment by ltclm** [comment]
as discussed in here https://github.com/geoadmin/mf-chsdi3/pull/1113
we could use some sort of ``levenshtein distance`` to decide which fuzzy results we would like to show or not.

**Comment by loicgasser** [comment]
should actually be pretty straightforward. I'll do it soon.

**Comment by gjn** [comment]
@loicgasser this is already done.

See https://github.com/geoadmin/mf-chsdi3/pull/1615 and https://github.com/geoadmin/mf-geoadmin3/pull/2662

@davidoesch We can close this, no?

**Comment by davidoesch** [comment]
no

What I expect if the user enter a corrct word like below and ther eis not even a fuzzy result
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/12672093/18a57802-c674-11e5-830e-2a5c2d0dab22.PNG)

 in a new line in italic and bold not the grey background as "Ajouter a carte" the line is called: DE : "Meinten Sie ..." FR : "Vouliez-vous dire .. " EN " Did you mean ..." IT " Forse cercavi ..." RM "tge manegiais Vus cun quai? "

the other ponits are resolved with the tickets you mention

**Comment by gjn** [comment]
I don't fully understand. Only the `Did you mean` text should stay? It's odd to say `Did you mean...` without telling him also what he could have meant.

Shouldn't we simply say `No results found.` in that case?

**Comment by loicgasser** [comment]
From my understanding, we would replace the current texte `Aller à...` with `Vouliez-vous dire...` with a different style if result is fuzzy right (you may have several options)?

**Comment by loicgasser** [comment]
![whatdoyoumean](https://cloud.githubusercontent.com/assets/3306154/12673436/0f4ccdf6-c67d-11e5-9564-763f5201f9b8.png)

Yeah right @gjn this is what I thought.

**Comment by loicgasser** [comment]
so for me it's implemented as well.

@davidoesch Please provide a printscreen of what you want if not happy with it.

**Comment by davidoesch** [comment]
sorry my fault again : it is OK as it is, good job ( and I need to get off screen time now....free my brain)

**Comment by gjn** [comment]
holzhacken!

**Comment by ltclm** [comment]
kuchenbaken!

**Comment by davidoesch** [comment]
Schlittschuhfahren hat geholfen
Am 29.01.2016 1:58 nachm. schrieb "Clausen Marcel" <notifications@github.com
