### ISSUE TITLE
link to object is not time aware

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1558]
**Situation:**
- Choose a time enabled layer (p.e. ch.swisstopo.lubis-luftbilder_schwarzweiss)
- Choose a year
- click feature
- click link to object

**Result:**
- New page opens with feature highlighted, time filter has disappeared.

**Expected Result:**
- New page opens with time filter activated

**Comment by procrastinatio** [comment]
Rapid resolution.
