### ISSUE TITLE
Avoid potential variable clash in global scope

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1585]
Which steps can we do to avoid that our ga.js compilation conflicts with other libararies global definitions? It happened twice in the last month that we had conflicts with 2 different external libraries.

See message in api group:

```
ga.js seems to overwrite the global variable Jx ( on Line 690: Jx=M(Vw.....).

As consequence, Jx-lib no longer works when included before the GeoAdmin-API.  I changed the order of including of the js-Files: Now Jx works as used to but I have no idea if there will be some bug in the API...

As Jx is used by many Applications I recommend to use an other name for this variable or use it only in local context.
```

**Comment by oterral** [comment]
There is clearly a compilation problem in our side. the Openlayers build in the `ga.js` shouldn't create variable on the global scope.

**Comment by elemoine** [comment]
I just took a look at the generated `ga.js` file, and actually I am not sure it includes a global `Jx` variable. There is a `Jx` variable but it's local. It's defined with a `var` which starts with `var zx=`.

On your side were you able to confirm it's a global var?

**Comment by oterral** [comment]
Yes that start with `var` but that overrides window.Jx, if we are on main scope. Just tested in console:

```
window.Jx = 2;
var Jx=3;
console.log(window.Jx);
```

That displays 3

**Comment by oterral** [comment]
But we have fixed this with the `output_wrapper` option on the build (It was like that before the last ol update)

**Comment by elemoine** [comment]
> if we are on main scope

But you're not, thanks to the `output_wrapper` you use in the build config, as you said in your previous comment.

So I think the issue can be closed, right?

**Comment by oterral** [comment]
Yes
