### ISSUE TITLE
select by rectangle 

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1593]
**Situation:**
Problem occurrs when you do multiple select by rectangle on different layers. the previous search results are still in the results lists and are highlighted, even if the layer has been deactivated in the meantime.
* activate layer a
* select by rectangle
* close search result windows by clicking x
* deactivate layer a
* activate layer b
* select by rectangle

https://s.geo.admin.ch/6628331574

**Result:**
Both select by rectangle results are shown, the result of the active layer and the result of the deactivated layer.

**Expected Result:**
Only the latest select by rectangle result should be shown.

**Comment by gjn** [comment]
This issue was moved to geoadmin/mf-geoadmin3#2606

**Comment by ltclm** [comment]
the problem still exists 
https://s.geo.admin.ch/670b35edff
**reproduce as follows:**
* activate both layers
* select by rectangle an area containing features of both layers
* close object information window
* deactivate the the layer with line features
* repeat the same select by rectangle

**Result:**
* lines and points are highlighted

**Expected Result:**
* only points are highlighted

![image](https://cloud.githubusercontent.com/assets/5286659/9956826/f55f8652-5dfb-11e5-9b6a-d89814ad70ba.png)

@mariokeusen .

**Comment by oterral** [comment]
@ltclm  it's only because geoadmin and chsdi have not been deployed since we fix th issue see in [dev](https://mf-geoadmin3.dev.bgdi.ch/?X=153550.00&Y=640700.00&zoom=4&topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.geologie-gisgeol-punkte,ch.swisstopo.geologie-gisgeol-linien)

**Comment by ltclm** [comment]
@oterral thanks for the feedback.
@mariokeusen will be fixed with next deploy.
