### ISSUE TITLE
testi18n

### ISSUE THREAD

**Issue by alcapat** [geoadmin/mf-chsdi3#1595]
https://mf-chsdi3.int.bgdi.ch/testi18n?lang=toto

UC : 
- Default language in browser is set to "romanche" 
- No "lang=xx" is specified on url or xx is not in the list (de, fr, it, rm, en)

Result : the translation doesn't work.
ch.bafu.bundesinventare-bln
ch.bafu.bundesinventare-jagdbanngebiete

Expected : romanche translation
IFC
Asils da selvaschina

**Comment by procrastinatio** [comment]
Don't understand the issue:

`curl -H "Accept-Language: ru"  "https://mf-chsdi3.int.bgdi.ch/testi18n"`
--> DE (default)

`curl -H "Accept-Language: ru,fr-FR;q=0.8,fr;q=0.6,en-US;q=0.4,en;q=0.2"  "https://mf-chsdi3.int.bgdi.ch/testi18n"`
--> FR (first available language)
`curl -H "Accept-Language: ru"  "https://mf-chsdi3.int.bgdi.ch/testi18n?lang=fr"`
--> FR (params overrides headers)

@alcapat Is it not what it is expected ?

**Comment by procrastinatio** [comment]
Well, to test, your only language set in the browser preference has to be 'rm', with no or a bogus `lang`param set...

`curl -H "Accept-Language: rm" "https://mf-chsdi3.int.bgdi.ch/testi18n"` or
`curl -H "Accept-Language: rm" "https://mf-chsdi3.int.bgdi.ch/testi18n&lang=toto"`
   --> not translated
