### ISSUE TITLE
Apache crashes

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1638]
In our logs [1], I could see a couple of apache crashes due to out-of-memory exceptions. These could be observed only on our prod instances that server mapproxy and profile. (vpc-mf0-prod5 and vpc-mf0-prod6)

No analysis done yet.

[1] https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/apache%20crashes

**Comment by procrastinatio** [comment]
The following 4 instances vpc-sphinxsearch-prod-2, vpc-sphinxsearch-prod-1, vpc-wms-prod-5 and vpc-wms-prod-4 are responsible for 2/3 of the crashes...

**Comment by procrastinatio** [comment]
This is a general issue on *all* prod servers. They all crash one day or another:_puppetmaster, wms-prod, shpinx sphinxsearch-prod, mf0-prod and mf0-stateless_.

As Apache act as a proxy for many services (mapserver, wsgi, tomcat) it should be configured to protect the backends.
The cluster _mf0-prod_ with its three memory hogs services is clearly underpowered.
