### ISSUE TITLE
zeitreihen - get rid of meta_xx views

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1639]
As discussed today i have modified the materialized views:
- zeitreihen_master.public.tooltip_15
- zeitreihen_master.public.tooltip_20
- zeitreihen_master.public.tooltip_21
- zeitreihen_master.public.tooltip_22

These view do now contain a new fileld with an integer array of all release years:

``` sql
{2011,2005,2000,1994,1988,1982,1980,1970,1963,1958}
```

The print meta service can now query the tooltip views.

The new database has been deployed to dev.
Changes in db: https://github.com/geoadmin/db/commit/49c8599f4e749cf76e36c73cd15d1a9287266f98

**Comment by ltclm** [comment]
it would be probably better to work on this now in order to avoid future problems with the meta_views 
as described here https://github.com/geoadmin/mf-chsdi3/pull/2013#issuecomment-203902735

**Comment by gjn** [comment]
+1. 

I tried once, but didn't fully understand the data behind it. Might be tricky.

**Comment by ltclm** [comment]
I have removed the  deprecated tables and views from zeitreihen_master.
https://github.com/geoadmin/db/commit/6b068b796022ef87da3db933576d1db5982be84f 
the cleaned db can be deployed after the deploy of code.

**Comment by gjn** [comment]
@ltclm The db change you are refering too broke some of our tests. zeitreiehen and historical maps related.

**Comment by gjn** [comment]
The box2d attribute was removed from the view, but it's still needed in the models for the historical maps.

**Comment by ltclm** [comment]
sorry about that, i fixed the database and deployed it to dev.
https://github.com/geoadmin/db/commit/ffbaf7dbdaa8bb3978cf50fb891d623cf7120657

**Comment by gjn** [comment]
Thanks for the quick fix. Next time quick testrun with such important change ;=)

**Comment by procrastinatio** [comment]
PR #2014 is merged. I guess the case is closed
