### ISSUE TITLE
feature service supports simplified geometry

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1641]
**Problem**
Some layers have huge original geometries (number of vertices per feature) which are slowing down the overall performance of the database access stack (wsgi,sqlalchemy,etc.). We should be able to provide generalized and simplified geometry columns for these layers.
Now we have some workarounds, see:
https://github.com/geoadmin/mf-chsdi3/pull/1624
https://github.com/geoadmin/mf-chsdi3/pull/1621

**Proposition:**
In the **model definition** we have a new optional attribute called **`__highlightGeometry__`**  

``` python
class example(Base, Vector):
    __tablename__ = 'mytable
    __table_args__ = ({'schema': 'public', 'autoload': False})
    __template__ = 'templates/htmlpopup/template.mako'
    __bodId__ = 'bod.layer.id'
    __queryable_attributes__ = ['id', 'name']
    __highlightGeometry__ = 'the_geom_highlight'
    ....
    the_geom_highlight = Column('the_geom_highlight', Geometry(geometry_type='GEOMETRY',
                                                               dimension=2, srid=21781))
    ....
```

If this is attribute is present, the **feature service** is using this geometry column for hilghlighting the features of this layer.

During data integration we can decide, if it is necessary to prepare a simplified highlight column in the database. (p.e. max number of vertices per features could be a trigger).

**Comment by cedricmoullet** [comment]
It looks good to me. @davidoesch @procrastinatio @loicgasser @gjn thoughts ?

**Comment by davidoesch** [comment]
Ok - we already have the same approach for Swiss boundaries...

**Comment by procrastinatio** [comment]
Depending on scale and dataset, you may also:
- clip the bbox of `mapExtent`
- round the coordinates to meter or less

**Comment by gjn** [comment]
Doesn't this apply to all services returning a geometry?

So I would apply to reduced geometry as default geometry (also for intersection, etc) and (if desired) keep the full geometry on a new separate row. Frankly, I can't see a use case where we want to keep huge geometries in the db, so why keep them at all and add complexity to the models/requests?

**Comment by ltclm** [comment]
yes, if the geometry reference of the model is just used for the spatial selection query and the highlight in chsdi, we could just use a simplified geometry source in the database. I will prepare a column in the database and make a pr for ch.swisstopo.geologie-geocover.
We still need the original geometry in the database for mapserver (wms,wfs, tile generation, etc.).

**Comment by ltclm** [comment]
I have replaced the geometry source of ch.swisstopo.geologie-geocover on dev.
The identify request with the simplified geometry is about 3 times faster (2s) than with the original geometry (5s), the simplified geometry response is 200kB, the original geometry response is 900kB.

https://mf-chsdi3.dev.bgdi.ch/rest/services/ech/MapServer/identify?geometry=639250,148850&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1436,782,96&layers=all:ch.swisstopo.geologie-geocover&mapExtent=575500,142550,647300,181650&tolerance=5

https://mf-chsdi3.prod.bgdi.ch/rest/services/ech/MapServer/identify?geometry=639250,148850&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1436,782,96&layers=all:ch.swisstopo.geologie-geocover&mapExtent=575500,142550,647300,181650&tolerance=5

**Comment by gjn** [comment]
I think that's the correct approach. Do we do the same for all the other problematic layers?

**Comment by gjn** [comment]
@ltclm Will all other problematic layers be treated as well? If so, please let us know and also indicate which db's we need to deploy to production.

**Comment by ltclm** [comment]
No we have to decide this for each layer. Some of them have a db access via views, no big problem here, others have direct table access, we have to change the model definition in this case.
Furthermore it would be good to know how the planned postgres->geojson change impacts the whole system before any further changes.

For now we just have to deploy stopo to int and prod.

**Comment by gjn** [comment]
ok. Well, code guard against to big geometries is still in place. User won't get any geometry for those at all.

**Comment by procrastinatio** [comment]
This has been done. No more big geometries, and even if is larger than 10MB (?), it won't be sent to application, but tooltips will show (no highlight though)
