### ISSUE TITLE
Add doc for terrain 'service'

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1654]

**Comment by loicgasser** [comment]
doc about the service will be in 3d-forge, doc about the process in confluence. Agree?

**Comment by gjn** [comment]
No. Terrain service we want to officially release, like WMTS service. But this is relatively small documentation.

Technical documentation in 3d-forge/confluence.

**Comment by loicgasser** [comment]
Ah ooook. np will do when the time comes

**Comment by gjn** [comment]
@loicgasser The quantized mesh spec moved to github: https://github.com/AnalyticalGraphicsInc/quantized-mesh

**Comment by loicgasser** [comment]
Thanks for the info
