### ISSUE TITLE
Error with wmtsgettile.test_epsg2056

### ISSUE THREAD

**Issue by alcapat** [geoadmin/mf-chsdi3#1669]
Hello Marc.

There is a jenkins test failed with chsdi.tests.e2e.test_wmtsgettile.test_epsg2056
http://mf-chsdi3.ci.bgdi.ch/1.0.0/ch.astra.ivs-nat-verlaeufe/default/20100416/2056/17/5/6.png
Tileset (bod) is correct.
Can you please investigate ?

**Comment by procrastinatio** [comment]
The issue is with the source data delivered in a format Mapproxy is not expecting.

`curl -I https://wmts8.geo.admin.ch/1.0.0/ch.astra.ivs-nat-verlaeufe/default/20100416/21781/15/0/3.png`

We hava again:

```
HTTP/1.1 204 No Content
Access-Control-Allow-Origin: *
Content-Length: 0
Content-Type: text/plain
```

Has to be an image format, `image/png` in this case

**Comment by cedricmoullet** [comment]
How to solve this ?

**Comment by procrastinatio** [comment]
This was solved long time ago, but the config got lost in the varnish 3 to 4 migration or in the aftermath.

So @danduk82 has a ticket for that.

This is now an issue because of (https://github.com/geoadmin/mf-chsdi3/pull/1658), mapproxy reducing the image size with `img.quantize(colors, Image.FASTOCTREE)`, the delivered image has to be in a correcte image type.

Many non-web aplications will chock on this.

**Comment by gjn** [comment]
But why is `ch.astra.ivs-nat-verlaeufe` the only layer affected? It's the only test that fails, all other layers for 2056 are ok.

**Comment by procrastinatio** [comment]
All tile pngs are:

`(256x256, 32-bit RGB+alpha, non-interlaced, 99.7%`

but `ch.astra.ivs-nat-verlaeufe`which is

 `(256x256, 16-bit grayscale+alpha, non-interlaced, 97.1%)`

Enought to make `Pillow` choke.

**Comment by gjn** [comment]
Fixable for tomorrow?

**Comment by procrastinatio** [comment]
No, no idea what to try for now. I did try requesting a custom format, desativating the quantizer and various other things in the config. The trouble is, many options are only global and affect all images of the same type.

Using the WMS as a source ?

Small note, mapproxy has only requested about 140 tiles last month

**Comment by gjn** [comment]
I'd use wms for quick fix.

**Comment by gjn** [comment]
wms as source, that is.

**Comment by procrastinatio** [comment]
It's neither quick nor a fix. I give up. Sorry

**Comment by gjn** [comment]
There's no easy fix. We'll fix the test and deploy this anyway. At least this layer will be broken for other configurations (it's not requested often, we we should be able to live with this for some time).

Issue stays open and we try to solve it after deploy.

**Comment by gjn** [comment]
I've quickly tested all layers visually. I've found 2 other layers with same issue:

`ch.swisstopo.vec25-eisenbahnnetz`
`ch.swisstopo.swissbuildings3d`

**Comment by gjn** [comment]
@ltclm just to keep you updated on this issue. We'll deploy mapproxy today where those 3 layers won't work.
