### ISSUE TITLE
tooltips on vd amografik layers do not work anymore

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1676]
Apparently https://github.com/geoadmin/mf-chsdi3/commit/cc4c8c8f4f39a1fea73b509fe4d31cf837f197b5 has broken the amographik tooltips of the following layers:

ch.swisstopo-vd.geometa-nfgeom
ch.swisstopo-vd.geometa-grundbuch
ch.swisstopo-vd.geometa-gemeinde

The same column ``the_geom_gen50``is used for wms and tooltip hilighting, thats why i dont want to simplify the geometry too much. Do you have any short term solution?

https://map.geo.admin.ch/?selectedNode=node_ch.swisstopo-vd.geometa-los1&Y=703000&X=167250&zoom=1&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo-vd.geometa-standav,ch.swisstopo-vd.geometa-gemeinde,ch.swisstopo-vd.geometa-grundbuch,ch.swisstopo-vd.geometa-nfgeom,ch.swisstopo-vd.geometa-los&layers_opacity=0.75,0.75,0.75,0.75,0.75&topic=ech&lang=de

Tooltip Error:
https://mf-chsdi3.dev.bgdi.ch/ltclm/rest/services/ech/MapServer/identify?geometry=646000,117250&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1440,315,96&layers=all:ch.swisstopo-vd.geometa-nfgeom&mapExtent=343000,88500,1063000,246000&tolerance=5

**Comment by davidoesch** [comment]
Already got a Customer complaint --- Prio 1 bug

**Comment by AFoletti** [comment]
posted a PR to correct it. Took some time to dig out the problem

**Comment by gjn** [comment]
Will be deployed to prod today.
