### ISSUE TITLE
CadastralWebMap inconsistencies

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1679]
The MISTRA folks did observe that tiles borders sometime did not maatch at the border (WMTS/WMTS). See print screen. For more info, contact Mr Surka.

![mistra](https://cloud.githubusercontent.com/assets/1236739/10074757/1dfb8fd6-62d2-11e5-9cb1-5cf34242e712.jpg)

Contact bei MISTRA: martin.surka@astra.admin.ch

Via @beat-github

**Comment by cedricmoullet** [comment]
@ltclm ?

**Comment by ltclm** [comment]
I have contacted martin surka to get more infos.

**Comment by procrastinatio** [comment]
Both our WMS and WMTS are using `‚http://wms.cadastralwebmap.ch/WMS`as a source. We do not cache anything locally (except in varnish).

The only strange thing is  the `Cache-Control`header:
```$ curl -I "http://wmts11.geo.admin.ch/1.0.0/ch.kantone.cadastralwebmap-farbe/default/current/21781/25/1052/370.png" 
HTTP/1.1 200 OK
Cache-control: max-age=259200 public, max-age=3600, public```

Shoudl be only 1 hour.

**Comment by procrastinatio** [comment]
Still waiting for response to my request for more informations from MISTRA side.

**Comment by procrastinatio** [comment]
Still no anwser. Resent request for more infos today.
