### ISSUE TITLE
MapProxy 50x

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1680]
Request to  http://wmts12.geo.admin.ch/1.0.0/ch.swisstopo.vec25-eisenbahnnetz/default/20090401/2056/17/5/6.png produces this issue: https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/20150925_Issue50x 

is produced by:

[Fri Sep 25 03:35:51 2015] [error] No handlers could be found for logger "mapproxy.wsgiapp"
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245] Traceback (most recent call last):
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/wsgiapp.py", line 181, in __call__
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     resp = self.handlers[handler_name].handle(req)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/service/base.py", line 30, in handle
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     return handler(parsed_req)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/service/wmts.py", line 90, in tile
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     tile = tile_layer.render(request, coverage=limited_to, decorate_img=decorate_img)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/service/tile.py", line 307, in render
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     dimensions=dimensions, with_metadata=True)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/cache/tile.py", line 106, in load_tile_coord
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     created_tiles = creator.create_tiles([tile])
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/cache/tile.py", line 215, in create_tiles
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     created_tiles = self._create_single_tiles(tiles)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/cache/tile.py", line 239, in _create_single_tiles
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     created_tiles.extend(self._create_single_tile(tile))
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/cache/tile.py", line 258, in _create_single_tile
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     source.as_buffer(self.tile_mgr.image_opts)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/image/__init__.py", line 150, in as_buffer
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     self._buf = img_to_buf(self._img, image_opts=image_opts)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/image/__init__.py", line 289, in img_to_buf
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     defaults=defaults, quantizer=quantizer)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/MapProxy-1.7.0-py2.7.egg/mapproxy/image/__init__.py", line 311, in quantize
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     img = img.quantize(colors, Image.FASTOCTREE)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/Pillow-2.8.1-py2.7-linux-x86_64.egg/PIL/Image.py", line 992, in quantize
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245]     im = self.im.quantize(colors, method, kmeans)
[Fri Sep 25 03:35:51 2015] [error] [client 10.220.6.245] ValueError: image has wrong mode

**Comment by procrastinatio** [comment]
This is described in https://github.com/geoadmin/mf-chsdi3/issues/1669

These three layers are mixing image type (problems arise when a tile is converted to greyscale):

`ch.swisstopo.vec25-eisenbahnnetz`
`ch.swisstopo.swissbuildings3d`
`ch.astra.ivs-nat-verlaeufe`

**Comment by gjn** [comment]
I'll close the other as duplicate (tests have been temporarely fixed), but this issue needs to be fixed ....somehow...
