### ISSUE TITLE
strange list of default layers for topic ech

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1683]
If you open map.geo.admin.ch without parameters you will find the following layers in the layer tree, selected but not activated:
* ch.swisstopo.zeitreihen
* ch.bfs.gebaeude_wohnungs_register
* ch.bafu.wrz-wildruhezonen_portal
* ch.swisstopo.swisstlm3d-wanderwege

**Comment by cedricmoullet** [comment]
It's a feature ;-) (of the new layer manager in order to avoid that users have to search within the catalog tree..
