### ISSUE TITLE
Search Layer Objects with Spatial filter (circle, rectangle, polygon) + SearchText

### ISSUE THREAD

**Issue by ltbam** [geoadmin/mf-chsdi3#1694]
For our Client we need following feature when searching for layer objects:

- Filter objects within a (circle, rectangle, polygon).
- Filter objects using a search text.

Example use case:
The user draws a polygon or circle representing a mission critical area, then enters “health” in the search box criteria, performs the search. It will receive back all health troupe available in the specified area.

We use either identifyFeature or Search Feature Services. This feature could be implemented in one of these services, the one that fits better...

**Comment by davidoesch** [comment]
Can we take this offline? We need here to follow the process -> anforderungsklaerung .

**Comment by loicgasser** [comment]
Yes, you can use a circle, a rectangle or any polygon in an identify request and you can use the where clause of the “Object info” tool in geoadmin.
Both can be used together as multiple filters.

For instance (where parameter) for the search text:
where=startofconstruction+>%3D+%272015-10-14%27+and+state+ilike+%27%25A%25%27


For the geometry:
geometry=533000,141000.00000000006,567000,175500.00000000006&geometryFormat=geojso&geometryType=esriGeometryEnvelope&imageDisplay=1920,888,96&mapExtent=180000,-32000,1140000,412000&tolerance=5

Combine all that with the name of the layer and the lang:
&lang=fr&layers=all:ch.bazl.luftfahrthindernis

All that combined

https://api3.geo.admin.ch/rest/services/all/MapServer/identify?lang=fr&layers=all:ch.bazl.luftfahrthindernis&where=startofconstruction+%3E%3D+%272015-10-14%27+and+state+ilike+%27%25A%25%27&geometry=533000,141000.00000000006,567000,175500.00000000006&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=1920,888,96&lang=fr&mapExtent=180000,-32000,1140000,412000&tolerance=5

To know which attributes are queryable:

https://api3.geo.admin.ch/rest/services/all/MapServer/ch.bazl.luftfahrthindernis

**Comment by loicgasser** [comment]
where parameter is not documented
