### ISSUE TITLE
Wrong Attribute-Name in Extended Tooltip in ch.bfe.windenergieanlagen

### ISSUE THREAD

**Issue by cype** [geoadmin/mf-chsdi3#1702]
In the first table of the extended tooltip, there should be written "Name" instead of "tt_ch.bfe.abgeltung-wasserkraftnutzung_name".

Check both extended tooltips, turbine and facility:

https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bfe.windenergieanlagen/turbine_56/extendedHtmlPopup?lang=de

https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bfe.windenergieanlagen/facility_SCH/extendedHtmlPopup?lang=de

**Comment by AFoletti** [comment]
@daguer, I'll let you handle this translation problem

**Comment by cype** [comment]
push
