### ISSUE TITLE
Use date format for date columns

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1703]
We have a lot dates that are in text format. We should change those and use the proper type.
(Date or DateTime for instance)

See for instance:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/uvek.py#L889
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/uvek.py#L890
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/uvek.py#L854

bgdi_created seems to always be in Text for instance. The best would be to check all models and make a big PR containing all the necessary modifications. Of course you can forward it further.

I didn't check if the DB needs to be updated as well, otherwise we simply need to change the makos and the models.

**Comment by AFoletti** [comment]
as a rule of thumb, we do not use much a date format in our tables and we tend to use text instead.
What do you think? Will it be a problem setting them to date format in the model and leave them as text in the tables?
@ltclm : would it make sense to check our tables and change the column format too?

**Comment by loicgasser** [comment]
Dates should be dates, do we need to argue on that?

**Comment by procrastinatio** [comment]
And number should be float or integer...

**Comment by loicgasser** [comment]
that too

**Comment by AFoletti** [comment]
@ltclm and I we discussed the issue a little. Our proposal is to integrate every new layer with the correct data type in the DBs, but not altering the old tables immediately. They will be processed one by one on occasion of a data update.
Is that acceptable to you?
