### ISSUE TITLE
JS API: search results with restricted result

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1715]
When a client duplicates our [example search](http://api3.geo.admin.ch/examples/geoadmin_search.html) and he is outside of BundNetwork, any address results will not have any geometrical informations. This results in the API zooming in to an 'undefined' point, which is completely outside of Switzerland.

The API should be able to handle 'no geometry' results from the search service in this example.

**Comment by gjn** [comment]
Or maybe something for @rfrancel

**Comment by gjn** [comment]
@rfrancel Could you have a look. Don't hesitate to come asking.

**Comment by rfrancel** [comment]
Yes sure, thanks.
