### ISSUE TITLE
Linked data service SPARQL

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#1764]
Linked data access 
provide a Linked data service (TBD)

Starting point
- Geosparql: http://www.opengeospatial.org/standards/geosparql -> implementation does not yet exists
- SPARQL by ordonance survey :http://data.ordnancesurvey.co.uk/docs/sparql  (examples http://data.ordnancesurvey.co.uk/ ) -> IMHO this should be our reference for the service 
- LOD2 Stack http://stack.lod2.eu/blog/ 
- INSPIRE SmOD http://www.w3.org/2015/03/inspire/ 

Here a spec vom GeoKnow for the linked geo services
[D1.2.1_Revised_common_requirements_specification_and_GeoKnow_architectur....pdf](https://github.com/geoadmin/mf-chsdi3/files/39835/D1.2.1_Revised_common_requirements_specification_and_GeoKnow_architectur.pdf)

Current situation:
 http://data.admin.ch/  and   https://github.com/zazuko/bafu_ubd

@p1d1d1 more to add? t

**Comment by p1d1d1** [comment]
* http://d2rq.org/
* W3C Linking Geospatial Data: https://www.w3.org/2014/03/lgd/report
* INSPIRE-RDF-GeoSparql: https://web.imis.athena-innovation.gr/redmine/projects/geoknow_public/wiki/Inspire2RDF
* Example of a Geosparql endpoint: http://geodata.gov.gr/sparql/#editor
* https://ies-svn.jrc.ec.europa.eu/attachments/download/1188/ARE3NA-RDF_vocabulary_guidelines_Final.pdf - Interesting chapter 6.3

**Comment by davidoesch** [comment]
GeoSPARQL with virtuoso http://geodata.gov.gr/sparql/#editor
