### ISSUE TITLE
Map service tests failing for ch.bfs.gebaeude_wohnungs_register

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1769]
test_identify_valid
test_identify_valid_topic_all

Are we supposed to accepect localhost are shall we add an exception when coming accross this layer?

**Comment by gjn** [comment]
Can you point me to the jenkins job?

**Comment by loicgasser** [comment]
For instance:
https://jenkins.ci.bgdi.ch/job/PR_chsdi3/1033/console

**Comment by gjn** [comment]
Why did it start to fail?

**Comment by loicgasser** [comment]
My guess is that it is infra related because nothing has changed in the code.

**Comment by gjn** [comment]
It's on nighlty builds as well now. So most likely infra changes.

@danduk82 What infra changes yesterday could have caused this on dev?

**Comment by loicgasser** [comment]
Related to geometry restrictions on addresses I believe. We could fix the tests, but I also would like to know why it broke so suddenly.

**Comment by danduk82** [comment]
Could someone explain the problem more in detail? I don't get it from the error stack, sorry.
Anyway I do not see major modifications in the infra yestarday, so having more info could lead me into the good direction...

**Comment by procrastinatio** [comment]
Both tests check if "Content-Type: application/json", which is not anymore.. It is "Content-Type: application/json; charset=UTF-8"

**Comment by gjn** [comment]
@ltclm @AFoletti Did we update data on dev yesterday?

@loicgasser It seems that parsing db results is the problem. It fails after the request is made (see https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/tests/integration/test_mapservice.py#L112) and it's the esriencoder that fails to parse the results. Probably a data changed that pushed results over a given treshold?

**Comment by ltclm** [comment]
the esriencoder has probably a problem with 3d coordinate?
```
ret
{'type': 'Point', 'coordinates': (549341.0, 147959.0, 0.0)}
```

It would be good to know the name of the layer.

**Comment by ltclm** [comment]
yes that is possible that yesterday some data has changed, we have automatic data updates every day.

**Comment by gjn** [comment]
Is it possibly db changed from 2D point to 3D point?

**Comment by loicgasser** [comment]
yep no support of 3d coordinates in esriJSON encoder to my knowledge. @procrastinatio can you confirm and extend it as needed?

**Comment by procrastinatio** [comment]
Dic you check the tests ? Both tests mentionned above `test_identify_valid`and `test_identify_valid_topic_all`have the following assertion:
`self.assertTrue(resp.content_type == 'application/json')`
