### ISSUE TITLE
translation of haltestellen categories within swisssearch / gazetteer

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1782]
From https://github.com/geoadmin/service-sphinxsearch/pull/245

@mariokeusen

We need a translation for the Features in ch.bav.haltestellen-oev They are not the DIF, -> can you ask BAV to complete the DIF ? then we can also fix the legends translation as in https://api3.geo.admin.ch/static/images/legends/ch.bav.haltestellen-oev_de.png etc
features: 
"Bedienpunkt Zug"
"Haltestelle Bus"
"Haltestelle Lift"
"Haltestelle Luftseilbahn"
"Haltestelle Luftseilbahn_Zug"
"Haltestelle Metro"
"Haltestelle Schiff"
"Haltestelle Schiff_Zahnradbahn"
"Haltestelle Standseilbahn"
"Haltestelle Standseilbahn_Bus"
"Haltestelle Standseilbahn_Luftseilbahn"
"Haltestelle Standseilbahn_Zug"
"Haltestelle Tram"
"Haltestelle_und_Bedienpunkt Zug"
"Haltestelle Zahnradbahn"
"Haltestelle Zug"
"Haltestelle Zug_Tram"
"reiner_Betriebspunkt Zug"

**Comment by mariokeusen** [comment]
Most easy way to reach that would be to take the translations from the legends, which are available in 4 languages, not?

**Comment by ltclm** [comment]
Hello Mario

Yes thats the easy way indeed :-)
We got the following translations for the ms_class legends:
"haltestellen_luftseilbahn";"Luftseilbahn"
"haltestellen_luftseilbahn_zug";"Luftseilbahn_Zug"
"haltestellen_standseilbahn";"Standseilbahn"
"haltestellen_standseilbahn_bus";"Standseilbahn_Bus"
"haltestellen_standseilbahn_luftseilbahn";"Standseilbahn_Luftseilbahn"
"haltestellen_standseilbahn_zug";"Standseilbahn_Zug"
"haltestellen_bus";"Bus"
"haltestellen_bus_tram";"Bus_Tram"
"haltestellen_tram";"Tram"
"haltestellen_metro";"Metro"
"haltestellen_zug";"Zug"
"haltestellen_zahnradbahn";"Zahnradbahn"
"haltestellen_schiff";"Schiff"
"haltestellen_lift";"Lift"

The following objects are not translated / displayed in the mapfile, so i guess we can remove them from the search? Can you confirm this?
Bedienpunkt Zug
Haltestelle und Bedienpunkt Zug
Haltestelle Zug_Tram
reiner Betriebspunkt Zug

**Comment by mariokeusen** [comment]
Hello Marcel,

We have received a new data delivery for this layer, which includes a bunch of new symbols. And what we also received is a complete list of object/symbol descriptions in 4 languages: see redmine:
https://redmine.prod.bgdi.ch/issues/5758

Update is rather urgent for Dec. 16th (Fahrplanwechsel).

Gruss
Mario

**Comment by ltclm** [comment]
should be coordinated with this change https://github.com/geoadmin/wms-bod/commit/7d018e1461f34e10021c253c20d2b1df525ffbfd
