### ISSUE TITLE
Restricted services should not be cached

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1826]
Restricted services (those using X-SearchServer-Authorized headers) should never be cached by varnish using our general caching-with-numbers approach. Otherwise, it might leak undesired information.

Note: this might impact existing customers and also map.geo.admin.ch.

**Comment by procrastinatio** [comment]
Huke, why not use instead the not-cached version ? If we start with cached and not-cached timestamped versions, this is going to be a mess. I would simply revomed the timestamped version for these services.

**Comment by gjn** [comment]
It's the search service and the restricted information is a rare case.

I'll try with the Vary header, if this doesn't work, we probably don't use the uncached version.

**Comment by procrastinatio** [comment]
@gjn did you tried `Vary: Referer`?

**Comment by gjn** [comment]
No.

**Comment by rebert** [comment]
use vary header on restricted services, this is a must if we want cloudfront in front of the api

**Comment by loicgasser** [comment]
We don t have any restriction in the project anymore.

**Comment by gjn** [comment]
yeah.
