### ISSUE TITLE
tlm3d-karte wrong configuration of lowest lod

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1827]
It seems that there is something wrong with the lowest lod configuration of 
ch.swisstopo.swisstlm3d-karte-farbe
ch.swisstopo.swisstlm3d-karte-grau

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-karte-farbe,ch.swisstopo.swisstlm3d-karte-grau&lon=7.95610&lat=46.24804&elevation=2232&heading=170.341&pitch=-23.046

![image](https://cloud.githubusercontent.com/assets/5286659/12011741/5dfb0b46-acda-11e5-905f-f8f79b5e461b.png)

**Comment by cedricmoullet** [comment]
@ltclm @procrastinatio @gjn @danduk82 AFAIK, tiles have been generated for this layer. Do we have an issue in S3 ? Or wrong varnish config ?

**Comment by cedricmoullet** [comment]
Error is:
An error occurred in "": Failed to obtain image tile X: 266 Y: 59 Level: 8.

**Comment by ltclm** [comment]
this are 2d tiles served via mapproxy. they are fine in 2d. probably mapproxy config ?

**Comment by gjn** [comment]
As Marcel said, these are not the pre-generated tiles, but the mapproxy tiles of the 2D tiles. 
So if this is an error, then it's a mapproxy config issue...and there from the start.
Am 28.12.2015 2:22 nachm. schrieb Clausen Marcel <notifications@github.com>:this are 2d tiles served via mapproxy. they are fine in 2d. probably mapproxy config ?

**Comment by procrastinatio** [comment]
Looks like it solved.

**Comment by loicgasser** [comment]
I can confirm
