### ISSUE TITLE
[extended tooltip] layout problems with firefox ch.bafu.wasser-teileinzugsgebiete_2km2

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#1828]
UC: open extended tooltip (e.g. https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bafu.wasser-teileinzugsgebiete_2/7817/extendedHtmlPopup?lang=de ) with FF and then press print on the bottom right, in order to print a PDF of the extended Tooltip.

Result: PDF contains 2 pages, but only the first one has content, the second is empty
Expected: PDF contains 2 pages, the first with content as is and the second with a runoff graph and the map extent.

**Comment by AFoletti** [comment]
will have a look at it

**Comment by gjn** [comment]
@AFoletti state?

**Comment by AFoletti** [comment]
i'm working on it, but 'it quite strange if you ask me

**Comment by AFoletti** [comment]
The various elements of the mako are OK, but FireFox is not correctly handling the content overflow from the first page.
I tried to force the overflow to no avail. A forced page break at the end of the table is useless too. I think I need help on this one :)

**Comment by oterral** [comment]
We have discussed with @AFoletti  it's just a css bug.
