### ISSUE TITLE
[ch.swisstopo.zeitreihen] FF: missing link to geoportal in quickview of 1:100 000 map material

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#1841]
UC: open e.g. https://api3.geo.admin.ch/historicalmaps/viewer.html?lang=de&layer=ch.swisstopo.zeitreihen&release_year=1960&title=kartenwerk_lk100&height=8250&width=11400&bildnummer=bv80032185&x=5700.00&y=4125.00&zoom=2&rotation=0 or another quickview out of the tooltips of a map sheet in 1:100 000 scale in Firefox and watch the top right part of the window

Result: there is no permalink to the corresponding map sheet in the geoportal visible
Expected: permalink to the corresponding map sheet in the geoportal is available like in IE, Chrome...

Issue in Firefox only. All other browsers are ok.

**Comment by loicgasser** [comment]
Firefox version please, it's fine on Mozilla Firefox for Ubuntu version 44.0

**Comment by mariokeusen** [comment]
42.0 (on chtopo computers)

**Comment by ltclm** [comment]
There is already an issue for this:
https://github.com/geoadmin/mf-chsdi3/issues/1755
