### ISSUE TITLE
Deploying a snapshot uses the wrong configuration

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1854]
When one deploys a snapshot to prod or integration rather than using the file in

`deploy/deploy.cfg` of the snapshot being deployed it uses the configuration from which the command is being exectued from. (Most likely the use environment)

I believe this is dangerous and should be addressed.

@gjn @procrastinatio makes sense to you as I guess.

**Comment by procrastinatio** [comment]
Yes, fully agree.

The other issue is that the target list in the `deploy.cfg` should be dynamic (got from a service somehow), as the cluster size is sometime changing. For instance, for DBs, the deploy script uses a nightly generated config.

**Comment by loicgasser** [comment]
That would be nice @procrastinatio . You think it's doable without too much effort here?

**Comment by oterral** [comment]
+1 for a generated config
