### ISSUE TITLE
tooltip bfs adressen is not working anymore

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1866]
Issue has been reported via webgis mailbox.

Tooltip is not working anymore on the aggregate layer ch.bfs.gebaeude_wohnungs_register

p.e click on house number 1 in this url
https://map.geo.admin.ch/?layers=ch.bfs.gebaeude_wohnungs_register&X=215104.30&Y=636241.70&zoom=13&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe

a click on this coordinate results in the following chsdi call
https://mf-chsdi3.prod.bgdi.ch/rest/services/ech/MapServer/identify?geometry=636250.5,215104.375&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1362,1113,96&layers=all:ch.bfs.gebaeude_wohnungs_register_wms&mapExtent=635989.25,214858.125,636329.75,215136.375&returnGeometry=true&tolerance=10

Identify is called with the group member ``ch.bfs.gebaeude_wohnungs_register_wms``. 

It should be called with the parent layer id ``ch.bfs.gebaeude_wohnungs_register`` 
https://mf-chsdi3.prod.bgdi.ch/rest/services/ech/MapServer/identify?geometry=636250.5,215104.375&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1362,1113,96&layers=all:ch.bfs.gebaeude_wohnungs_register&mapExtent=635989.25,214858.125,636329.75,215136.375&returnGeometry=true&tolerance=10

**Comment by loicgasser** [comment]
It must be related to layersConfig, I am having a look at it right now.

**Comment by loicgasser** [comment]
seems more like a geoadmin bug

**Comment by loicgasser** [comment]
`map.forEachLayerAtPixel` works on sublayers only....

**Comment by loicgasser** [comment]
Bug introduced by https://github.com/geoadmin/mf-geoadmin3/commit/266348b06bbb92d42e9a4aeeade2920486c2dceb#diff-620c4d1d708e7f9116bb7328f3e202ec

I propose that we use the serverLayerName and keep the current code.

**Comment by loicgasser** [comment]
mmh, but it's possible we have two sublayers with the same `serverLayerName` under the cursor.

**Comment by gjn** [comment]
In that case, only make the request once.

**Comment by loicgasser** [comment]
I have a patch but my own project is Forbbiden

**Comment by ltclm** [comment]
thanks @loicgasser , that was at lightning speed!!

**Comment by loicgasser** [comment]
That was important, thks for noticing
