### ISSUE TITLE
Make link clickable in layer information of ch.swisstopo-karto.skitouren

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1880]
![image](https://cloud.githubusercontent.com/assets/319676/12774217/13f77c74-ca43-11e5-93a5-fb21230e9e4e.png)

Link to http://www.sac-cas.ch/guides like for layer "Itinéraires en raquette"

**Comment by AFoletti** [comment]
Thanks to our geocat team, the entry was modified to include the HTML code.
Looks perfect in our infobox, but ugly in geocat because the code is not interpreted.
