### ISSUE TITLE
CadastralWebMap link update

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1900]
Die URL für die Weiterleitung von CadastralWebMap für den Kanton Jura hat geändert:
ALT:
http://mapfish.jura.ch/main/wsgi/theme/Cadastre?&map_x=576462.75&map_y=250151.5&map_zoom=8

NEU:
http://geo.jura.ch/main/wsgi/theme/Cadastre?&map_x=576462.75&map_y=250151.5&map_zoom=8

**Comment by loicgasser** [comment]
fixed via https://github.com/geoadmin/mf-chsdi3/pull/1888
