### ISSUE TITLE
[public transportation] blank row in object information with schedule

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#1904]
UC: open the public transportation layer, open the tooltip of a stop with schedule information (not a Betriebspunkt), look at the layout of the tooltip window.
Result: there is a blank row on top of the informations (see screenshot below).
Expected: remove that blank in order to save space

![bav_obsolete_row](https://cloud.githubusercontent.com/assets/4577749/12949828/535c4f12-d00a-11e5-8075-b9c374e716a4.PNG)

**Comment by oterral** [comment]
@rebert if your PR fixes it, please close

**Comment by rebert** [comment]
will be fixed with #2749
