### ISSUE TITLE
[ch.bazl.luftfahrthindernis] make attribute searchable

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#1911]
Hi Marcel,
as discussed bazl wants to have one attribute searchable over all-in-one:
https://redmine.prod.bgdi.ch/issues/3770

Thanks in advance

**Comment by gjn** [comment]
@ltclm Will the auto-import alos trigger a sphinx update?

**Comment by ltclm** [comment]
yes, table deploys are triggering an update of all dependant sphinx indexes.

**Comment by ltclm** [comment]
https://github.com/geoadmin/service-sphinxsearch/pull/263

**Comment by mariokeusen** [comment]
This is done and works fine. Thanks
