### ISSUE TITLE
Data issue: ch.bafu.hydroweb-messstationen_zustand

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1917]
Messtation: `Mühlbach - Chur (2632)"` has coordinates `0,0` which is probably wrong.

https://api3.geo.admin.ch/ogcproxy?url=https://data.geo.admin.ch/ch.bafu.hydroweb-messstationen_zustand/ch.bafu.hydroweb-messstationen_zustand_fr.json

**Comment by AFoletti** [comment]
Most probably I would say.
But that's an automatically updated json layer. Maybe it would be good to ping the datenherr.
@mariokeusen , could you please ask your contact @ BAFU?

**Comment by mariokeusen** [comment]
Ok, I'll inform them. Did you detect any further objects with such weird coordinate values amongst the 7 hydroweb-layers?

**Comment by AFoletti** [comment]
Problem is still present
@mariokeusen , any news?

**Comment by AFoletti** [comment]
Checked the 7 layers and found 2 0,0 objects
Mühlbach - Chur (2632)
Mühlbach - Chur (9632)

both from ch.bafu.hydroweb-messstationen_zustand

**Comment by mariokeusen** [comment]
Both 0,0 objects have now correct coordinates in the currently running tests, which will be online soon.
See the data integration board (open tickets there for these layers) for further procedure and please always treat data related issues over there

**Comment by AFoletti** [comment]
i'll close this
