### ISSUE TITLE
WSGI configurations in new Makefile setup

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1924]
In buildout setup, the *.ini file used for the mod_wsgi was as follows:

for dev/int/prod in main, it was always production.ini
for user specific environments, it was always development.ini
(was `config-file` paramter of [modwsgi] buildout section.

With Makefile setup, it's as follow:
for dev and all user specifics, it's development.ini
for int/prod it's productions.ini

I think it should be productions.ini in dev main evnironment as well. development.ini should be strictly for development work.

**Comment by loicgasser** [comment]
Agreed, we don't need debugging in main.
