### ISSUE TITLE
Missing table kantone25plus cadastralwebmap

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1939]
@AFoletti @ltclm @alcapat @daguer 

ch.kantone.cadastralwebmap-farbe
kantone25plus

Some Jekins tests are failing because of missing columns on bafu updated layers (which is fine):
https://github.com/geoadmin/mf-chsdi3/pull/1935

But we're also mssing an entire table. 
```
ProgrammingError: (ProgrammingError) relation "kantone25plus" does not exist
LINE 2: FROM kantone25plus
```

could you tell me where it comes from and what you've planned to do?

**Comment by ltclm** [comment]
my mistake,  i have restored the table.

**Comment by loicgasser** [comment]
:+1:  Thank you!
