### ISSUE TITLE
[extended tooltips] layout is broken

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#1957]
UC: open app, select and add a layer with an extended tooltip, pick an object and open extended tooltip
Result: the usual layout of the ext. HTML-tooltip has disappeared. It seems to be fully missing
Expected: extended tooltips are layouted as usual and as designed.

Recognized on Chrome and IE and for all ext. tooltips I tested (ca. 10). Important examples:
Teileinzugsgebiete: https://api3.geo.admin.ch/rest/services/energie/MapServer/ch.bafu.wasser-teileinzugsgebiete_2/77215/extendedHtmlPopup?lang=de Important UC here is print: if you want to print the extentded tooltip into a pdf, the map is blurred in E-W direction.
Luftfahrthindernisse: https://api3.geo.admin.ch/rest/services/aviation/MapServer/ch.bazl.luftfahrthindernis/1199/extendedHtmlPopup?lang=de
Windenergieanlagen: https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bfe.windenergieanlagen/facility_STB/extendedHtmlPopup?lang=de

**Comment by gjn** [comment]
@AFoletti what happened?

**Comment by loicgasser** [comment]
css are missing I think. I ll fix it.

**Comment by loicgasser** [comment]
@alcapat what about a squashTM test on one of those

**Comment by gjn** [comment]
Fixed and deployed.
