### ISSUE TITLE
Remove esrijson hack and papyrus

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1965]
TODO create a pypi module for esriJSON

**Comment by procrastinatio** [comment]
Related issue https://github.com/geoadmin/mf-chsdi3/issues/1336

**Comment by loicgasser** [comment]
`<broken repr (UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 218: ordinal not in range(128))>` that's the esri json object description you get at the moment....

**Comment by loicgasser** [comment]
papyrus will remain and esrijson hack has been removed
