### ISSUE TITLE
Why are those layers supposed to have searchable features and don't have an index 

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1969]
Jenkins fails because of these 2 layers.

ch.swisstopo.geologie-gravimetrischer_atlas.metadata
ch.swisstopo.skitourenkarte-50.metadata

@ltclm @AFoletti @daguer @alcapat Any idea why?

**Comment by ltclm** [comment]
i have set both layers to searchable false in the bod and i have deployed the bod to dev:

**ch.swisstopo.skitourenkarte-50.metadata** is not supposed to be searchable according to ap, i will fix the bod.

**ch.swisstopo.geologie-gravimetrischer_atlas.metadata**  @rfrancel please prepare a sphinx pr with a sphinx pr for this layer. this layer has to be searchable. after the merge of this pr you can set the layer in the bod to searchable againg.

**Comment by gjn** [comment]
They also have the dev wms set. So other tests also failed.
