### ISSUE TITLE
Split mapservice test file

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1977]
At the moment this https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/tests/integration/test_mapservice.py

tests the views in
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/features.py
and
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/layers.py

We perform a lot of tests in this file and it's actually quite long at the moment.
could you split this file in 2 smaller files:
chsdi/tests/integration/test_features.py
and
hsdi/tests/integration/test_layers.py

so that we don't waste too much time when  working locally?

**Comment by loicgasser** [comment]
@rfrancel Maybe you would do that?

**Comment by rfrancel** [comment]
yes, sure.
