### ISSUE TITLE
Code Pen example: rectangle hidden

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1985]
In our rectangle codepen example, when choosing a different scale, the rectangle is hidden behind the selected layer.

It should be visible, as it was in the previous example. This is probably a z-index error or layer order error.

@rfrancel Could you try to fix it?

**Comment by gjn** [comment]
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/static/doc/examples/README.md

**Comment by rfrancel** [comment]
Yes I'll have a look

**Comment by rfrancel** [comment]
Th example works again. The rectangle was added as a new layer, and layers are shown on radio click. I replaced it as a feature overlay,

**Comment by gjn** [comment]
Well done. And fast.

Thanks alot, @rfrancel .
