### ISSUE TITLE
Link to CadastralPortal: Lucerne uses LV95 and not LV03

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1986]
See:
http://www.geo.lu.ch/map/grundbuchplan/?FOCUS=196000.0:465000.0:5480304.0

**Comment by loicgasser** [comment]
@procrastinatio feel like it?

**Comment by AFoletti** [comment]
I'll take this if you agree

**Comment by loicgasser** [comment]
sure you need to transform cooridnates server side that's all.

**Comment by AFoletti** [comment]
@loicgasser the tooltip works fine by me. Could you please test again and, if needed, better describe the problem you are facing?

**Comment by loicgasser** [comment]
You're right it seems to work well from geoadmin. I wonder how I got this URL in the first place.
Maybe https://github.com/geoadmin/mf-chsdi3/commit/bd8b960c1dcf31478c620a89ea1e53fb7681e0c8#diff-ba767b78ad55b55512dc1c46d43bdfed fixed it
