### ISSUE TITLE
Strange behaviour of baseURL by printing WMS layers 

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#2018]
The baseURL for WMS layers in the request payload by printing behaves strangely with some staging/wms combinations

**WMS set to wms-bgdi_prod. Layer staging = int**
Protocol is cut from baseURL. WMS used is on dev. --> NOK
```
 "layer": "org.epsg.grid_4326",
      "opacity": 1,
      "type": "WMS",
      "baseURL": "//wms-bgdi.dev.bgdi.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0",
      "layers": [
        "org.epsg.grid_4326"
      ]
```

**WMS set to wms-bgdi_dev. Layer staging = prod**
Protocol is there again. WMs level is correct. --> OK
```
"layer": "org.epsg.grid_2056",
      "opacity": 1,
      "type": "WMS",
      "baseURL": "https://wms-bgdi.dev.bgdi.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0",
      "layers": [
        "org.epsg.grid_2056"
      ]
```

**WMS set to wms-bgdi_prod. Layer staging = prod**
Protocol is there again. WMs level is correct. --> OK
```
"layer": "org.epsg.grid_4326",
      "opacity": 1,
      "type": "WMS",
      "baseURL": "https://wms.geo.admin.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0",
      "layers": [
        "org.epsg.grid_4326"
      ],
```

With staging=int the baseURL misses the protocol, and the wms level used is not what defined in BOD

**Comment by gjn** [comment]
The wms requests in the application are correct?

**Comment by AFoletti** [comment]
wms visualization works fine in application

**Comment by gjn** [comment]
Are the URLs requests correct? Domains as expected?

**Comment by AFoletti** [comment]
ah sorry, I misunderstood.
And no, it's not correct. Same staging level issue, but protocol is there

**Comment by loicgasser** [comment]
I'll investigate

**Comment by loicgasser** [comment]
Related code is https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/bod.py#L124

Basically we currently create agnostic links in dev and int.

I don't remember why we decided to do so.
I guess links should always be agnostic and we should add the the protocol before sending the config to the print server. (most likely http:// should be enough).

Also graticule wms url is hard coded here:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js#L724

**Comment by loicgasser** [comment]
@gjn some thoughts?

**Comment by gjn** [comment]
Thanks for the analysis!

Not sure print can handle https. So yes, I  would propose to add http to the URL.

In general, I think we have a conflict in that we specify the wms resource in different places. It's in the bod (`wms-bgdi_dev`, `wms-bgdi_int` and `wms-bgdi_prod`), we adapt it depending on staging and configuration used in the bod (bod.py code linked by @loicgasser). But this code is ignored for all productive layers. This also results in our troubles to test changes for layers that are already in prod. We hack around this by putting the layer to dev sometimes (if I'm not mistaken).

In future, we should be able to also specify wms branches (we can branch-deploy wms for all staging environments) - and use these wms branches during **development**, and also for **abnahme** on int/demo instances

Can't tell for now what the best approach would be to configure this. Ideally, it's all in the bod (or in the new 'published' tables)

Any proposals welcome.

**Comment by procrastinatio** [comment]
Mapfish Print needs a protocol. I have to check, but https://wms.geo.admin.ch will work, but _https://wms-bgdi.dev.bgdi.ch_ will not.

**Comment by procrastinatio** [comment]
Yes, we have to find a way to split entirely application development and layer integration.

So if you want to test specific settings, you have to have a custom branch for WMS, getting it's config from a custom mf-chsdi3 branch pointing to a custom BOD, the whole being used by a custom mf-geoadmin3 branch ?

**Comment by gjn** [comment]
@procrastinatio Yes, that's what I would expect to have. Everything completely seperated on branches until we merge it to master.

We can already deploy wms branches - now we need to be able to tell mf-chsdi3/mf-geoadmin3 to use this wms branch. What would be the best approach to configure this?
