### ISSUE TITLE
Some links to bfe don't work

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2026]
For instance ch.bfe.sachplan-uebertragungsleitungen_kraft

for this popup
/rest/services/ech/MapServer/ch.bfe.sachplan-uebertragungsleitungen_kraft/fa38/htmlPopup?imageDisplay=1334,1095,96&lang=fr&mapExtent=553776.3722368001,48871.36078512028,887276.3722368001,322621.3607851203

All links
Sachplan Übertragungsleitungen (SÜL), Konzepte und Sachpläne (Art 13 RPG) - Hauptband
are broken

This is a prod issue

@ltclm @AFoletti @daguer @alcapat 

Who integrated this layer and has info about thoses links?

**Comment by AFoletti** [comment]
I'll take care of this issue

**Comment by AFoletti** [comment]
@loicgasser , the links seem to work again today. Can you confirm that?

**Comment by loicgasser** [comment]
No this is still an issue probably on their side though.
http://www.bfe.admin.ch/php/modules/publikationen/stream.php?extlang=de&name=de_709743059.pdf

**Comment by AFoletti** [comment]
Just to mention it: BFE is checking the issue with the internal IT service. No news until now

**Comment by loicgasser** [comment]
no news? @AFoletti

**Comment by procrastinatio** [comment]
@loicgasser Would it make sense to have a crawler checking all links in `mf-chsdi3` (tooltips content, legends, etc...) instead of checking a few links prior to deploy ?

**Comment by AFoletti** [comment]
Hey, I missed @loicgasser last question, but the issue has not been forgotten.
In fact BFE is migrating their feature attachments storage. We will migrate every BFE link on 26.04

**Comment by gjn** [comment]
@procrastinatio links are also in data. This might be huge task.

And then: what do we do with dead links?

**Comment by AFoletti** [comment]
Link migration for BFE will be deployed next week, but this particular issue has not been adressed.
I asked BFE to doublecheck the links

**Comment by AFoletti** [comment]
links work in IE and FF but not chrome. BFE is looking into that

**Comment by procrastinatio** [comment]
No news, good news.
