### ISSUE TITLE
[SHOP] - Use shop price service for paper maps

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2032]

**Comment by loicgasser** [comment]
If you could provide info about the interface (getPrice API) or a link it would be nice.

**Comment by p1d1d1** [comment]
Puzzle is currently modifying the service according to our discussion with them last week.
As soon as we have a stable service you will be informed

**Comment by loicgasser** [comment]
ok thanks

**Comment by oterral** [comment]
@p1d1d1 is this fixed ?
