### ISSUE TITLE
[ch.bav.haltestellen-oev] departures are not displayed in map.geo.admin.ch

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2038]
UC: open app, load the layer ch.bav.haltestellen-oev, click an object, look at the tooltip
Result: no next departures available
Expected: next departures are listed as designed

Info: geops reported me that they have no issues on their systems providing the data.

@pfanguin @alcapat : could you please take care of that with high prio? Thanks

**Comment by alcapat** [comment]
Hi. Import script was desable next week.
Now the job run again and data are available since 14h00.

**Comment by alcapat** [comment]
@mariokeusen : can you check and close this issue if it's ok for you.
Best regards,
Patrick

**Comment by mariokeusen** [comment]
Works. Thanks for the fix.
