### ISSUE TITLE
search inconsistency

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2043]
Since the last deploy, the layer search behaves inconsistent:
[Testurl ](https://api3.geo.admin.ch/rest/services/ech/SearchServer?searchText=WGS84&lang=de&type=layers)

Open this url with cache disabled some times, the result is not always the same.

**Comment by loicgasser** [comment]
I think only one sphinx server has been updated.
Deploying the bod snapshot from last deploy to prod should fix this issue.

**Comment by loicgasser** [comment]
commands are in remember to deploy google doc

**Comment by ltclm** [comment]
thanks loic, it is solved.
i have manually updated bod related sphinx indexes on both prod instances.
```bash
$ python /etc/sphinxsearch/pg2sphinx_trigger.py -d bod_prod -c update
```

**Comment by ltclm** [comment]
no idea db deploy logs are not available anymore. The last bod deploy to prod was 2016-04-13 13:16:01

**Comment by gjn** [comment]
Smells like a weakness in our db deploy/sphinx update process.

We should try to track it down. @loicgasser as you did the deploy, could you try to find out what happened?

**Comment by loicgasser** [comment]
Not easy without any logs. Let's be extra vigilant during next deploy.
It would be nice to have 2 instances on int as well if this were to be tested.

**Comment by ltclm** [comment]
Obviously there have been two overlapping deploys on the instance 10.220.5.210:
```bash
ltclm@ip-10-220-5-210 (vpc/sphinxsearch - production):~$ grep deploy /var/log/messages.1 | grep restoring
# start first deploy
Apr 13 13:15:09 ip-10-220-5-210.eu-west-1.compute.internal (deploy.main) restoring archive from '/var/cache/deploy/sphinx_1460546108/sphinx'
# start second deploy
Apr 13 14:21:22 ip-10-220-5-210.eu-west-1.compute.internal (deploy.main) restoring archive from '/var/cache/deploy/sphinx_1460550081/sphinx'
Apr 13 14:21:24 ip-10-220-5-210.eu-west-1.compute.internal (deploy.main) done restoring # stop second deploy
Apr 13 14:22:04 ip-10-220-5-210.eu-west-1.compute.internal (deploy.main) done restoring # stop first deploy
``` 
On the second instance 10.220.6.242 there has been only one deploy:
```bash
ltclm@ip-10-220-6-242 (vpc/sphinxsearch - production):~$ grep deploy /var/log/messages.1 | grep restoring
Apr 13 14:21:25 ip-10-220-6-242.eu-west-1.compute.internal (deploy.main) restoring archive from '/var/cache/deploy/sphinx_1460550081/sphinx'
Apr 13 14:21:27 ip-10-220-6-242.eu-west-1.compute.internal (deploy.main) done restoring
```

Strange that there have been two deploys on the first instance. @loicgasser did you notice something special during db deploy? It is hard to analyze, especially without /var/log/messages from the db instance.

**Comment by gjn** [comment]
Looks like aborted deploy.

Thanks alot for the analysis.
