### ISSUE TITLE
remove queryable, selectbyrectangle  from bod model

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2048]
Please remove the attributes
`selectbyrectangle` and `queryable` from the LayersConfig  model. The attribute `tooltip` can be used in the related code.
These attributes are redundant copy of tooltip and can be removed from the view afterwards.

**Comment by gjn** [comment]
Both attributes can be removed already. Front-end code does not depend on them anymore.  We are using the `tooltip` attribute to determine if we should issue an identify request on click. We use the `queryableAttributes` array to determine if the layer is queryable in the query tool.

**Comment by loicgasser** [comment]
+1, we remove it from the code and then from the views.

**Comment by loicgasser** [comment]
Fixed in code via https://github.com/geoadmin/mf-chsdi3/commit/61bee52a5f7d7b5733882f5e8aca79cef92f445d#diff-2e90e144f9058f27411cceaa0039ca9d

Views still need to be adapted

**Comment by ltclm** [comment]
Hi Loic

View layers_js has been modified and deployed to dev.
https://github.com/geoadmin/db/commit/2989b1cec0a01b763dc3f9163a52953bf9ea2e6a
https://github.com/geoadmin/db/commit/57ca2fac291084e6ef76c84661b770b0f169c396

**Comment by loicgasser** [comment]
Done
