### ISSUE TITLE
Use price service for shop layers

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2079]
Currently, the price information for the shop layers is coming from the db.

We should use the webshot price service to get this information. Interface description was send out by email.

Note: special care need to be taken regarding availability of the service on different staging areas. Get in touch with puzzle regarding this.

**Comment by oterral** [comment]
Duplicate of #2032

**Comment by gjn** [comment]
It's done for all published layers. So I close this.
