### ISSUE TITLE
Wrong TileMatrixSet for LV95

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#2093]
WMTS [GetCapabilities](http://wmts20.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml) for LV95 is miss aligned.
![missalinged_lv95](https://cloud.githubusercontent.com/assets/1236739/15546329/c8ad58b4-229f-11e6-9e6a-1b146bf32471.png)

**Comment by procrastinatio** [comment]
Two independant people did report this issues, but this was **before** the change in PR https://github.com/geoadmin/mf-chsdi3/pull/2047 were deployed in production.

I now cannot reproduce this problem, using the very same QGis project as gestern.

**Comment by procrastinatio** [comment]
Cannot reproduce (QGis and ArcMap), Kt SH has now no issue (QGis).

**Comment by procrastinatio** [comment]
[Using OL3 with GetCapabailities](http://codepen.io/procrastinatio/details/vKBjNz/)

**Comment by gjn** [comment]
Very strange. Do you have an approach?

**Comment by gjn** [comment]
Does x/y switch in 2056 compared to 21781?

**Comment by procrastinatio** [comment]
No, but there are no _x_ and _y_ in LV95, only _eastings_ and _northings_.

**Comment by gjn** [comment]
see my comment https://github.com/geoadmin/mf-geoadmin3/commit/43a820abc5f5704d3754a68a65c7efcc481ed0a6

**Comment by procrastinatio** [comment]
So is this fixed ?

**Comment by procrastinatio** [comment]
According to https://groups.google.com/d/msg/geoadmin-api/6ienm9GO-3M/S8r7FgjpBAAJ looks like it solved.

**Comment by loicgasser** [comment]
yes solved
