### ISSUE TITLE
pkxx.noscale tooltips 

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2094]
Not sure if this is a feature or a bug,
But why are the pk25, pk50, pk100, pk200 configured as higlightable = false ?

https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.pixelkarte-farbe-pk25.noscale&X=187200.00&Y=636800.00&zoom=3

**Comment by gjn** [comment]
Feature.
Shop functionality (rectangle selection) does conflict with feature highlight. Also, shop will have other selections (commune, canton, map) that mist be handled differently (will be coming later).
Am 25.05.2016 6:20 nachm. schrieb Clausen Marcel <notifications@github.com>:Not sure if this is a feature or a bug,
But why are the pk25, pk50, pk100, pk200 configured as higlightable = false ?

https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.pixelkarte-farbe-pk25.noscale&X=187200.00&Y=636800.00&zoom=3

**Comment by ltclm** [comment]
🙈
