### ISSUE TITLE
[ch.swisstopo.gas25-papierkarte.metadata]: map sheet at wrong location

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2097]
UC: load the layer ch.swisstopo.gas25-papierkarte.metadata, go to 751'000.0, 176'700.0, look at the map
Result: the sheet Ambri/Piotta is obviously at the wrong location in the canton of Grisons
Expected: sheet is located in Ticino

Workaround: could you please investigate where this error comes from?

![ga25-paper_issue1_sheetatwronglocation](https://cloud.githubusercontent.com/assets/4577749/15572994/651c9184-2344-11e6-8263-af7a6ab550b7.PNG)

**Comment by rfrancel** [comment]
The geometry was wrong it is fixed now.

**Comment by mariokeusen** [comment]
Yes, thanx!
