### ISSUE TITLE
[ch.swisstopo.geologie-geologischer_atlas]: tooltip of papermap appearing in no data area

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2098]
UC: open app, load layer ch.swisstopo.geologie-geologischer_atlas, click into the empty area @ 750'800.0, 177'150.0, see what happens
Result: the tooltip of the papermap 	Ambrì-Piotta (CN 1252) appears, which is from a different layer (ch.swisstopo.gas25-papierkarte.metadata)
Expected: "no information" popup at this coordinates

Workaround: will probably be solved with #2097 

![ga25_pixel_issue_mixwithpaper](https://cloud.githubusercontent.com/assets/4577749/15573091/d92d5d10-2344-11e6-953f-9a57e5131243.PNG)

**Comment by rfrancel** [comment]
The geometry was wrong it is fixed now.

**Comment by mariokeusen** [comment]
Yes, thanx!
