### ISSUE TITLE
[tooltip] issue on raster layer with tooltip in "no information" areas

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2099]
UC1: open app e.g. with the layer ch.swisstopo.pixelkarte-farbe-pk25.noscale, zoom out to a whole Switzerland view, click outside the map data perimeter (white areas)
UC2: click again in an area where there is some map material
UC3: load an additional (vector) layer and try to get the tooltip
Result1: a popup appears with a message: "No further information" (so far it's correct)
Result2: the same popup appears instead of the extpected tooltip
Result3: the same popup appears instead of the extpected tooltip

![popup_issue_where_no_tooltip_available](https://cloud.githubusercontent.com/assets/4577749/15573230/b86acab2-2345-11e6-907b-e502e2aaadf7.PNG)

**Comment by gjn** [comment]
@mariokeusen Should be fixed now.

**Comment by mariokeusen** [comment]
Jep. Looks good now.
