### ISSUE TITLE
[SHOP] - Avoid order of "no data"

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2101]
UC: load e.g. ch.swisstopo.pixelkarte-farbe, select by rectangle, draw a rectangle on a the white part (no data)
Result: one can buy "no data"
Expected: "Order" is disabled

**Comment by loicgasser** [comment]
This is a problem on the shop side. There obviously not calling the cut service when we're requesting a price.
Take for instance an extent outside a product will generate the following getPrice request:
https://beta.shop.swisstopo.ch/shop-server/resources/products/price?layer=ch.swisstopo.pixelkarte-farbe-pk25.noscale&geometry=871250,112250,885250,136750

So the extent is:
871250,112250,885250,136750

The associated request that should be generated on our backends is:

http://api3.geo.admin.ch/rest/services/ech/GeometryServer/cut?geometryType=esriGeometryEnvelope&geometry=871250,112250,885250,136750&layers=all:ch.swisstopo.pixelkarte-farbe-pk25.noscale

Clearly it returns an area of 0, so the price should be 0 as well.

**Comment by loicgasser** [comment]
ping @pauloamado

**Comment by gjn** [comment]
@pauloamado Could you discuss this with puzzle.
