### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-chsdi3#2110]
I'm doing some checks on which license the project we use rely on. During this process, I saw that there is no license file for the python api.

I saw [here](https://github.com/geoadmin/mf-chsdi3/blob/61c2e62766bd2bbbf0051621e5172013a8d8bfd4/chsdi/static/doc/source/api/faq/index.rst#what-is-the-license-of-the-geoadmin-api) that the javascript api is BSD licensed but we are not using this.

I also saw that the [sphinxapi](https://github.com/geoadmin/mf-chsdi3/blob/61c2e62766bd2bbbf0051621e5172013a8d8bfd4/chsdi/lib/sphinxapi/sphinxapi.py) is published under the GPL (no precision of version thought) which probably means that the python API (chsdi) is GPL too.

Can you please clarify this?

**Comment by gjn** [comment]
BSD 3-clause License added.

**Comment by Jenselme** [comment]
Thanks!
