### ISSUE TITLE
Swissbuildings3D 2.0 uses wms of dev in production

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2113]
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissbuildings3d-2.metadata&layers_opacity=0.75

This can also be seen in failed jenkins tests:
https://jenkins.prod.bgdi.ch/job/chsdi3/525/console

pint @AFoletti @rfrancel

**Comment by rfrancel** [comment]
ok, the layer is configurerd to use wms-prod in the bod but I'll investigate why it's not

**Comment by rfrancel** [comment]
no I was wrong, it was not the case everywhere.. I redeployed the bod to dev.

**Comment by gjn** [comment]
ok. will be ok on prod on next deploy. thanks.
