### ISSUE TITLE
[map background layers WMTS/WMS swisstopo] add LK10 layers on zoomlevels 25 to 27

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2114]
UC: add grey and color map bg-layer from WMTS and WMS swisstopo
Result: map material till zoomlevel 23 with LK25 is available
Expected: also LK10 is available from zoomlevel 25 to 27

**Comment by gjn** [comment]
28 as well? Currently, in map.geo.admin.ch, we only have 27. 28 is client zoomed only.

**Comment by mariokeusen** [comment]
Wasn't aware of that: IMHO we should do it exactly the same way as in map.geo.admin.ch, then we get rid of differences like that and it's easier to have the whole managed.

**Comment by procrastinatio** [comment]
We have:
* ch.swisstopo.pixelkarte-farbe-pk(25|50|100|200|500|1000).noscale
* ch.swisstopo.pixelkarte-farbe   and
* ch.swisstopo.landeskarte-farbe-10

WMTS does not know `aggregate`layers. WE have to manually copy the missing level from `ch.swisstopo.landeskarte-farbe-10`to `ch.swisstopo.pixelkarte-farbe`if you want to see them in WMTS.

**Comment by loicgasser** [comment]
+1 we should copy `ch.swisstopo.landeskarte-farbe-10` at the last zoom levels using the `current` timestamp. Then we can change `ch.swisstopo.pixelkarte-farbe` configuration as we don't need a layer group anymore.

**Comment by ltclm** [comment]
the aim was to replace tlm-karte with lk10. thats exactly what has been done. the aggregate base layers exist already for years. there was always that difference between map.geo.admin and pure wmts.

**Comment by gjn** [comment]
That's true. There was an assumption by the datenherr that the integration of LK 10'000 would automatically extent the pure wmts `ch.swisstopo.pixelkarte-farbe` and `ch.swisstopo.pixelkarte-grau` layers with the LK10 on levels 25 to 27. As it was just assumed and not clearly specified as part of the data integration, it was not done.

Now we have to do it.

**Comment by ltclm** [comment]
lk10 tiles are png (default for overlay layers), ch.swisstopo.pixelkarte-farbe|grau tiles are jpeg. so we have to calculate all the tiles again...

**Comment by gjn** [comment]
Any way to estimate the cost of it? (man hours, cloud costs?)

**Comment by procrastinatio** [comment]
@ltclm And you have to change the name from **lk10** to **pk10**...

**Comment by ltclm** [comment]
@mariokeusen 
this has been done

**Comment by mariokeusen** [comment]
Yes, thanks!
