### ISSUE TITLE
Always cast/use the correct mapping type

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2122]
ping @daguer @alcapat @ltclm  @gjn @rfrancel @pfanguin @AFoletti 

We are using a lot of views, ok...

But we really need to be aware of the fact that the type mapping must be correct at all time which is not the case. (escpecially with `autload=False`)

For instance take:
`tlm.swissboundaries_gemeinden` type is defined as an integer in the model but looking at the view we actually have a double precision number for the id.

This is bad because we'll generate floating point numbers for the ids when we actually have integers.
This needs to be addressed ASAP. I will start the corrections but I want everyone to take part.

This is a source of potential errors (try the highlight on the features of ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill for instance)

At least for the ids.

And don't change the views only, please change the underlying table.

Have a look at Jenkins in the flowing PR:
https://github.com/geoadmin/mf-chsdi3/pull/2121

Also if it's a double -> map it to a double.
Avoid using Numeric or at least use the argument `asdecimal=False` so that we don't have to deal with the decimal in python.

**Comment by rfrancel** [comment]
jenkins test
