### ISSUE TITLE
Content-Type missmatch in data.geo.admin.ch

### ISSUE THREAD

**Issue by rfrancel** [geoadmin/mf-chsdi3#2136]
Some data have the wrong Content-Type.

```
$ curl -I --referer "https://toto.geo.admin.ch" "https://data.geo.admin.ch/ch.bafu.hydroweb-warnkarte_regional/ch.bafu.hydroweb-warnkarte_regional_fr.json"

Content-Type: application/octet-stream
```

**Comment by loicgasser** [comment]
Yes they handle that themseleves. It doesn t break the app but it should be fixed.
Ping @davidoesh if you can tell them

**Comment by procrastinatio** [comment]
The uploader is responsible for setting the right `Content-Type`. Some client are doing the magick, while other not.
