### ISSUE TITLE
zeitreihen lk25/lk50 fullres view fix backlink

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2142]
Since there are now fullres scans of lk25 and lk50 available, 
we have to fix the zoomlevel of the backlinks.

lk25 backlink should zoom to zoomlevel 8
lk50 backlink should zoom to zoomlevel 7

https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/templates/historicalmaps/viewer.mako#L29

**Comment by gjn** [comment]
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=20041231,,,&X=252774.72&Y=665638.48&zoom=3&time=2004

Click in the middle.

**Comment by ltclm** [comment]
there is no scanned fullres data for this image in the middle.
https://historicalmaps.geo.admin.ch/tiles/bv000826462/quickview.jpg

http://www.alexandria.ch/primo_library/libweb/action/dlSearch.do?institution=BIG&vid=ALEX&scope=default_scope&query=lsr07,contains,bv000826462

You have to ask rolf.
