### ISSUE TITLE
Big geometries in Identify results

### ISSUE THREAD

**Issue by ltbam** [geoadmin/mf-chsdi3#2166]
An identify feature request on "ch.vbs.logistikraeume-armeelogistikcenter" and "ch.vbs.territorialregionen" returns huge geometries. It would be nice to simplify them.

**Comment by loicgasser** [comment]
@ltclm I think we could add a simplified geometry column for that and use the `__returnedGeometry__` option. We need to use the topology preserving simplification (e.g. same as what you did in vector forge).

**Comment by ltclm** [comment]
yes that would make sense, but we should use postgis/topology with caution. 
it is adding a new schema and some new views/tables related to the table. this will break our table deploy. but we have to this case-by-case.
for now i would propose to try a simplify the geometries with fme or postgis and add a new geometry column to the tables. i will ask @Ariadnigaki to work on that.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/2179

**Comment by loicgasser** [comment]
case-by-case: needs to be formalized.
