### ISSUE TITLE
Unesco table in bak.public primary key starts at 0

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2169]
bgdi_id is the primary key and starts at 0

**Comment by loicgasser** [comment]
Also there is a topology schema which doesn't have the usal access rights. (same for the tables)

**Comment by ltclm** [comment]
> Also there is a topology schema which doesn't have the usal access rights. (same for the tables)

Sorry Loic but i have no idea what you mean with this. Can you give me the raw error message?

**Comment by loicgasser** [comment]
I am talking about.
GRANT SELECT ON TABLE bla TO ...

**Comment by loicgasser** [comment]
It is not used so maybe remove it all together. I am not sure what was the goal of it. There is no generalization to my knowledge

**Comment by ltclm** [comment]
I have fixed the bgdi_id issue, furthermore there was no primary key and geometry index on that table. I have created them and deployed the table to dev/int/prod.

**Comment by ltclm** [comment]
the topology schema is in all our databases, it comes with the topology support of postgis.
What's the issue, i still dont understand.

**Comment by loicgasser** [comment]
Ok. then we should make sure it comes with the correct access rights in case we use it.
Wouldn't you agree? We should be coherent that's all. Not a problem generating an error at the moment but it might if we start using them as our app won't even have read acces on it.

**Comment by ltclm** [comment]
the apps dont need to access to this schema, the schema will be used in the background. You can add a topology geometry column to an existing table, which already has the right access constraints. This should be done with the [postgis topology management and constructor functions](http://postgis.net/docs/manual-dev/Topology.html#Topology_Constructors).
It should be noted that adding a topology to an existing table will
* add a new schema
* create entries in topology.* tables
* make **table deploy difficult or even impossible**

So we should decide that case-by-case. By the way do you still need the table ``stopo_master.tlm.prodas_spatialseltype_gemeinde_forge``?

**Comment by loicgasser** [comment]
Well when creating topogeometries the new column will have dependencies on the topology schema and table (faces, edges, nodes and relation) which will make it impossible for another user to access the column.

Yes I still need `stopo_master.tlm.prodas_spatialseltype_gemeinde_forge`.

**Comment by gjn** [comment]
Not sure I understand fully.

But is there a way to assure tables have primary key? Or doesn't that make sense?

When reviewing a data integration, shouldn't we also review the corresponding postgis tables, definitions and views? Is this done? If not, how could it be integrated to a review process?

**Comment by gjn** [comment]
A big +1 from my side.

Are FME scripts reviewed? Should/Could be done as well.

**Comment by loicgasser** [comment]
FME scripts are a bit everywhere.
I don't think it's really reviewable but it would be good to have a central repo for all those scripts.

**Comment by AFoletti** [comment]
+1 for the review at the data (table/file) level.

FME scripts are a bit subjective (many ways for the same result, and we do not have clear ways to define what's better) and I, like @loicgasser, think that they will be difficult to review.
Much more interesting would be a sort of knowledge exchange about how to build a particular workbench or how to perform some bizarre task in them.
We also have some standards, but those should be documented in the wiki.

+1 for the centralized **and well organized** FME repo. In an ideal world, each workbench should come with a bit of documentation (in workbench itself)

**Comment by loicgasser** [comment]
+1 for the review at the data (table/file) level.

I can take care of it with @ltclm . Organize it, Ideally automatize it.

> +1 for the centralized and well organized FME repo. In an ideal world, each workbench should come with a bit of documentation (in workbench itself)

As you are migrating from Redmine to Jira and you have a good knowledge/overview on how we handle these scripts, I think you are in the best position to organize that.
Could you make a proposal for that when you have time?

**Comment by AFoletti** [comment]
I'll discuss it with A. Kunz too and organize a global IGEB repo

**Comment by loicgasser** [comment]
Great! keep us in the loop.
