### ISSUE TITLE
Wanderwege - duplication

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2172]
In our models, we have 2 models and 2 technical layers pointing to the exact same table with the same attributes.

[ch.swisstopo.swisstlm3d-wanderwege](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/stopo.py#L1560) and [ch.swisstopo-karto.wanderwege](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/stopo.py#L1621)

In bod, we don't have ch.swisstopo-karto.wanderwege, so I think this could be remove.

@daguer since you are the original author. Can you verify this and remove it if it's not needed anymore?

**Comment by gjn** [comment]
@ltclm KIK is using ch.swisstopo.swisstlm3d-wanderwege for all of their requests.

**Comment by gjn** [comment]
ping @daguer

**Comment by procrastinatio** [comment]
I think the original _ch.swisstopo-karto.wanderwege_ used to have footpath outside Switzerland, which was much loved.
