### ISSUE TITLE
Ensure all geometriesin DB do not exceed max size

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2178]
With
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/features.py#L698
and
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/features.py#L710

it is assumed that our geometries don't have more than 1'000'000 parts.

This is not the case, with the current approach we simply skip all geometries that exceeds this arbitrary limit.
The client on the other hand excepts a respone with a geometry property which he is likey not to receive.
This will to generate errors on the client side.

We should
1. Detect all `big geometries`
2. Simplify them accordingly.
3. Ensure that geometries we will publish in the future don't exceed this limit

@ltclm @alcapat @simonevonheute @daguer @gjn

**Comment by ltclm** [comment]
hello, 
i dont agree in changing / reducing the precision of the original geometry (tilegeneration, wms, etc.), this is data manipulation. But we can introduce a simplifed geometry column for chsdi highlights.
p.e.
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/lubis.py#L17

**Comment by loicgasser** [comment]
Sure that s what I had in mind sorry

**Comment by gjn** [comment]
The above was introduced to protect our infrastructure. Huge geometries lead to timeouts (actually, it was the creation of the JSON string) - which consumed the apache connections, which in turn brought down all services.

We need simplified geometries for the web.

**Comment by loicgasser** [comment]
I could easily detect all the tables where we have such geometries with a script. Then we need somebody to actually do the work.

**Comment by procrastinatio** [comment]
Splitting or converting from `MULTI` to `SINGLE` large geometries is not an options ?

**Comment by loicgasser** [comment]
This is now part of the integration process.
