### ISSUE TITLE
ch.vbs.armeelogistikcenter LV95 variable Symbol size

### ISSUE THREAD

**Issue by ltbam** [geoadmin/mf-chsdi3#2186]
When we consume the layer in LV95 (https://wmts20.geo.admin.ch/EPSG/2056/1.0.0/)

Sometimes the Symbols appear with different sizes.

![image](https://cloud.githubusercontent.com/assets/11943224/17060979/98d6da88-502c-11e6-98f3-5e6ae3202402.png)

We did not see this problem on any other layer

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/service-mapproxy/pull/40

**Comment by procrastinatio** [comment]
Please check https://web-wmts-test.dev.bgdi.ch/?host_tpl=https%3A%2F%2Fwmts%7B20-24%7D.geo.admin.ch&raw_tpl=0&timestamp=20150330&use_src=0&format=png&layer=ch.vbs.armeelogistikcenter&epsg=2056&lang=fr

**Comment by procrastinatio** [comment]
@ltbam Coucou ?

**Comment by procrastinatio** [comment]
No news, good news
