### ISSUE TITLE
Remove unused columns from public.ms_class

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2196]
Remove columns

frm_classitem
frm_classitem

And from the wiki:
https://wiki.lt.admin.ch:8443/confluence/display/BGDI/12+-+Howto+integrate+Layer+in+BOD

**Comment by rebert** [comment]
https://github.com/geoadmin/tool-wms/pull/152/files

**Comment by rebert** [comment]
done
