### ISSUE TITLE
Update ol3 for js api

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2220]
We should update ol3 for js api and publish it as a preview. The current version is over 1 year old.

@oterral Could you give it a try?
https://github.com/geoadmin/ol3

**Comment by oterral** [comment]
Already on it  but compilation problems.

**Comment by oterral** [comment]
Ah sorry I thought you mean in map.ge.admin.ch.

**Comment by oterral** [comment]
@gjn  have you think putting this lib (loader.js and na dfile  in s3 ? 
like map.geo.admin.ch we could have multiple static versions in it and avoid update problems of the users.

**Comment by gjn** [comment]
Yes, that would/could make sense.

Didn't think about it in detail, but probably loader would be kept in api, and the specific version in s3 forever. Then user could call loader.js with version parameter, e.g. api3.geo.admin.ch/loader.js?version=something and it would be forever there. (Could defer/redirect to statified loader.js in s3 together with the specific version)

But main problem we probably have is timestamps of our layers. We need to keep them as long as we keep older API's. Or would we always get latest layersConfig, even with old ol3 version? So, data will be up-to-date, but lib could be versioned?

Not sure about that. Little brainstorm?

**Comment by oterral** [comment]
Since now we use `current` timestamp  I don't think timestamps are an issue for future versions of the api.
 
Getting the new LayersConfig with old ol3 versions could be problematic if we change properties in LayersConfig.

**Comment by procrastinatio** [comment]
I mean 99% of users are only interested in pixelkarte or swissimage, so there is no issue to keep older layers config. But generally speaking, it make absolutely no sense to keep a previous version of tiles, because tooltips (and other service) are not versioned.

**Comment by gjn** [comment]
We have `current` timestamp only for a small selection of layers (even if most used layers). Most other layers have specific timestamps.

But we can also say that when you use old version of api, you also get old data. That could motivate users to upgrade.

I think both ways are possible, as with both solution we risk to run into incompatibilities...and breaking of the API app.

**Comment by gjn** [comment]
Migration documentation
Create a preview
Create examples with preview
