### ISSUE TITLE
Stationboard polling never stops

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2235]
For instance:
1. Open map.geo.admin.ch
2. Select Haltestellen
3. Click on a station or selection by rectangle
4. Observe requests in you browser

Resut:
Polling never stops.

Expected result:
Polling stops when popup is closed.

**Comment by loicgasser** [comment]
@gjn The tooltip here doesn't behave as a service.
We should do the same we did for windenergie, it would also solve the timeout issue.
See for instance:

https://api3.geo.admin.ch/1474375204/rest/services/ech/MapServer/ch.bav.haltestellen-oev/8504860/htmlPopup?coord=585750,161875.00000000003&imageDisplay=1920,647,96&lang=de&mapExtent=412000,99625,892000,261375

**Comment by gjn** [comment]
We try to solve it in iframe similar to windgeschwindigkeiten.
