### ISSUE TITLE
eMAPIS: symbology, legends, feature info 

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2253]
Here a list of fixes needed for eMAPIS:
- [x] which is the status of this? https://github.com/geoadmin/wms-mapfile_include/pull/58
- [x] Legend label for "Beizugsgebiet" in layer ch.blw.emapis-beizugsgebiet is OK in WMS (int) but not in map.geo.admin.ch. The static png should be regenerated
- [x] Legend label for "Beizugsgebiet" (NAME "5103") in layer ch.blw.emapis-zusammenfassung is wrong. Should be as in previous point
- [x] Symbology for "Spurweg Beton" in layer ch.blw.emapis-zusammenfassung is wrong (EXPRESSION=5214). Take right symbology from layer ch.blw.emapis-wegebau. Then regenerate legend for map.geo.admin.ch
- [x] Adapt symbology for all layers ch.blw.emapis-\* . Concept implemented for layer ch.blw.emapis-hochbau in  wms-bgdi.dev.bgdi.ch/ltgal. Consider that: (i) ch.blw.emapis-zusammenfassung is the sum of all other layers; (ii) this level of symbology should not appear in the GetLegendGraphic output.

**Comment by AFoletti** [comment]
- First point should be OK. PR is merged
- About last point: that's not the only case where a technical layer is used but it should not show up in the GetLegendGraphic request, I think it would be good to find a way to handle that in the same way we use for the GetCap omission (DB-based). @loicgasser what do you think?

**Comment by loicgasser** [comment]
@AFoletti What about using the scale parameter in GetLegendGraphic

See for instance:

Without scale:
http://wms-bgdi.int.bgdi.ch/?request=GetLegendGraphic&layer=ch.blw.emapis-beizugsgebiet&style=default&service=WMS&version=1.3.0&format=image%2Fpng&sld_version=1.1.0&lang=fr


With scale 100:

http://wms-bgdi.int.bgdi.ch/?request=GetLegendGraphic&layer=ch.blw.emapis-beizugsgebiet&style=default&service=WMS&version=1.3.0&format=image%2Fpng&sld_version=1.1.0&lang=fr&scale=100

With scale 50'000:
http://wms-bgdi.int.bgdi.ch/?request=GetLegendGraphic&layer=ch.blw.emapis-beizugsgebiet&style=default&service=WMS&version=1.3.0&format=image%2Fpng&sld_version=1.1.0&lang=fr&scale=50000

DB based is a hack to me.

**Comment by gjn** [comment]
+1

**Comment by p1d1d1** [comment]
- First point: is a deploy needed? e.g. i don't see the new attribute here: https://mf-geoadmin3.int.bgdi.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7CStrukturverbesserungen%7C%7Chttp:%2F%2Fwms-bgdi.int.bgdi.ch%7C%7Cch.blw.emapis-zusammenfassung%7C%7C1.3.0

- Last point: the legend of this layer should show up, but now it has duplicated entries because of the 2 levels of symbology:
![image](https://cloud.githubusercontent.com/assets/1533649/19150687/70b654ca-8bc8-11e6-823d-cc26f201c065.png)
Only one level should appear in the legend, the one defined in the data model.

**Comment by AFoletti** [comment]
First point: I have to look at the code. Will do tomorrow :)

About GetLegend:
I don't understand why entering this info in the DB should be a hack. We already have this info for the !GetCap and let the translation script do the work for us. This could work the same way.
@loicgasser your solution "works" but you have to consider that a user will NOT add a scale parameter to his GetLegendGraphic. Disabling the request for the non official symbolization is in my opinion a better approach

**Comment by loicgasser** [comment]
Users don't have to add it manually. It's activate when you click the info button automatically.
We could even imagine updating it when zooming in our out.

**Comment by loicgasser** [comment]
At least you'd have a legend for what you see.

**Comment by loicgasser** [comment]
First point yes we probably have to update the mapinclude snippets in wms-bgdi. will check it later.

**Comment by loicgasser** [comment]
For the first point attributes haven't been included in `ows_include_items` so they won't show up.

**Comment by loicgasser** [comment]
It's not clear not me if you want translated title or a new attribute

**Comment by loicgasser** [comment]
Ok I have a test link for point 1;
https://mf-geoadmin3.int.bgdi.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=WMS%7C%7CStrukturverbesserungen%7C%7Chttp:%2F%2Fwms-bgdi.dev.bgdi.ch%2Fltgal%2F%7C%7Cch.blw.emapis-zusammenfassung%7C%7C1.3.0&X=240279.45&Y=590394.79&zoom=10

**Comment by p1d1d1** [comment]
Marcel already did something:
https://mf-geoadmin3.int.bgdi.ch/?topic=emapis&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.dev.bgdi.ch%2Fltclm%2Fde%2F%3Fequery%3D(typ_code%3D41)%7C%7Cch.blw.emapis-hochbau,ch.blw.emapis-hochbau&lang=de&bgLayer=voidLayer&X=237412.37&Y=575609.28&zoom=4&catalogNodes=1916

**Comment by loicgasser** [comment]
ok yes we simply need to add it to `ows_include_items` then

**Comment by AFoletti** [comment]
Again about the GetLegend issue:
of course you can make the geoadmin GetLegendGraphic scale-aware. You can even go further and make it fully context-aware by implementing the BBOX if you really want to have a legend of only what you are seeing.
But that was not the issue.
Issue was: **please do not show the unofficial symbolization but only the one defined in the data model.**
If that's really what we want, then tinkering with geoadmin is not a real solution since there are other WMS clients out there and it should be solved at the WMS level.

**Comment by p1d1d1** [comment]
@loicgasser status here?
Please consider that we'd need at least the first 4 points done within this month. Beginning November (1st to 3rd) we have a new tests round on "int".

**Comment by loicgasser** [comment]
1 is fixed, See PR above just need merge \ translate. 2 and 3 are pretty straightforward. The rest on the way.

**Comment by loicgasser** [comment]
> Symbology for "Spurweg Beton" in layer ch.blw.emapis-zusammenfassung is wrong (EXPRESSION=5214). Take right symbology from layer ch.blw.emapis-wegebau. Then regenerate legend for map.geo.admin.ch

This layer is not integrated in CHSDI. -> nothing to do in CHSDI.
I guess you had planned to use it only throught WMS Import. This is a layer that shows all the EMapis layers at the same time right? that's what I understand when I read the doc.

**Comment by p1d1d1** [comment]
The layer is so far only used via WMS Import.
I'm waiting an answer from Christine to the proposal I did via email (using wms_url instead of WMS Import): if accepted either the layers goes in ch-sdi either it could be decommissioned.

**Comment by loicgasser** [comment]
Ok I wait for your feedback then.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/wms-mapfile_include/pull/63
[LAST POINT TESTLINK](https://mf-chsdi3.int.bgdi.ch/shorten/6efe0f196f)

**Comment by loicgasser** [comment]
@p1d1d1 status about symbology here? Better, worth? I could make those even a little bigger. The thing is I don't know how many items we'll have in the end. If we won't have that many new items I would propose to go even bigger.

**Comment by p1d1d1** [comment]
@loicgasser we're not expecting so many objects in the short term. So i'll go a little bigger too.
Then will check again when we'll have more objects.

**Comment by p1d1d1** [comment]
@all any news on this?

**Comment by loicgasser** [comment]
Yes we have a testlink in dev:
https://mf-chsdi3.dev.bgdi.ch/shorten/6fbc8df41c

VS

https://mf-chsdi3.int.bgdi.ch/shorten/6fbc8e9ee2

**Comment by p1d1d1** [comment]
Ok thanks. But what about points 4 and five? Have these been fixed?

**Comment by loicgasser** [comment]
5 yes see the above links.

> Symbology for "Spurweg Beton" in layer ch.blw.emapis-zusammenfassung is wrong (EXPRESSION=5214). Take right symbology from layer ch.blw.emapis-wegebau. Then regenerate legend for map.geo.admin.ch

For 4 I don't know this is a layer containing all the emapis layers apparently.

See:
https://github.com/geoadmin/mf-chsdi3/compare/gal_legends?expand=1

And a legend doesn't exist for this one yet. At least in chsdi.

**Comment by p1d1d1** [comment]
Many thanks.
5) the symbology is ok on map, but legend in infobox should be updated

4) this layer contains all emapis layers and is just a WMS layer that will be used via WMS-Import: https://mf-chsdi3.int.bgdi.ch/shorten/6fc0e76f00. The legend in the infobox is a GetLEgendGraphic request, but entries are duplicated.

**Comment by oterral** [comment]
Done in prod
