### ISSUE TITLE
[lk10] mwa not visible on zoomlevels 0 to 9

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2254]
Mentioned on wednesday already...

UC: open https://s.geo.admin.ch/6ec962ee7f, zoom out to zoomlevel 9, 8 
Result: the mwa object (bridge) is visible on zoomlevels 10 to 13, but not on 9 or smaller
Expected: mwa objects are present on the whole tile pyramid

My suspicion: we only have the new tiles on zoomlevels 10 to 13. Problem concerns the Lk10 "noscale" layers, not the bg-layers...

**Comment by gjn** [comment]
The now working levels are the ones we fixed for pixelkarte-farbe and grau. But obviously, we need all levels to get all MWA's on all levels.

@loicgasser Please discuss with @ltclm once he's back.

**Comment by loicgasser** [comment]
I know what this is. Can be fixed.

**Comment by loicgasser** [comment]
This is fixed

**Comment by gjn** [comment]
Masterful. Thanks alot.

**Comment by mariokeusen** [comment]
Great! Thanks!
