### ISSUE TITLE
Geometry too big

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2259]
http://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=548945.5,147956,549402,148103.5&geometryType=esriGeometryEnvelope&imageDisplay=500,600,96&mapExtent=548945.5,147956,549402,148103.5&tolerance=1&layers=all:ch.bafu.gefahren-baugrundklassen

Results in error:

 509 Bandwidth Limit Exceeded
Feature ID 19691: is too large

@ltclm @rebert How can we avoid such huge geometries in our db?

**Comment by ltclm** [comment]
we have to introduce to the data integration:
* use the geometry checker function
* if huge geometries exist, create a chsdi geometry column the_geom_highlight

**Comment by loicgasser** [comment]
Fixed
