### ISSUE TITLE
Shop layers names refactoring

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2273]
Here is a summary:

**Layers that have already been replaced.**

| Old name | New name |
| --- | --- |
| ch.swisstopo.lk200-papierkarte.metadata | ch.swisstopo.landeskarte200_papier.metadata |
| ch.swisstopo.lk500-papierkarte.metadata | ch.swisstopo.landeskarte500_papier.metadata |
| ch.swisstopo.gk300-papierkarte.metadata | ch.swisstopo.generalkarte300_papier.metadata |
| ch.swisstopo.wk25-papierkarte-zusammensetzung.metadata | ch.swisstopo.wanderkarte25-zus_papier.metadata |
| ch.swisstopo.sfk300-papierkarte.metadata | ch.swisstopo.segelflugkarte_papier.metadata |
| ch.swisstopo.wkt33-papierkarte.metadata | ch.swisstopo.wanderkarte33_papier.metadata |
| ch.swisstopo.bk200-papierkarte.metadata | ch.swisstopo.burgenkarte200_papier.metadata |
| ch.swisstopo.stk200-papierkarte.metadata | ch.swisstopo.strassenkarte200_papier.metadata |
| ch.swisstopo.gkg500-papierkarte.metadata | ch.swisstopo.geologie-geologische_karte_papier.metadata |
| ch.swisstopo.gkt500-papierkarte.metadata | ch.swisstopo.geologie-tektonische_karte_papier.metadata |
| ch.swisstopo.gkwvor500-papierkarte.metadata | ch.swisstopo.geologie-grundwasservorkommen_papier.metadata |
| ch.swisstopo.gkba500-papierkarte.metadata | ch.swisstopo.geologie-geodaesie-bouguer_anomalien_papier.metadata |
| ch.swisstopo.gklgm500-papierkarte.metadata | ch.swisstopo.geologie-eiszeit-lgm-raster_papier.metadata |
| ch.swisstopo.gas25-papierkarte.metadata | ch.swisstopo.geologie-geologischer_atlas_papier.metadata |
| ch.swisstopo.gsk-papierkarte.metadata | ch.swisstopo.geologie-spezialkarten_schweiz_papier.metadata |
| ch.swisstopo.ggk200-papierkarte.metadata | ch.swisstopo.geologie-generalkarte-ggk200_papier.metadata |
| ch.swisstopo.swissbuildings3d-2.metadata | ch.swisstopo.swissbuildings3d_2.metadata |

**Shop layers we still need to decomission**

| Old name | New name |
| --- | --- |
| ch.swisstopo.lk100-papierkarte-zusammensetzung.metadata | ch.swisstopo.landeskarte100_papier.metadata |
| ch.swisstopo.lk100-papierkarte.metadata | ch.swisstopo.landeskarte100_papier.metadata |
| ch.swisstopo.lk1000-papierkarte.metadata | ch.swisstopo.landeskarte1000_papier.metadata  |
| ch.swisstopo.lk25-papierkarte-zusammensetzung.metadata | ch.swisstopo.landeskarte25_papier.metadata |
| ch.swisstopo.lk25-papierkarte.metadata | ch.swisstopo.landeskarte25_papier.metadata |
| ch.swisstopo.lk50-papierkarte-zusammensetzung.metadata | ch.swisstopo.landeskarte50_papier.metadata |
| ch.swisstopo.lk50-papierkarte.metadata | ch.swisstopo.landeskarte50_papier.metadata |
| ch.swisstopo.icao-papierkarte.metadata | ch.swisstopo.luftfahrtkarten-icao_papier.metadata |
| ch.swisstopo.area-papierkarte.metadata | ch.swisstopo.luftfahrtkarten-icao_papier.metadata |
| ch.swisstopo.wk50-papierkarte-zusammensetzung.metadata | ch.swisstopo.wanderkarte50_papier.metadata |
| ch.swisstopo.wk50-papierkarte.metadata | ch.swisstopo.wanderkarte50_papier.metadata |
| ch.swisstopo.geologie-gravimetrischer_atlas.metadata |  ch.swisstopo.geologie-gravimetrischer_atlas_papier.metadata |
| ch.swisstopo.gkwvul500-papierkarte.metadata |ch.swisstopo.geologie-grundwasservulnerabilitaet_papier.metadata | 
**Layer that should be entirely decomissioned**

Anything else?

@mariokeusen @daguer 
Could you complete the list please? So that we have an easy global overview.

Earlier reference:
https://github.com/geoadmin/mf-chsdi3/pull/2267

**Comment by loicgasser** [comment]
1. Wait for protocol
2. @pfanguin will make the changes
3. @mariokeusen will adapt the catalogs
4. @pauloamado will create the migration script
5. Remember to deploy doc

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/2313

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/2314

**Comment by pfanguin** [comment]
It's done
