### ISSUE TITLE
Layer decomissioning ch.astra.ivs-reg_loc

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2274]
TODO after today's deploy

ch.kantone.ivs-reg_loc
ch.kantone.ivs-reg_loc.sub

This layer needs to be completly removed from the BOD.

@alcapat please put here what you have already done.

TO CHECKLIST:

Geocat:
- [ ] Remove entry 

DB:
BOD (maybe more...)
- [x] catalog
- [x] dataset
- [x] geocat_data
- [x] abnahme
- [x] layers_js
- [x] translations

Geometries
- [ ] associated tables if not used by another layer (for chsdi you can use https://github.com/geoadmin/mf-chsdi3/blob/master/scripts/models_scan.py)

WMS:
- [x] Remove from mapfile_includes
- [x] Remove from WMS services

CHSDI:
- [x] models
- [x] translations
- [x] makos
- [x] legends

Sphinx:
- [x] Remove indice if searchable

**Comment by loicgasser** [comment]
Now, you just need to remove the snippet from https://github.com/geoadmin/wms-mapfile_include and we can close this isssue.
Thank you, it was very smooth. I don't know if there is something to do with geocat, but I would ask André/Mario.

**Comment by gjn** [comment]
@alcapat Can you verify the state (use the check mentioned by @loicgasser )
