### ISSUE TITLE
Add tests for sitemap service 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2276]
In squash we test these links:

http://api3.geo.admin.ch/sitemap?content=index
http://api3.geo.admin.ch/sitemap?content=base
http://api3.geo.admin.ch/sitemap?content=topics
http://api3.geo.admin.ch/sitemap?content=layers
http://api3.geo.admin.ch/sitemap?content=addresses_33

Tell me if it's still necessary or if we should add tests in chsdi.

**Comment by loicgasser** [comment]
Oh I think we're good.
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/tests/integration/test_sitemap.py

**Comment by oterral** [comment]
thx I remove these links
