### ISSUE TITLE
Add tests for i18n service

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2277]
In squash we test these links:

http://api3.geo.admin.ch/testi18n?lang=de
http://api3.geo.admin.ch/testi18n?lang=en
http://api3.geo.admin.ch/testi18n?lang=toto

Tell me if they are  necessary or if we should add test in chsdi3 ?

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/commit/518f07f2afe68d29d63215d4a7e6c5fcf3ed75e2#diff-1097e732e05bd11c2868df8e09ba0fcf

We have one. more could be good

**Comment by gjn** [comment]
Something for @Sgachet ? Adding more tests.

**Comment by procrastinatio** [comment]
No, we test that services are translated. We will not a test such relics from the past as `checker_dev` and `testi18n`. Will be removed.
