### ISSUE TITLE
2 BAZL layer decommission

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#2289]
the BAZL layers
ch.bazl.heliports-gebirgslandeplaetze and ch.bazl.points-of-interest have to be decommissioned.
I already set their staging to "test"

Still ToDo:

Catalog:
- [x] Remove from googledocs

WMS:
- [x] Remove from wms-bod
- [x] Delete snippets in mapfile_include

CHSDI:
- [x] models
- [x] translations
- [x] makos
- [x] legends

BOD:
- [x] dataset
- [x] geocat_data
- [x] abnahme
- [x] layers_js
- [x] translations

Geometries:
- [x] remove geometry tables

Geocat:
- [x] Remove entry

**Comment by loicgasser** [comment]
`I already set their staging to "test"`

We may have to remove them from the catalog and sphinx (if searchable= for tomorrow's deploy. Otherwise I don't see any potential conflict with this change.

**Comment by AFoletti** [comment]
they are not searchable, so no problem on sphinx.
They are already removed from the catalog spreadsheet, but I have to check the import

**Comment by AFoletti** [comment]
Redmine tickets: 4027 + 4028

**Comment by AFoletti** [comment]
chsdi PR https://github.com/geoadmin/mf-chsdi3/pull/2325

**Comment by AFoletti** [comment]
Everything is done and I asked for the removal of the geocat entries

**Comment by AFoletti** [comment]
closing this since PR is merged
