### ISSUE TITLE
Cadastral web map soleure link not working

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2296]
http://www.sogis1.so.ch/sogis/internet/pmapper/somap.php?karte=ortsplan&extent=42000.0,30000.0,350000.0,900000.0

@rebert can you adapt the link in
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/templates/htmlpopup/cadastralwebmap.mako

?

you probably know what to do. :d

**Comment by gjn** [comment]
:=)
