### ISSUE TITLE
layer Ids needs to be remapped to new Ids

### ISSUE THREAD

**Issue by daguer** [geoadmin/mf-chsdi3#2323]
This layer Ids needs to be remapped to new Ids
- ch.swisstopo.landeskarte1000_papier.metadata
  (old ch.swisstopo.lk1000-papierkarte.metadata)
- ch.swisstopo.geologie-gravimetrischer_atlas_papier.metadata
  (old ch.swisstopo.geologie-gravimetrischer_atlas.metadata)
- ch.swisstopo.geologie-grundwasservulnerabilitaet_papier.metadata
  (old ch.swisstopo.gkwvul500-papierkarte.metadata)

TO CHECKLIST:

Geocat:
- [ ] Update entry 

DB:
BOD (maybe more...)
- [ ] catalog
- [ ] dataset
- [ ] geocat_data
- [ ] abnahme
- [ ] layers_js
- [ ] translations

Geometries
- [ ] associated tables if not used by another layer (for chsdi you can use https://github.com/geoadmin/mf-chsdi3/blob/master/scripts/models_scan.py)

WMS:
- [ ] Remove from mapfile_includes
- [ ] Remove from WMS services

CHSDI:
- [ ] models
- [ ] translations
- [ ] makos
- [ ] legends

Sphinx:
- [x] Remove indice if searchable

Post deploy tasks:
- [ ] Remove from BOD
- delete from re3.layers_js where pk_layer in ('ch.swisstopo.lk1000-papierkarte.metadata','ch.swisstopo.geologie-gravimetrischer_atlas.metadata','ch.swisstopo.gkwvul500-papierkarte.metadata');

- delete from dataset where id_dataset in ('ch.swisstopo.lk1000-papierkarte.metadata','ch.swisstopo.geologie-gravimetrischer_atlas.metadata','ch.swisstopo.gkwvul500-papierkarte.metadata');

- delete from translations where msg_id like '%ch.swisstopo.lk1000-papierkarte.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.geologie-gravimetrischer_atlas.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.gkwvul500-papierkarte.metadata%';

- [ ] Remove from chsdi
- [ ] Remove from sphinx

**Comment by pfanguin** [comment]
@daguer : missing metedata for ch.swisstopo.geologie-gravimetrischer_atlas_papier.metadata and tooltip for all layers must be activated.

**Comment by daguer** [comment]
This layer isn't in the geocat diff list.
That's why the metadata is empty...

**Comment by pfanguin** [comment]
because it is the same uuid as the old layer. You must remove the uuid from the old layer.

**Comment by loicgasser** [comment]
thanks @pfanguin
