### ISSUE TITLE
Regrouping layers shop

### ISSUE THREAD

**Issue by pfanguin** [geoadmin/mf-chsdi3#2324]
sphinx : [#309](https://github.com/geoadmin/service-sphinxsearch/pull/309)
chsdi : [#2314](https://github.com/geoadmin/mf-chsdi3/pull/2314)

This layer Ids needs to be remapped to new Ids
- ch.swisstopo.wanderkarte50_papier.metadata
  (old ch.swisstopo.wk50-papierkarte.metadata)
- ch.swisstopo.landeskarte50_papier.metadata
  (old ch.swisstopo.lk50-papierkarte.metadata)
- ch.swisstopo.landeskarte25_papier.metadata
  (old ch.swisstopo.lk25-papierkarte.metadata)
- ch.swisstopo.luftfahrtkarten-icao_papier.metadata
  (old ch.swisstopo.icao-papierkarte.metadata)
- ch.swisstopo.landeskarte100_papier.metadata
  (old ch.swisstopo.lk100-papierkarte.metadata)

TO CHECKLIST:

Geocat:
- [x] Update entry 

DB:
BOD (maybe more...)
- [x] catalog
- [x] dataset
- [x] geocat_data
- [x] abnahme
- [x] layers_js
- [x] translations

Geometries
- [x] associated tables if not used by another layer (for chsdi you can use https://github.com/geoadmin/mf-chsdi3/blob/master/scripts/models_scan.py)

WMS:
- [x] Remove from mapfile_includes
- [x] Remove from WMS services

CHSDI:
- [x] models
- [x] translations
- [x] makos
- [x] legends

Sphinx:
- [x] Remove indice if searchable

Post deploy tasks:
- [x] Remove from BOD
- delete from re3.layers_js where pk_layer in ('ch.swisstopo.area-papierkarte.metadata','ch.swisstopo.icao-papierkarte.metadata','ch.swisstopo.wk50-papierkarte-zusammensetzung.metadata','ch.swisstopo.wk50-papierkarte.metadata','ch.swisstopo.lk50-papierkarte-zusammensetzung.metadata','ch.swisstopo.lk50-papierkarte.metadata','ch.swisstopo.lk25-papierkarte-zusammensetzung.metadata','ch.swisstopo.lk25-papierkarte.metadata','ch.swisstopo.lk100-papierkarte-zusammensetzung.metadata','ch.swisstopo.lk100-papierkarte.metadata');

- delete from dataset where id_dataset in ('ch.swisstopo.area-papierkarte.metadata','ch.swisstopo.icao-papierkarte.metadata','ch.swisstopo.wk50-papierkarte-zusammensetzung.metadata','ch.swisstopo.wk50-papierkarte.metadata','ch.swisstopo.lk50-papierkarte-zusammensetzung.metadata','ch.swisstopo.lk50-papierkarte.metadata','ch.swisstopo.lk25-papierkarte-zusammensetzung.metadata','ch.swisstopo.lk25-papierkarte.metadata','ch.swisstopo.lk100-papierkarte-zusammensetzung.metadata','ch.swisstopo.lk100-papierkarte.metadata');

- delete from translations where msg_id like '%ch.swisstopo.area-papierkarte.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.icao-papierkarte.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.wk50-papierkarte-zusammensetzung.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.wk50-papierkarte.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.lk50-papierkarte-zusammensetzung.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.lk50-papierkarte.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.lk25-papierkarte-zusammensetzung.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.lk25-papierkarte.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.lk100-papierkarte-zusammensetzung.metadata%';
- delete from translations where msg_id like '%ch.swisstopo.lk100-papierkarte.metadata%';

- [x] Remove from chsdi
- [x] Remove from sphinx

**Comment by pfanguin** [comment]
Decommission chsdi : https://github.com/geoadmin/mf-chsdi3/pull/2342
Decommission sphinx : https://github.com/geoadmin/service-sphinxsearch/pull/311

**Comment by loicgasser** [comment]
yep, try:

```sql
DELETE FROM re3.layers_js WHERE pk_layer = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM dataset WHERE id_dataset = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM dataset WHERE parent_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM translations WHERE msg_id like 'ch.swisstopo.area-papierkarte.metadata%';
DELETE FROM dataset_cache WHERE layer_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM dataset_tags WHERE layer_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM dataset_timestamps WHERE layer_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM ms_class WHERE fk_layer_name = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM ms_item WHERE fk_layer_name = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM tileset WHERE fk_dataset_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM wms_timestamps WHERE fk_dataset_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM wms_timestamps_fme WHERE fk_dataset_id = 'ch.swisstopo.area-papierkarte.metadata';
DELETE FROM xt_dataset_wms WHERE fk_id_dataset = 'ch.swisstopo.area-papierkarte.metadata';
```

**Comment by pfanguin** [comment]
Done
