### ISSUE TITLE
Document multi-version javascript API

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2333]
We should mention it in the docs at least. Only then we'll release it officially.

**Comment by loicgasser** [comment]
http://mf-chsdi3.dev.bgdi.ch/api/quickstart.html#include-the-geoadmin-javascript-api

It is in the quick start page.
We could mention it in the examples as well.

**Comment by oterral** [comment]
We need to address polyfill issue.  See feedbacks in google group.
