### ISSUE TITLE
Geologischer Atlas: bugs

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2337]
There is a bug in the following layers:

ch.swisstopo.geologie-geologischer_atlas_papier.metadata
ch.swisstopo.geologie-geologischer_atlas

Use Case:
- Load ch.swisstopo.geologie-geologischer_atlas_papier.metadata
- Search for 139 --> GA-DRG-139
- Click on the map sheet --> 139 and 149 are loaded in the tooltip (there are 2 geometries there)
- Text on map sheet is wrong (149 Buchs (LK 1135). Should be 139 Balsthal (LK 1107)

ch.swisstopo.geologie-geologischer_atlas is also affected

**Comment by ltclm** [comment]
the toposhop table has two products:
'GA25-DRG-139', 'GA25-DRG-149' which are referenced with the same geometry in our stopo geometry table stopo_master.public.grid_ga25. Well in this table we have two entries with identical geometry.
We have to find out why both products have the same geometry in our geometry table. 
@pauloamado do you have any idea why these products have the same geometry?

**Comment by davidoesch** [comment]
@p1d1d1  tick should be in mf-geoadmin

**Comment by ltclm** [comment]
thanks to @pauloamado we could identify the issue.
we had duplicate entries in the geometry source table in stopo.
we have found the same issue with the sheets 148 and 138.
I have removed the duplicated entries and added a unique constraint.
the table has been deployed to prod.

**Comment by p1d1d1** [comment]
@ltclm many thanks for the quick fix.
@davidoesch sorry, sometimes I have doubts on where to open tickets.
