### ISSUE TITLE
Tests ogcproxy: download kml via ogcproxy url

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2338]
http://mf-chsdi3.dev.bgdi.ch/examples/bln-style.kmz

Should be stored oustide CHSDI.

chsdi.tests.integration.test_ogcproxy.TestOGCproxyView
Line 27

Upload and then replace URL

**Comment by procrastinatio** [comment]
You mean outside 'bgdi.ch' and 'geo.admin.ch' ?

**Comment by loicgasser** [comment]
I mean outside chsdi.

**Comment by procrastinatio** [comment]
You may try https://procrastinatio.github.io/kml/bln-style.kml or bln-style.kmz
But as they have correct CORS headers, it won't go through the proxy

We may transfer it to geoadmin.github.io
