### ISSUE TITLE
Bug Search Service?

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2339]
Use Case:

1) Search for CH327843320651 --> 2 results in the list with exactly the same text but 2 different locations on the map

![image](https://cloud.githubusercontent.com/assets/1533649/20429709/9d9c44f6-ad90-11e6-9ca7-34b1716bcda9.png)

**Comment by loicgasser** [comment]
Data issue.
https://api3.geo.admin.ch/1611161143/rest/services/ech/SearchServer?searchText=CH327843320651&lang=fr&type=locations

geometry seems different while parcel id is identical.

@ltclm we don't enforce parcel number in DB?

**Comment by ltclm** [comment]
the last number comes from the attribute egris_egrid
around 7% of the data (300'000 out of 4M) have duplicate egris_egrid numbers, i dont know if this is a data issue.

**Comment by p1d1d1** [comment]
this last number is supposed to be unique over the entire Schweiz. Unique ID of a parcel.

**Comment by ltclm** [comment]
I have no idea about the content of egris_egrid. we are publishing 1:1 what we get from geoshop. this delivery has egris_egrid as optional field. please ask ibele about that.

**Comment by oterral** [comment]
fixed in new GWR import
