### ISSUE TITLE
Decommission ch.swisstopo.geologie-geolkarten500.metadata

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#2362]
A stopo layer to decommission. Replaced by ch.swisstopo.geologie-geologische_karte_papier.metadata
BOD staging already set to "test"

Still ToDo:

Catalog:
- [x] Remove from MuM

WMS:
- [x] Remove from wms-bod
- [x] Delete snippets in mapfile_include

CHSDI:
- [x] models
- [x] translations
- [x] makos
- [x] legends

BOD:
- [x] dataset
- [x] geocat_data
- [x] abnahme
- [x] layers_js
- [x] translations

**Comment by AFoletti** [comment]
fully removed once the chsdi PR is merged.
I removed it from the catalog spreadsheet too.

Pending: removal from MuM (needs development MuM-side)

**Comment by ltclm** [comment]
is there any data we can remove, or is it only a renaming?

**Comment by AFoletti** [comment]
old layer used  public.gk500 for both visualization and tooltip info.
The new layer uses geol.view_gridstand_gkg500 so it's probably safe to remove the data too.
But I don't know stopo layers well enough to be sure...

**Comment by ltclm** [comment]
we will have to do some clean-up work in the stopo database:
https://github.com/geoadmin/mf-chsdi3/issues/2365

**Comment by AFoletti** [comment]
MuM ability to remove layers will come in a future release.
I'll leave this ticket open so that I do not forget it. Redmine ticket will be closed
https://redmine.prod.bgdi.ch/issues/4309

**Comment by mariokeusen** [comment]
This GDS has been removed from BMD4MuM now:
https://jira.swisstopo.ch/browse/BGDIDM_SB-288

**Comment by AFoletti** [comment]
thanks!
