### ISSUE TITLE
[Tooltip]: dynamic links to feature attachments non available

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2381]
UC: open app, load the opendata AV layer (ch.swisstopo-vd.amtliche-vermessung), go to Solothurn, click on map
Result: tooltip appears with attributes as designed, but the links to download the SHAPE and ITF Files per municipality are not available anymore. 
Expected: we have functional download links to the SHAPE and ITF Files available on S3

Remark: the files are still available in the folder structure in S3, seems to be a tooltip issue.

**Comment by mariokeusen** [comment]
The links to the PDF's for e.g. ch.astra.ivs-nat, ch.astra.ivs-reg_loc do not work anymore as well. Seems to be a general issue with feature attachments.
Other examples like ch.bafu.typisierung-fliessgewaesser (Feature attachments on dav0) or ch.bak.bundesinventar-schuetzenswerte-ortsbilder (feature attachments on S3) still work normally.

**Comment by ltclm** [comment]
see https://github.com/geoadmin/mf-geoadmin3/issues/3651
will be solved with the deploy next week https://github.com/geoadmin/mf-chsdi3/pull/2380

**Comment by mariokeusen** [comment]
Duplicate with #3651
