### ISSUE TITLE
kataster_belasteter_standorte_oev empty table?

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2389]
Something is wrong with this table / layer. 

Tests keep failing. 

@ltclm @pfanguin any idea who s working on that ?

**Comment by ltclm** [comment]
you have to ask @AFoletti

**Comment by AFoletti** [comment]
uvek.bav.kataster_belasteter_standorte_oev (and its oereb sister) are not empty. Which tests are failing?

**Comment by loicgasser** [comment]
Have a look at Jenkins.. http://jenkins.dev.bgdi.ch/job/PR_chsdi3/91/console
Search and layers (no feature was found in the table)

**Comment by AFoletti** [comment]
Something is fishy. Table is OK, and the layer works as defined
[maplink](https://s.geo.admin.ch/70226341e5)
[identify](https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=680466.3375970491,249199.93719575045&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1920,718,96&lang=en&layers=all:ch.bav.kataster-belasteter-standorte-oev&mapExtent=677946.3375970491,248254.93719575048,682746.3375970491,250049.93719575048&returnGeometry=true&tolerance=10)

**Comment by ltclm** [comment]
the layer is configured as ``searchable=True`` in the bod but there is no sphinx index.
i propose to set the layer to ``searchable=False``

**Comment by loicgasser** [comment]
+1

**Comment by ltclm** [comment]
done and bod deployed to dev
new build: http://jenkins.dev.bgdi.ch/job/PR_chsdi3/94/

**Comment by loicgasser** [comment]
This is fixed thanks @ltclm
