### ISSUE TITLE
No rm legend

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2390]
http://api3.geo.admin.ch/static/images/legends/ch.bakom.downlink1_rm.png

For all these layers there is bad legend for rm:

Update	Download ≥ 1 Mbit/s (ch.bakom.downlink1)
Update	Download ≥ 2 Mbit/s (ch.bakom.downlink2)
Update	Download ≥ 10 Mbit/s (ch.bakom.downlink10)
Update	Download ≥ 20 Mbit/s (ch.bakom.downlink20)
Update	Download ≥ 50 Mbit/s (ch.bakom.downlink50)
Update	Download ≥ 100 Mbit/s (ch.bakom.downlink100)
Update	Availability HDTV fixed netw. (ch.bakom.verfuegbarkeit-hdtv)
Update	Availability TV fixed network (ch.bakom.verfuegbarkeit-tv)
Update	Upload ≥ 1 Mbit/s (ch.bakom.uplink1)
Update	Upload ≥ 2 Mbit/s (ch.bakom.uplink2)
Update	Upload ≥ 10 Mbit/s (ch.bakom.uplink10)
Update	Upload ≥ 20 Mbit/s (ch.bakom.uplink20)
Update	Upload ≥ 50 Mbit/s (ch.bakom.uplink50)
Update	Upload ≥ 100 Mbit/s (ch.bakom.uplink100)
Update	Optical fibre (ch.bakom.anschlussart-glasfaser)
Update	Coaxial cable (ch.bakom.anschlussart-koaxialkabel)
Update	Copper wire (ch.bakom.anschlussart-kupferdraht)

@rebert  can you fix it please ?

**Comment by rebert** [comment]
@oterral I will try

**Comment by AFoletti** [comment]
[Do. Or do not. There is no try](https://www.youtube.com/watch?v=iSpx92Xoukk)
I take care of that. Those are my layers after all...

**Comment by rebert** [comment]
@AFoletti : I just updated the table bod_master: public.ms_class for this issue - have fun :-)
