### ISSUE TITLE
Error in catalog for layer ch.bafu.karst-ausdehnung_grundwasservorkommens

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2394]
This layer is not connected in the catalog ping @AFoletti @mariokeusen @daguer

**Comment by mariokeusen** [comment]
Indeed it is part of the topics ech, inspire, bafu, gewiss and geol. But the tech. layername is ch.bafu.karst-ausdehnung_grundwasservorkommen instead of ch.bafu.karst-ausdehnung_grundwasservorkommens.

I have successfully imported it with the other 4 "karst" layers into the catalogs. And checked the layer positions on dev and int.

**Comment by oterral** [comment]
The extra 's' is just an error in the code of the test.

**Comment by loicgasser** [comment]
https://mf-geoadmin3.int.bgdi.ch/mobile.html?topic=bafu&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,

**Comment by loicgasser** [comment]
Catalogue bafu is still broken on int, my guess is that a category is still on int or Dev and layer on prod

**Comment by mariokeusen** [comment]
Just checked the topic config table for bafu once again: there is no category set on dev or int where there are layers on prod. Therefore this cannot be an issue on the topic config side....

**Comment by oterral** [comment]
@mariokeusen  there is problem with all the karst layers because you haven't validate the config after changing the category staging to prod. Can you do it now please ?

**Comment by mariokeusen** [comment]
Ok, I did that once again. Should have been on prod since Friday last week btw.

**Comment by oterral** [comment]
thx

**Comment by ltclm** [comment]
imho it should be possible and no normal to have prod layers in dev or int topics, loic?

**Comment by oterral** [comment]
arf sorry for the noise @mariokeusen.  The validation didn't work as expected. An SQL error were triggered but not display.

**Comment by mariokeusen** [comment]
no prob. So, issue is or can be solved? If so, please close this issue. Thanks

**Comment by loicgasser** [comment]
It is fixed. closing
