### ISSUE TITLE
Simplify geoms for ch.bafu.gefahren-baugrundklassen

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2397]
Some geometries are way too big

https://map.geo.admin.ch/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&X=152486.49&Y=568129.80&zoom=3&layers=ch.bafu.gefahren-baugrundklassen&layers_opacity=0.75

We need to improve that as half of the identify requests fail.

**Comment by ltclm** [comment]
please add an additional geometry column ``the_geom_simplified``
as described here: https://wiki.lt.admin.ch:8443/confluence/pages/viewpage.action?pageId=313460400
with fme generalizer and adapt import script.

**Comment by ltclm** [comment]
```bash
$ psql -d bafu_master -c "SELECT _bgdi_analyze_geometry('gefahren.baugrundklassen','the_geom')"
NOTICE:  geometry column will be analyzed : (bafu_master.gefahren.baugrundklassen.the_geom)
NOTICE:  count: 50284
NOTICE:  max. number of vertices: 126183
NOTICE:  max. number of geometries in Multigeometry: 657
NOTICE:  Geometry types: ST_MultiPolygon
NOTICE:  Geometry Coordinate Dimenstion: 2
NOTICE:  Geometry max. z value: 0
NOTICE:  Geometry Indices: baugrundklassen_the_geom_geom
NOTICE:
NOTICE:  Optimization advice
NOTICE:      * add a geometry column with simplified geometry, some features have more than 10000 vertices
 _bgdi_analyze_geometry
------------------------
 f
```

**Comment by loicgasser** [comment]
It's in the pipeline, it was an update and it was already the case, we missed it but didn't have time to do it today as it would take too long to simplify. @rebert is ready ;)

**Comment by davidoesch** [comment]
@mariokeusen Can we convince tha data owner to remove the tooltip ? (only 5% of users click on geometries...)

**Comment by ltclm** [comment]
the simplified geometry is ready and will soon be deployed.
so we could keep the identify, but yes no-tooltip is better ;-)

**Comment by loicgasser** [comment]
Or no highlight, it s possible as well

**Comment by cedricmoullet** [comment]
We see a lot of 509 like http://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=646062.375,222355.4375&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1920,1123,96&lang=de&layers=all:ch.bafu.gefahren-baugrundklassen&mapExtent=645105.375,221788.4375,647025.375,222911.4375&returnGeometry=true&tolerance=10 so it seems users are clicking on features

**Comment by rebert** [comment]
PR #2406 -> dependancy on database bafu_master

**Comment by loicgasser** [comment]
Will be fixed for next deploy @rebert don't forget The 
REMBER TO DEPLOY document.
