### ISSUE TITLE
500 errors on search server

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#2402]
https://api3.geo.admin.ch/1612141141/rest/services/aviation/SearchServer?se…0,353750&features=ch.bazl.luftfahrthindernis&timeEnabled=false&timeStamps=

deivers a 500 in https://map.geo.admin.ch/index.html?topic=aviation&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bazl.luftfahrthindernis&catalogNodes=1379

![image](https://cloud.githubusercontent.com/assets/319676/21192496/11467690-c229-11e6-9201-5eb7b1f613df.png)

**Comment by loicgasser** [comment]
Will look into it when I get home.

**Comment by loicgasser** [comment]
issue is solved

**Comment by loicgasser** [comment]
I still see 500 errors on the search service. I can't reproduce right now. @ltclm @danduk82 We may have an issue with an instance.

**Comment by loicgasser** [comment]
the feature search mainly

**Comment by loicgasser** [comment]
Error 500 are gone but I leave it open as I can't tell why it was the case in the first place.

**Comment by loicgasser** [comment]
This is solved. AWS DNS exploded yesterday. This could explain that. http://status.aws.amazon.com/rss/ec2-eu-west-1.rss
