### ISSUE TITLE
500 error on ch.bfe.windenergie-geschwindigkeit_h125

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#2408]
http://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometryType=esriGeometryPoint&geometry=516750%2C307656.25&geometryFormat=geojson&imageDisplay=671%2C600%2C96&mapExtent=492250%2C35000%2C827750%2C335000&tolerance=10&layers=all%3Ach.bfe.windenergie-geschwindigkeit_h125&lang=de&callback=_callbacks_._4iwtlnetm

**Comment by loicgasser** [comment]
The tooltip works when clicking in the grid, this point is way outside the grid. We should be returning an empty list instead though. I will fix that.

https://s.geo.admin.ch/7041a91f57

**Comment by loicgasser** [comment]
Fixed via https://github.com/geoadmin/mf-chsdi3/pull/2410
