### ISSUE TITLE
[copyright-tool] new BLW URL's due to a CMS change

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2411]
UC: open app, load any layer from ch.blw, click the link to BLW on the copyright tool
Result: link does not work anymore due to a CMS change @blw 
Expected: user is lead to new blw website

Workaround: replace current URL's with the new ones [1]

[1]
BLW: https://www.blw.admin.ch/blw/de/home.html
OFAG: https://www.blw.admin.ch/blw/fr/home.html
UFAG: https://www.blw.admin.ch/blw/it/home.html
FOAG: https://www.blw.admin.ch/blw/en/home.html
BLW RM (de): https://www.blw.admin.ch/blw/de/home.html 

Thanks in advance!

**Comment by ltclm** [comment]
will be fixed with next deploy

**Comment by loicgasser** [comment]
Fixed via https://github.com/geoadmin/mf-chsdi3/pull/2412
