### ISSUE TITLE
Wrong LV95 ( 4x 2x)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2416]
"Ihre Suche über eine Postadresse funktioniert, aber die Suche über ein Grundstück weist als Resultat die doppelte LV95 Koordinate aus (4 Millionen, 2 Millionen statt 2 Mio, 1 Mio)."

Customer feedback ID : 2017010911441229

according to lttsb , @oterral is working on it

**Comment by ltclm** [comment]
the csv geoshop export is now lv95. we have to change our import script. will deploy the data tomprrow.

**Comment by davidoesch** [comment]
Thanks for the update

**Comment by ltclm** [comment]
import script are fixed and data is deployed to prod.

**Comment by davidoesch** [comment]
Thanks, Helpdesk is informed to update customer with the news
