### ISSUE TITLE
using min-max-resolution instead of scale in models

### ISSUE THREAD

**Issue by rebert** [geoadmin/mf-chsdi3#2420]
@loicgasser When reading the code (the comments) I have the feeling, that (min/max)_scale_ is prefered over for (min/max)_resolution_. But why not using _resolution_ over for _scale_ ? Of course this should then be adviced in the data integration process.

#2419

**Comment by loicgasser** [comment]
yes we want to get rid of resolution. A resolution is less accurate than a scale as it doesn't take into account the DPI. The scale is also what one uses in WMS. So I would stick to the scale.
In the zeitreihen service (releases) we use resolutions but this is a legacy functionality of RE2. There some magic in this code I would not change right now.

**Comment by loicgasser** [comment]
we use scale everywhere except for zeitreihen
