### ISSUE TITLE
Get Varnish List dynamically

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2438]
https://github.com/geoadmin/bgdi-scripts/blob/master/aws_scripts/aws_shell_functions.sh#L372

@danduk82 let me know when ready

**Comment by procrastinatio** [comment]
hem, ` User: arn:aws:iam::44********:user/****** is not authorized to perform: cloudformation:ListStacks`

**Comment by oterral** [comment]
@danduk82 could we use instance roles for that?  Not very nice to have our varnish addressses hard coded in a public project.

**Comment by loicgasser** [comment]
@danduk82 another issue with instance roles we wanted to fix for a while.
But...

**Comment by procrastinatio** [comment]
We have now role instance now.
