### ISSUE TITLE
GWR Data issue

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2440]
Seems like we have some strange language mixing and object duplication on the GWR layers.

1. [We have duplicates for certain adresses](https://s.geo.admin.ch/7129bce9c1). 1 symbol, but 2 texts. Why?

2. The html popup of the duplicates has, depending on point selected, either french or german street name - independant of UI language chosen: [french streename with german language selection](https://api3.geo.admin.ch/1702011125/rest/services/ech/MapServer/ch.bfs.gebaeude_wohnungs_register/1758621_0/htmlPopup?coord=586153.616641108,219244.38384552122&imageDisplay=1920,678,96&lang=de&mapExtent=585972.616641108,219063.88384552122,586932.616641108,219402.88384552122), [same street, different object results in german streename, even with french language selection](https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bfs.gebaeude_wohnungs_register/1758614_0/htmlPopup?coord=586436.4,219237.8999999999&imageDisplay=1920,678,96&lang=fr&mapExtent=585337.4,218792.8999999999,587257.4,219470.8999999999)

3. [In the search](https://map.geo.admin.ch/?swisssearch=Aegerten 40 Bienne), we have both languages for the same object.

We need to define what we want. I propose the following:

1. Search: we keep it as it is.
2. Tooltip: show in language that is in UI.
@davidoesch Do you agree?

@ltclm @loicgasser What is needed to achieve this?

**Comment by ltclm** [comment]
we will publish the fixed data this sunday, elias has modified the import script (bfs->gdwh).
multilingual entries have been merged into one single entry: z.B. STRNAME = Neuenburgstrasse/Route de Neuchâtel. 
we dont have the information about the language in the data.

**Comment by gjn** [comment]
This means we'll have both languages in the tooltip and the search result for one entry?

Not sure this is really user friendly. @davidoesch ?

**Comment by davidoesch** [comment]
This is not userfriendly 

BUT
- how many names are affected ( in %) ?
- other solution:
--How does google solve it - they don't. 
--I would create a new col in the DB SPHINX which has "alternate" titles for an Entry, lang dependent, and via the lang parameter  we choose the lang defined col. per default we have have what BFS delivers as primary source
as it already seemsed to be defined
FR
![image](https://cloud.githubusercontent.com/assets/4577727/22548080/1e1d5a94-e945-11e6-8872-8f1a33e4fb7a.png)

DE

![image](https://cloud.githubusercontent.com/assets/4577727/22548091/2ed0f85a-e945-11e6-9c2c-3fb8fa95195c.png)

**Comment by loicgasser** [comment]
suboptimal but what else can we do?
As long as we don't have the language info, this is the best one can do.

And no it is not defined.
Those are 2 separate entries that relate to the same entry. (see first link of @gjn)

as I explained in another thread, identify only returns one result because it is using a bgdi_id which is unique (which is correct but we should have both translations and not a random one like now).
We couldn't create a unique primary (on egid and eid) because of these duplicates.

**Comment by loicgasser** [comment]
Another solution could be to merge points for identify and WMS, leave it as is for the search.

**Comment by ltclm** [comment]
8'769 out of '2078'097 address entries are multilingual duplicates ( **4.2 %** ).
The only different information is the streetname. i propose to merge these entries and put the streetnames together. 
And we dont have the information about the language of the street names.

**Comment by ltclm** [comment]
as soon as these entries are merged, we can define egid_edid as primary key.

**Comment by davidoesch** [comment]
only 4.2% ? the  a clear go for @ltclm approach

**Comment by davidoesch** [comment]
ne data dleivery awaited IMHO we can close this. we will handle this via Dataintgeration
https://jira.swisstopo.ch/browse/BGDIDI_KB-776

**Comment by ltclm** [comment]
As discussed with the data owner, we have published the merged streetname solution:

http://api3.geo.admin.ch/rest/services/api/MapServer/find?layer=ch.bfs.gebaeude_wohnungs_register&searchText=1758614&searchField=egid&returnGeometry=false

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bfs.gebaeude_wohnungs_register&X=219278.78&Y=586419.65&zoom=12
