### ISSUE TITLE
loader errors

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#2448]
In the last 7 days, more than 6000 loader requests ended in an error: https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/loader.js%20errors
Could you analyze the causes ?

**Comment by oterral** [comment]
bad url requested :  http://api.geo.admin.ch/loader.js

instead of  http://api3.geo.admin.ch/loader.js

Any change in redirection setup @danduk82 @procrastinatio ?

**Comment by procrastinatio** [comment]
Sur les 7 derniers jours, sur 6322 requêtes sur loader.js retournant des codes non 200, la majorité (env. 5'000) concerne **api.geo.admin.ch** comme mentionné par @oterral . Pour le reste, 593 proviennent de pays bloqués par **GeoIP** (RU, BY, TR, HR, etc.), 685 proviennent d'un bot californien (Fremont) **PhantomJS** qui scanne systématiquement tous les sites de la confédération. Si l'on enlève encore tous les 403 hautement suspects, il reste **4** erreurs 500 "légitime", sur 280'000 requêtes. 

@oterral There was never a redirection on the loader.js as both API are incompatible. The web site however http://api.geo.admin.ch is redirect to http://api3.geo.admin.ch

**Comment by loicgasser** [comment]
@procrastinatio is right, http://api.geo.admin.ch is redirected to http://api3.geo.admin.ch
so we have a 301

Same for http -> https remapping.

Geoip block can also be observed via 403 response.

For there is no problem.

**Comment by cedricmoullet** [comment]
Not completely satisfy by the answer.

Why does a PhantomJS script get 503 answers ? 

And we still have 3 or 4 requests ending with a 500 without explanation https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/loader.js . I hope this doesn't hide a more important issue.

**Comment by procrastinatio** [comment]
**PhantomJS**

    $ curl -I -A  "PhantomJS/2.0.0" https://api3.geo.admin.ch/loader.js
    HTTP/1.1 503 Service Unavailable

    $ curl -I -A  "Zorba is back" https://api3.geo.admin.ch/loader.js
    HTTP/1.1 200 OK

hint: _puppetmaster_chtopo/site-modules/chtopo/files/etc/varnish/4.0/blacklist.vcl_

**Comment by procrastinatio** [comment]
**500 sans explications**

Des erreurs WSGI se produisent (*Bucket Brigade* anyone ?). Actuellement, on a 5 erreurs sur 280'000 requêtes, soit 99.998 % OK

Si on veut faire mieux, quelques pistes :

1/ Supprimer la sous-requête sur layersConfig

Pour mémoire, loader.js --> apache --> wsgi --> layersConfig --> apache --> wsgi et retour
on passe alors mathématiquement à 99.999%

2/ MàJ de _mod_wsgi_
Notre version de *mod_wsgi* est 3.3.0 qui date de bien plus de 2 ans.

3/ Tuner Apache
Pour le moment on utilise les paramètres d'usine. Passer de *mpm_prefork* à *mpm_worker* aussi

4/ Utiliser un vrai serveur WSGI
Sachant également que *mod_wsgi* n'est pas le module le plus maintenu de apache.

5/ Statifier loader.js
Et utiliser et promise pour charger la config des couches
