### ISSUE TITLE
DAV0 Migration

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2452]
Here's a list of resources we still currently have on DAV0. We should aim to move them to S3. Where exactly is not yet defined. My proposal would be public.geo.admin.ch bucket.

PDF's in tooltip:
Layer: [ch.bafu.typisierung-fliessgewaesser](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bafu.typisierung-fliessgewaesser&layers_opacity=0.75&X=190000.00&Y=660000.00&zoom=1), Managed by ?
Layer: [ch.bafu.feststoffe-geschiebemessnetz](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers=ch.bafu.feststoffe-geschiebemessnetz), Managed by ?
Layer: [ch.bafu.wasser-teileinzugsgebiete_2](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=179650.00&Y=602100.00&zoom=0&layers=ch.bafu.wasser-teileinzugsgebiete_2&layers_opacity=0.75), Managed by ?
Layer: [ch.bafu.fauna-wildtierkorridor_national](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=voidLayer&X=166050.00&Y=607700.00&zoom=2&layers=ch.bafu.fauna-wildtierkorridor_national), Managed by ?
Layer: [ch.babs.kulturgueter](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers=ch.babs.kulturgueter&layers_opacity=0.75), Managed by ?
Layer: [ch.swisstopo.geologie-geotechnik-gk200](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_opacity=0.75&X=190000.00&Y=660000.00&zoom=1&layers=ch.swisstopo.geologie-geotechnik-gk200), Managed by ?
Layer: [ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_opacity=0.75&X=190000.00&Y=660000.00&zoom=1&layers=ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200), Managed by ?
Layer: [ch.swisstopo.geologie-geotope](https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers=ch.swisstopo.geologie-geotope), Managed by ?

**Comment by gjn** [comment]
@AFoletti @mariokeusen Can you add in the OP above who is managing the resources on DAV0? Mainly, is the client managing this, or are we managing it.

**Comment by ltclm** [comment]
there's also a swissguessr project referencing dav0 documents, not sure if this project is still publihsed:
https://github.com/geoadmin/mf-swissguesser/blob/6260153659b41ab001ae63292ce31d5202b2d734/storymap9.cfg

**Comment by AFoletti** [comment]
@ltclm yes, that's the guesser linked to ch.babs.kulturgueter

**Comment by loicgasser** [comment]
@gjn what bucket do you suggest?

**Comment by AFoletti** [comment]
As discussed today in IGEB teammeeting, goal is to move to datageoadmin bucket

**Comment by loicgasser** [comment]
@AFoletti Do you take care of it/need my help?

**Comment by AFoletti** [comment]
I first need to check some things with @mariokeusen , then we will handle the whole or ask for help where needed 😃

**Comment by mariokeusen** [comment]
IMO we can directly migrate all of those feature attachments from dav0 to S3 data.geo.admin.ch without contacting the customers. Will organize this with @AFoletti upon his return

**Comment by gjn** [comment]
Status?

**Comment by mariokeusen** [comment]
DI tickets opened, planned for the deploy of March 29th

**Comment by loicgasser** [comment]
FYI this migration might require some code change in Chsdi as well. Let me know in advance when this has been done so that I can do it in time.

**Comment by mariokeusen** [comment]
All necessary steps to do are described via data integration process in JIRA: tickets are distributed and in process.

**Comment by gjn** [comment]
@mariokeusen @AFoletti status update?

**Comment by AFoletti** [comment]
work on this issue should resume shortly. @daguer was in the middle of a MuM sprint but this has ended just today.

**Comment by mariokeusen** [comment]
according to the DI tickets this change will go on prod tomorrow Apr. 12th.
