### ISSUE TITLE
ch.bafu.schutzgebiete-aulav_uebrige duplicate feature id

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2460]
Hi @alcapat 
since you have integrated this layer, im assigning this ticket to you.
The layer model in chsdi is referencing two tables with duplicate feature ids (bgdi_id).
The table in the lowres scales uebrige_gebiete_general does not have the attributes for the html template -> tooltip is not working.

please provide a solution. i propose to disable the tooltip for the generalized zoomlevels.

**Comment by gjn** [comment]
@alcapat Can you take care of it?

**Comment by alcapat** [comment]
@gjn ok
