### ISSUE TITLE
[wms-bgdi] no data visible in layers under ch.bav.kataster-belasteter-standorte-oev.oereb

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2472]
UC: use wms.geo.admin.ch, layer ch.bav.kataster-belasteter-standorte-oev.oereb, add both tech. layers
Result: no data are visible
Expected: data are visible

Thanks for investigation. This ticket was opened upon an urgent request by a canton.

**Comment by AFoletti** [comment]
\<comment censured by the author himself\>

**Comment by ltclm** [comment]
i have activated the auto update again, 
the ili2fme version is now up-to-date.

**Comment by mariokeusen** [comment]
Thanks for fixing!
