### ISSUE TITLE
[ch.bafu.gewaesserschutz-badewasserqualitaet] pics in ext. tooltip not visible

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2506]
![image](https://cloud.githubusercontent.com/assets/4577749/24451515/6d70451a-147f-11e7-9d32-77b655ba2631.png)

observed on int and on prod with IE11, Chrome and FF.

Thanks for fixing

**Comment by mariokeusen** [comment]
Source of the pictures is https://data.geo.admin.ch/ch.bafu.gewaesserschutz-badewasserqualitaet/image/

**Comment by loicgasser** [comment]
thanks @mariokeusen will deploy the fix as well.

**Comment by mariokeusen** [comment]
Perfect, thank you
