### ISSUE TITLE
Error 500 for haltestellen only instead of 404 for htmlpopup

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2514]
https://api3.geo.admin.ch/1703301326/rest/services/ech/MapServer/ch.bav.haltestellen-oev/8504569111/htmlPopup?coord=519900,175150&imageDisplay=1920,727,96&lang=fr&mapExtent=432400,155050,624400,227750

**Comment by loicgasser** [comment]
problem comes from the fact that postgres reconize this number as a biginteger and mapping is done on an integer column.

**Comment by rebert** [comment]
using API OpenTransportdata now
