### ISSUE TITLE
Deploybranchint fails

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2524]
Creating deploy/conf/00-branch.conf...
.venv/bin/mako-render --var "git_branch=update_wasta" deploy/conf/00-branch.conf.in > deploy/conf/00-branch.conf
make[1]: Leaving directory '/var/www/vhosts/mf-chsdi3/private/branch/update_wasta'
Traceback (most recent call last):
  File "/usr/bin/deploy", line 116, in <module>
    setup_logging(options.verbose)
  File "/usr/bin/deploy", line 22, in setup_logging
    syslog = SysLogHandler(address='/dev/log')
  File "/usr/lib/python2.7/logging/handlers.py", line 760, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 788, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
Makefile:229: recipe for target 'deploybranchint' failed
make: *** [deploybranchint] Error 1

**Comment by gjn** [comment]
I have similar error when deploying to dev now and creating snapshot. Snapshot can't be created.

Also, make deploydev doesn't throw this error, but the application is not available [under main](https://mf-chsdi3.dev.bgdi.ch/)

@loicgasser @procrastinatio Any idea about the cause?

**Comment by gjn** [comment]
A cleanall in my env results in same problem. Seems related to private env variable PYTHONPATH.

**Comment by gjn** [comment]
hmm. The pythonpath was the problem that the application did not work. Now it's working. But I can't create a snapshot still (error as in OP).

**Comment by gjn** [comment]
It seems like /dev/log is missing on mf1-dev. It's there on production. And it's there on integration with this definition:
`lrwxrwxrwx 1 root root 28 Jan 31 15:27 /dev/log -> /run/systemd/journal/dev-log`

I think @danduk82 s work on the logging might be the cause for this.
