### ISSUE TITLE
[layers] changed alternative titles for several ch.bazl* layers

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2538]
Just imported new alternative titles (mainly new RM translations) from geocat to the bod for almost all ch.bazl layers. Could you please consider that for the next deploy (layer search).
Thanks in advance

**Comment by loicgasser** [comment]
Yes it will be updated automatically at the same time we deploy the BOD.

**Comment by loicgasser** [comment]
Fixed
