### ISSUE TITLE
Missing attribution urls

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2546]
http://api3.geo.admin.ch/rest/services/all/MapServer/layersConfig?lang=fr
Extract of the layer config:

```
"ch.astra.strassenverkehrszaehlung_messstellen-uebergeordnet": {
    .
    "serverLayerName": "ch.astra.strassenverkehrszaehlung_messstellen-uebergeordnet",
    "attributionUrl": "ch.astra.kt.url",
    .
},
"ch.blw.emapis-oekologie": {
    .
    "serverLayerName": "ch.blw.emapis-oekologie",
    "attributionUrl": "ch.blw.kt.url",
    .
},
"ch.swisstopo.geologie-geodaesie-bouguer_anomalien": {
    .
   "serverLayerName": "ch.swisstopo.geologie-geodaesie-bouguer_anomalien",
    "attributionUrl": "ch.swisstopo.sgpk.url",
    .
},
```

**Comment by oterral** [comment]
May be it's normal

**Comment by AFoletti** [comment]
I would say it's normal for the **kt** attributions since most probably there is no single URL to reference to
The **sgpk** could point [here](http://www.sgpk.ethz.ch/) (provided that the page works... it's a 500 right now)
@mariokeusen ?

**Comment by procrastinatio** [comment]
it is the **msgid**, so it is not "translated". You may however have something empty.

**Comment by mariokeusen** [comment]
According to the discussions about those "splitted" data ownerships last year, we decided not to put an URL in these cases. So imo this is ok like this (at least for now) and this issue can be closed.

**Comment by loicgasser** [comment]
ok thanks
