### ISSUE TITLE
When deploying branch, it doesn't work (dev)

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2548]
I just deployed a branch and it doesn't seem to work. I get the following error:

`DistributionNotFound: The 'simplejson==3.10.0' distribution was not found and is required by chsdi`

Is this known?

**Comment by loicgasser** [comment]
https://pypi.python.org/pypi/simplejson/
It seems to exist and it's the latest version of the lib. cleaned my pypi cache and performed a 
`make cleanall user` and it worked.
Temporary pypi glitch?
Could you try again? And if it doesn't work tell me which branch is failing?

**Comment by gjn** [comment]
Tried again, still doesn't work. It's branch gjn_regbl, of this PR https://github.com/geoadmin/mf-chsdi3/pull/2549

**Comment by loicgasser** [comment]
[Test Link](https://mf-chsdi3.dev.bgdi.ch/gal_regbl/)
???
You must be using some custom local libs or something.

**Comment by rebert** [comment]
fixed
