### ISSUE TITLE
Mapproxy tests for 4258 keep failing

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2552]
Please remove/adapt the test if not up to date anymore.

`http://wmts20.int.bgdi.ch//1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/4258/10/6/4.jpeg`

This test keep failing on int.

**Comment by procrastinatio** [comment]
The layer was missing on _int_. For this project, we cannot deploy sperate branch, so sometime, garbage lands on _int_

**Comment by loicgasser** [comment]
Thanks for updating then
