### ISSUE TITLE
RSS feed is not valid

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2557]
https://api3.geo.admin.ch/releasenotes/rss2.xml 

can not be read , since it si not w3c conform

http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fapi3.geo.admin.ch%2Freleasenotes%2Frss2.xml

**Comment by procrastinatio** [comment]
There is no **official** schema for RSS 2, only a specification

**Comment by davidoesch** [comment]
lets at least assure that the syntax fits https://validator.w3.org/feed/
