### ISSUE TITLE
Tooltip fails if date <1900

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#2566]
In GisGeol, some tooltips fail with the following error:
`ValueError: year=1006 is before 1900; the datetime strftime() methods require year >= 1900`
See [here for an example](http://mf-chsdi3.dev.bgdi.ch/ltfoa/rest/services/all/MapServer/identify?geometry=530443.2007690045,156911.35955891423&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1920,521,96&lang=de&layers=all:ch.swisstopo.geologie-gisgeol-flaechen-lt10km2&mapExtent=519703.20076900464,150211.35955891426,558103.2007690046,160631.35955891426&returnGeometry=true&tolerance=10)

Yes, I know that 1006 does not make any sense, but there still are in those gisgeol layers some features with a 1800-something date which are correct (the example is being corrected by the datenherr)
The zeitrehie tooltip does not have the same issue... why?

**Comment by loicgasser** [comment]
lol, yes didn't think we had dates before 1900. I know where it comes from. don't correct too fast :D

**Comment by AFoletti** [comment]
Thanks for the fix! Works wonderfully
