### ISSUE TITLE
applicability of stable IDs within geojson layers

### ISSUE THREAD

**Issue by alainkunz** [geoadmin/mf-chsdi3#2571]
Is it possible to introduce the usage of stable IDs for geojson files within map.geo.admin?

User reports re: changes or questions to swisstopo data are published as ch.swisstopo.meldungen-karten_geodaten and the users receive a confirmation email containing a permalink pointing to the known location of their reports using coordinates. 

Using a stable ID instead of coordinates brings advantages:
- the permalink points always to the appropriate location - even after moving the geometry
- the geometry is highlighted and directly identifiable for the user
- the tool tip is already open

**Comment by loicgasser** [comment]
Yes from a technical point of view it is totally possible. though we need to implement it for vector layers. It shouldn't be too hard. @gjn opinions?
Here is an example of link to object URL.
https://map.geo.admin.ch/?ch.swisstopo.fixpunkte-agnes=PAYE&lang=fr&topic=echc

**Comment by gjn** [comment]
+1 for our geojson layers. I will do it.

Note: with showTooltiop=true, the tooltip will also open, so the message and status is also directly visible.

**Comment by gjn** [comment]
In addition, the tooltip itself could be extend to contain the 'link to object' link pointin to itself.

**Comment by davidoesch** [comment]
+1... Really nice improvement. 
For meldungen karte: it makes sense to use the feedback ID. So we can find the mail and generate the link to the map on the fly. 
In addition: the customer is missing the ETA for the fix in the actual map

**Comment by alainkunz** [comment]
We introduced a UUID as stable ID in addition to the Feedback ID since that id is not necessarily unique. But adding the Feedback ID to the tooltip could easily be done.
ETA  is not known on a feature basis. I don't recall whether Topo included a remark regarding work cycles in their user guides.

**Comment by davidoesch** [comment]
missing ETA: pity for  the user (don't tell the user stuff he already knows ( e.g error in map) tell him sth new (eg when the fix is available) ...its 2017 ,we are supposed to do egov, citizen oriented cc @p1d1d1

**Comment by alainkunz** [comment]
couldn't agree more...

**Comment by oterral** [comment]
Done thanks @nadine-piveteau
