### ISSUE TITLE
Detect variables change to rebuild templates

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2599]
Same approach as in geoadmin

**Comment by loicgasser** [comment]
@Sgachet I'll explain they are plenty of examples of that in geoadmin.
It's just a bit of work

**Comment by Sgachet** [comment]
rc_branch.mako
deploy/deploy-branch.cfg.in
deploy/conf/00-branch.conf.in
apache/application.wsgi.mako
apache/wsgi.conf.in
development.ini.in
production.ini.in

**Comment by procrastinatio** [comment]
OK, done
