### ISSUE TITLE
Json-layer ch.bafu.hydroweb-messstationen_grundwasserzustand is empty

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2604]
UC: open mapviewer, add the layer ch.bafu.hydroweb-messstationen_grundwasserzustand to the map
Result: empty map, no geodata visible
Expected: map layer is available on map

Remark: I have normal json deliveries on the S3 folder each 10mins and the json content looks normal to me

Please fix with high prio.

**Comment by mariokeusen** [comment]
open https://s.geo.admin.ch/74a0839e17

here's what the console gives back:
TypeError: a is null
Stack-Trace:
rb@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:410:411
k.Uc@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:666:643
k.F@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:445:702
Cp@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:883:366
k.Rd@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:883:146
l/</<@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:1458:12
h/<@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:194:467
Mf/this.$get</m.prototype.$digest@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:205:417
Mf/this.$get</m.prototype.$apply@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:209:111
l@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:162:87
wg/</A.onload@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:167:489
 Possibly unhandled rejection: {} build.js:183:210

TypeError: a is null
Stack-Trace:
rb@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:410:411
k.Uc@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:666:643
k.F@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:445:702
Cp@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:883:366
k.Rd@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:883:146
l/</<@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:1458:12
h/<@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:194:467
Mf/this.$get</m.prototype.$digest@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:205:417
Mf/this.$get</m.prototype.$apply@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:209:111
l@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:162:87
wg/</A.onload@https://map.geo.admin.ch/master/ee1dc86/1707191017/1707191017/lib/build.js:167:489
 Possibly unhandled rejection: {}

**Comment by loicgasser** [comment]
GeoJSON on S3 is invalid. it should be `coordinates` not `coordinate` in the geometry field. Please ask them to fix it on their side.
https://data.geo.admin.ch/ch.bafu.hydroweb-messstationen_grundwasserzustand/ch.bafu.hydroweb.hydroweb-messstationen_grundwasserzustand_en.json

see in `geometry` field

**Comment by mariokeusen** [comment]
Thanks for investigation. Requested a fix on the deliverer side.

**Comment by mariokeusen** [comment]
Issue at deliverer's side. GeoJSON export is being fixed on the customer side. No further action from our side needed for now
