### ISSUE TITLE
SHOP cleanup useless attributes from layersConfig

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2612]
From
http://api3.geo.admin.ch/rest/services/all/MapServer/layersConfig?lang=de

ch.swisstopo.swisstlm3d-karte-farbe
ch.swisstopo.digitales-hoehenmodell_25_reliefschattierung
ch.swisstopo.pixelkarte-farbe-pk200.noscale
ch.swisstopo.pixelkarte-farbe-pk100.noscale
ch.swisstopo.swissalti3d-reliefschattierung
ch.swisstopo.pixelkarte-farbe-pk50.noscale
ch.swisstopo.swissimage-product

all these layers have a shop attribute while you can't actually order them.
It's a source of confusion and it would be best to remove this unused property for those layers.
Those are probably artifacts of the first iteration.

@pauloamado could you give me a go to remove the shop attrs for those layers?

**Comment by pauloamado** [comment]
@loicgasser Go for it

**Comment by loicgasser** [comment]
thanks

**Comment by loicgasser** [comment]
https://github.com/geoadmin/tool-wms/pull/93
