### ISSUE TITLE
[copyright tool] aerial imagery copyright link doesn't work anymore

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2622]
This is probably due to cms change and needs a change in bod.
Steps to reproduce: open map.geo.admin.ch, switch the bg-layer to aerial imagery, click the copyright link below right:
![copyright_imagery_issue](https://user-images.githubusercontent.com/4577749/29123649-bd35361e-7d16-11e7-892d-6bad5ea148ca.PNG)

Result: link produces a 404 error.

Workaround: replace links with the following:

DE: https://www.swisstopo.admin.ch/de/home.html
FR: https://www.swisstopo.admin.ch/fr/home.html
IT: https://www.swisstopo.admin.ch/it/home.html
EN: https://www.swisstopo.admin.ch/en/home.html
RM: https://www.swisstopo.admin.ch/de/home.html

**Comment by ltclm** [comment]
bod has been fixed and a mf-chsdi pr is ready for next deploy
