### ISSUE TITLE
Add tilematrixset identifier tests

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2636]
Still has not been done

```xml
<TileMatrixSetLink>
<TileMatrixSet>4326</TileMatrixSet>
</TileMatrixSetLink>
```

at the layer level should be found in

```xml
<TileMatrixSet>
<ows:Identifier>4326</ows:Identifier>
<ows:SupportedCRS>EPSG:4326</ows:SupportedCRS>
....
```

Make sure that for every `TileMatrixSet` there is an `ows:Identifier`.

https://mf-chsdi3.int.bgdi.ch/1.0.0/WMTSCapabilities.EPSG.4326.xml

**Comment by oterral** [comment]
look into the possibility of generating one getcap that contains all the SRIDs.
just look at it, and we'll discuss it
