### ISSUE TITLE
Error 500 on ch.swisstopo.geologie-geologischer_atlas

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#2638]
http://api3.geo.admin.ch/rest/services/api/MapServer/ch.swisstopo.geologie-geologischer_atlas/GA25-PK-140/htmlPopup

**Comment by loicgasser** [comment]
thank you for the heads up.
shop side effect, the shop model was also registered..
This request should not be triggered on this layer as Id for this layer is an integer.
Now such an error will return a 400 error instead.
