### ISSUE TITLE
[ch.bafu.gefahren-baugrundklassen] too much simplified highlight geometries

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2670]
UC: open https://s.geo.admin.ch/767e9103c1, click on the object, compare the object on the map with the highlight geometry appearing with the tooltip
Result: highlight geometry has only 4 nodes. See screenshot
![baugrundklasse_highlight_simplification](https://user-images.githubusercontent.com/4577749/31995638-9a047712-b985-11e7-9a6d-c3479f1b868d.jpg)

Expected: less simplified highlight geometry

**Comment by ltclm** [comment]
fixed with this query:
```sql
update gefahren.baugrundklassen SET 
the_geom_highlight = st_multi(st_buffer(st_simplifypreservetopology(the_geom, 10),0)) WHERE st_npoints(the_geom) >= 10000;

update gefahren.baugrundklassen SET 
the_geom_highlight = the_geom WHERE st_npoints(the_geom) < 10000;

VACUUM FULL ANALYZE gefahren.baugrundklassen;

```
https://mf-chsdi3.dev.bgdi.ch/shorten/7a55524ede

**Comment by ltclm** [comment]
@mariokeusen feedback?

**Comment by mariokeusen** [comment]
Yes, looks much better. Thanks! I think, we can put that on prod.

**Comment by ltclm** [comment]
it is on prod since the last bafu deploy 2018-06-27
