### ISSUE TITLE
Source for cadastral web map should be 2056

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2686]
https://github.com/geoadmin/wms-mapfile_include/blob/91babc7c8c7f889b6506302d6b2bbc5a788f2901/ch.kantone.cadastralwebmap-farbe.map#L18

We should use 2056, which is better as it's the native format.

Not top priority, so can be adapted after LV95 is released. But it should be done eventually.

(opened issue here is this project so it doesn't get lost)

**Comment by rebert** [comment]
https://github.com/geoadmin/wms-mapfile_include/pull/193

**Comment by ltclm** [comment]
the mentioned pr should fix this (thanks @rebert ), but this will stay a wms layer right? we have no idea when data is updated.

**Comment by loicgasser** [comment]
this correct now
