### ISSUE TITLE
Remove model and mako (+unused translations -> edit ms_item and make translate)

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2687]
ch.swisstopo-vd.geometa-standav

@mariokeusen @AFoletti 

do you know if this layer is supposed to have a tooltip? Because we have a model in CHSDI but it is marked without tooltip in the layers config.

**Comment by loicgasser** [comment]
ping @mariokeusen @AFoletti BMD should have this info.

**Comment by AFoletti** [comment]
MuM is not (yet) a reliable source for tooltip info.
But the JIRA ticket comes to our rescue!!

`Foletti Ambrogio added a comment - 28/Sep/12 1:56 PM 
Hey Damien,
We have to implement some changes:
no more tooltip on this layer`

Then: no tooltip is right, model is no more needed

**Comment by loicgasser** [comment]
@daguer please proceed.
