### ISSUE TITLE
WMTS EPSG:3857

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2701]
From a customer:

"Sur le site de notre club (Club des Cent Cols, association sans but
lucratif) nous utilisons des tuiles cartographiques que vous délivrez en projection Mercator sphérique (EPSG:3857). Depuis quelques jours, je constate que ces tuiles (pour un facteur de zoom donné) sont reprojetées sur la base des cartes nationales à une échelle supérieure, par exemple
1:100'000 au lieu de 1:50'000 au zoom 14. Pour une même taille d'image, il y a ainsi nettement moins de détails visibles. Respectivement, pour avoir le même niveau de détail, il faut une image d'une surface 4 fois plus grande."

Maybe related to this?
https://github.com/geoadmin/mf-geoadmin3/pull/4028

**Comment by loicgasser** [comment]
Not sure, what they mean, it seems ok to me.

See:
https://codepen.io/geoadmin/pen/pyzwwL?editors=1010

What layer is it exactly.

**Comment by ltclm** [comment]
as far as i can tell, yes.

The scale limits of the pixelkarte layer / group can be seen here [3] 
The scaledenom values in the mapfile will be interpreted with 96dpi. 
The wms based reprojection into epsg:3857 working as excpected:
``EPSG:3857 zoomlevel 14 [1] -> 9.5m resolution [2]-> scaledenom 37'000 [3] -> pk200``

The scale limits in the mapfile snippet have been optimized for the optimal visualization in the lv03/lv95 pyramid. any changes in here have to be discussed with the Datenherr.

[1] https://github.com/geoadmin/lib-gatilegrid/blob/16cbd91aacd282bd0629a7b0a79f7c8eda27e739/gatilegrid/tilegrids.py#L80
[2] http://api3.geo.admin.ch/services/sdiservices.html#wmts
[3] https://github.com/geoadmin/wms-mapfile_include/blob/master/ch.swisstopo.pixelkarte-farbe.map

**Comment by procrastinatio** [comment]
I guess, this now obsolete, user may `choose between `LK10`, the various `PK*.noscale` and the combination `pixelkarte-farbe`
