### ISSUE TITLE
Profile: avoid parsing problems

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2702]
If profile gets a big body request, it might cause problems while parsing. Timeouts are the result and if many requests come this way, service outage is problable.

Try to find the content-length header before parsing the profile body, if content-length is too big (to be defined) we send a 413.

If content-length header is missing, we send a 411

**Comment by loicgasser** [comment]
yes same should be done in geoadmin. Better stop the request before it's performed.
What is `too big` did you evaluate?

**Comment by loicgasser** [comment]
I consider that it's fixed, PR has been linked. We can decrease the limit if needed.
