### ISSUE TITLE
Missing column in bundinv.amphibien_anhang4.obnr

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2707]
Nightly builds of Jenkins have been failing for a couple of days.

```
ProgrammingError: (psycopg2.ProgrammingError) column amphibien_anhang4.obnr does not exist
LIGNE 1 : ...n_anhang4.name AS bundinv_amphibien_anhang4_name, bundinv.am...
```

meaning someone messed up with this table. Most likely a botched update.
@nadine-piveteau @rebert 
I don't know who's working on this table but could you check it out please?

And remember, if the table structure changes for an update, it's always better to create a new table aside.

Thanks guys

**Comment by rebert** [comment]
I will have a look with @nadine-piveteau

**Comment by nadine-piveteau** [comment]
I've restored the table structure to its previous state, thus, there is now a column called `obnr` in `bundinv.amphibien_anhang4`.
