### ISSUE TITLE
"Feature ID <blabla>: is too large" is not a good solution

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#2720]
When an object has too large a geometry, the identify service currently answers this:
`{
  "status": "error",
  "code": 509,
  "detail": "Feature ID 814241: is too large"
}`

This is (maybe???? But I doubt it) not bad for services but absolutely bad for map.geo.admin.ch, where the user gets nothing. Apart the impression that the layer is broken.
See [here for example](https://s.geo.admin.ch/771999112c)

**My suggestion:**
when the condition for this error is found true, the identify correctly returns the object propreties EXCEPT the geometry.

Assigned @gjn and @davidoesch for evaluation 😄

**Comment by gjn** [comment]
The reason for this is service protection. large geometries result in timeouts and can lead to congestions that then affect other services. As you said, this is almost a necessity from the service point of view.

You can get what you want from the service perspectiv: use the returnGeometry=false parameter as indicated in the documentation and you'll get all other results.

From the application point of view, I agree that it's bad. User should have feedback. Not sure what the best approach would be - in this case, I think that it would make sense to have highlight geometries. We already have a couple of layers with highlight geometries - which are used for highlighting on front-end (and are usually a simplified version of the real geometry).

Could this be possible for this layer?

**Comment by AFoletti** [comment]
Possible is everything. My proposal was a more general one.
Geometry too big=the service answers with attributes but no geometry. We will avoid the 509 error (this giving service-users something useful about the queryed object) while keeping the service protection capability.

**Comment by gjn** [comment]
Might be a possibility - but then again it will confuse the user of the API that he suddenly gets a result but with no geometry - and he doesn't know why.

hen-egg.

We should have geometries in our services that are transferable in http services...

**Comment by AFoletti** [comment]
As I said, it is open to you for evaluation. Concocting a geometry suited for highlight is not a problem if we want to go that way

**Comment by oterral** [comment]
highlight geometry seems a good approach.

**Comment by procrastinatio** [comment]
it makes absolutely no sense to highlight the clicked feature in this example: do you really want to highlight the whole quaternary layer?

**Comment by AFoletti** [comment]
No @procrastinatio  I don't want to highlight a whole quaternary layer. But if you click on it I **want** to become a tooltip, not a hidden error thrown by the service.
Because in the actual state the user is getting nothing --> the layer is for the user broken!!

**Comment by procrastinatio** [comment]
So solved. No highlight, but tooltip.
