### ISSUE TITLE
Tutorial Cesium with terrain and 3D tiles in api doc

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2722]
since we have https://github.com/geoadmin/workshop-cesium3d

we could easily add a tutorial section in the API doc to promote and explain the use of terrain and 3D tiles with CesiumJS as this is not always an easy task.

Maybe something for @nadine-piveteau 

What do you guys think?

**Comment by davidoesch** [comment]
Short term: add it in the example section 
Midterm re4: we are planning a possible relaunch of www.geo.admin.ch and there we would also integrate all tutorials FAQ how to help and documentation.

Setting up tutorials has over caveat: maintenance....

**Comment by procrastinatio** [comment]
Update doc for vector tiles and terrain service with new address (and provide valid timestamp)

**Comment by procrastinatio** [comment]
We have this (already linked in the doc)

**Comment by procrastinatio** [comment]
Done in http://api3.geo.admin.ch/api/examples.html#cesiumjs-examples
