### ISSUE TITLE
No features in table bfe.view_solarenergie_fassaden_gs  for ch.bfe.solarenergie-eignung-fassaden

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2733]
AssertionError: No feature was found in table bfe.view_solarenergie_fassaden_gs for layer ch.bfe.solarenergie-eignung-fassaden

@ltclm do you know what's going on with this layer?

Tests are failing because of the  error above.

**Comment by ltclm** [comment]
staging?
@AFoletti is updating the data on _master and probabyl _dev, dont know.

**Comment by AFoletti** [comment]
The update script was running the whole night. And I deployed the database to DEV this morning so it could be the problem.
Anyways, the view is filled at every stage

**Comment by loicgasser** [comment]
ok thanks, it's a big one, I'll launch so more tests and let you know if the error is still there.

**Comment by loicgasser** [comment]
solved
