### ISSUE TITLE
Unify GWR import

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2745]
2 tables at the moment

1. bfs.adr
2. bfs.gwr_addresses

Unify into one import 

primary key should be egid_edid

we don't need gde_gdename_${lang} as it seems there is always only one language anyway.

but we need stn_strname_${lang}

**Comment by ltclm** [comment]
on-the-fly concatenation of egid_edid has been statified and indexed in db.

**Comment by loicgasser** [comment]
Thks

**Comment by ltclm** [comment]
will be fixed with:
changes in db: https://github.com/geoadmin/tool-wms/pull/120
automated import: https://github.com/geoadmin/bgdi-scripts/pull/259

**Comment by ltclm** [comment]
see here for a short overview of the attributes in v01 and v02 tables and what has been done
https://docs.google.com/spreadsheets/d/1cVuuk2M3U2LMXyDMXsTuGv94ek78FM9L_ipqdQr7pHo/edit?usp=sharing

**Comment by ltclm** [comment]
will be applied 2018-01-22 after the next regular auto-update

**Comment by gjn** [comment]
Can we close this? @loicgasser @ltclm

**Comment by ltclm** [comment]
yes, everything is done.
