### ISSUE TITLE
Error in mako for ch.bav.sachplan-infrastruktur-schiene_anhorung

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2757]
See:
http://mf-chsdi3.dev.bgdi.ch/rest/services/all/MapServer/ch.bav.sachplan-infrastruktur-schiene_anhorung/71-F-01-009/htmlPopup?callback=cb_&lang=de

Mako template error in ch.bav.sachplan-infrastruktur-schiene_anhorung

Relevant traceback

```
 File "/var/lib/jenkins/workspace/MAIN_chsdi3/chsdi/templates/htmlpopup/sis_facilities.mako", line 8, in render_table_body
    <%
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: T00:00:00
```

**Comment by loicgasser** [comment]
only in dev

**Comment by ltclm** [comment]
this interlis data mess will be deployed next monday

**Comment by AFoletti** [comment]
Since this layer needed a deploy today, I changed the date format in the table to solve this problem
