### ISSUE TITLE
API apache add client caching

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2767]
At the moment caching behaviour is as follow:

max-age=31536013, public for versioned URL 

and for external users we simply don't set it at all.

I propose the following changes:

DEV:
non-versioned: no-cache

INT:
non-versioned: public, max-age=3600

PROD:
non-versioned:  public, max-age=3600

Versioned URL as now -> always one year.

One hour of caching for external usage seems reasonable to me.

ping @gjn @procrastinatio Is it a go?

We could go up to one day, but maybe that's too much on all the services.

We could easily set a caching header of 1 day for the SearchServer path.

**Comment by gjn** [comment]
I would vote or 30 minutes. But can live with 60 minutes.

@procrastinatio ?

**Comment by loicgasser** [comment]
I am ok with 30 as well. What about `SearchServer` @gjn ?
Should we treat it differently?
