### ISSUE TITLE
OpenTrans: station not found htmlPopup

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2768]
https://mf-chsdi3.int.bgdi.ch/stationboard/stops/8531261

1. Change error code from 400 to 404
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/stationboard.py#L49
2. In htmlPopup tell the user we don't have data for this station
`No data available for this station`

Try and click the station in the link herehunder:

https://mf-chsdi3.int.bgdi.ch/shorten/779f522017

**Comment by rebert** [comment]
@loicgasser htmlpopup not adapted yet!

**Comment by rebert** [comment]
[try](https://mf-chsdi3.dev.bgdi.ch/ltrea_fix_2768/shorten/779f8b8c84)
