### ISSUE TITLE
Upgrade jquery

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#2792]
As alerted by github, we should upgrade jquery in package.json:

geoadmin/mf-chsdi3
-- | --
Known     moderate severity     security vulnerability detected in jquery < 3.0.0 defined in package.json.                            package.json     update suggested: jquery ~> 3.0.0.                        Always verify the validity and compatibility of suggestions     with your codebase. | Known     moderate severity     security vulnerability detected in jquery < 3.0.0 defined in package.json. | package.json     update suggested: jquery ~> 3.0.0. | Always verify the validity and compatibility of suggestions     with your codebase.
Known     moderate severity     security vulnerability detected in jquery < 3.0.0 defined in package.json.
package.json     update suggested: jquery ~> 3.0.0.
Always verify the validity and compatibility of suggestions     with your codebase.

**Comment by loicgasser** [comment]
We have a lot of deps to check in the external tooltips. I don't for what use cases there is a vulnerability.
But we'll update it, we have the same in geoadmin as well.

**Comment by gjn** [comment]
We can always decide to drop priority - but keeping up-to-date versions is good in general.

**Comment by oterral** [comment]
We could activate greenkeeper for mf-chsdi3 and mf-geoadmin3 like in ol

**Comment by loicgasser** [comment]
yes greenkeeper and https://requires.io/
