### ISSUE TITLE
Missing geometry in shop_swissimage

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2802]
[Mon Jan 22 11:15:02.794920 2018] [wsgi:error] [pid 20212] [remote 10.220.6.245:45064]  [SQL: 'SELECT public.shop_swissimage.pk_product AS public_shop_swissimage_pk_product, public.shop_swissimage.s_title_de AS public_shop_swissimage_s_title_de, public.shop_swissimage.s_title_fr AS public_shop_swissimage_s_title_fr, public.shop_swissimage.s_title_it AS public_shop_swissimage_s_title_it, public.shop_swissimage.s_title_en AS public_shop_swissimage_s_title_en, public.shop_swissimage.available AS public_shop_swissimage_available, ST_AsEWKB(ST_Transform(public.shop_swissimage.the_geom, %(param_1)s)) AS public_shop_swissimage_the_geom \\nFROM public.shop_swissimage \\nWHERE ST_DWITHIN(public.shop_swissimage.the_geom, ST_Transform(ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s), %(param_2)s), %(ST_DWITHIN_1)s) \\n LIMIT %(param_3)s'] [parameters: {'ST_DWITHIN_1': 3.7511354503330687, 'ST_GeomFromWKB_1': <read-only buffer for 0x7f39d93cfdf0, size -1, offset 0 at 0x7f39d8c7dcb0>, 'param_3': 201, 'param_2': 2056, 'param_1': 21781, 'ST_GeomFromWKB_2': 21781}]
****

**Comment by ltclm** [comment]
view has been fixed and updated on _master, _dev, _int, _prod

```sql
begin;
CREATE OR REPLACE VIEW shop_swissimage AS
 SELECT toposhop.pk_product,
    toposhop.s_title_de,
    toposhop.s_title_fr,
    toposhop.s_title_it,
    toposhop.s_title_en,
    toposhop.b_available AS available,
    perim.min,
    st_area(perim.the_geom) AS st_area
,
    perim.the_geom
   FROM datenstand.toposhop_product toposhop,
    ( SELECT min(datenstand.bgdi_id) AS min,
            st_union(blattschnitt.the_geom) AS the_geom
           FROM grid_swissimage_tile blattschnitt
             LEFT JOIN datenstand.gridstand_datenhaltung_swissimage datenstand ON blattschnitt.tilenumber = datenstand.tilenumber::bpchar
          WHERE datenstand.resolutionoforigin > 0::double precision) perim
  WHERE toposhop.pk_product ~~ 'SWISSIMAGE'::text;

ALTER TABLE shop_swissimage
  OWNER TO pgkogis;
GRANT ALL ON TABLE shop_swissimage TO pgkogis;
GRANT SELECT ON TABLE shop_swissimage TO "www-data";
commit;
```

**Comment by ltclm** [comment]
the_geom has been removed from the view looong time ago (2017-07-26 13:55:26) for unknown reasons:
https://github.com/geoadmin/db/compare/72daa2e774cc45214942c37aede668b31b6d5528...6bda2f1063b2a13f7ad023fa1c28e2641fa8136d#diff-df879f19a468b9a761a81bf658a51d37L18583

**Comment by loicgasser** [comment]
thanks
