### ISSUE TITLE
ch.swisstopo.vec200-landcover is missing from the WMTS configuration

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2804]
ch.swisstopo.vec200-landcover 

https://wmts100.geo.admin.ch/1.0.0/ch.swisstopo.vec200-landcover/default/current/2056/21/76/173.png

**Comment by ltclm** [comment]
has been removed with other layers with this commit :
https://github.com/geoadmin/wms-bod/commit/d8b6f236b2c8723e5a4fa23aa7d3ff9911f9581b#diff-8130770192a58555d46adf5cbe3e8b87

No idea what went wrong.
We have to establish a review process of these mapfile.

**Comment by loicgasser** [comment]
It seems that all the vector-200 layers were removed with this commit.
Fishy

**Comment by gjn** [comment]
Many other layers as well were removed.

**Comment by loicgasser** [comment]
yes they have been all added back and deployed to prod.
