### ISSUE TITLE
Default WMTS GetCapabilities still to EPSG:21781

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#2809]
Now `https://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml`points on `https://wmts.geo.admin.ch/EPSG/21781/1.0.0/WMTSCapabilities.xml`

Should we switch on `https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml` ?

**Comment by loicgasser** [comment]
That would mean break the world. Not unless we analyze who's using this service and inform them.

**Comment by gjn** [comment]
Default SRS of services that don't specify explicit version will remain LV03 - as has been communicated during the Bezugsrahmenwechsel.

Communication plan needs to be set up on how we want to migrate this.

**Comment by davidoesch** [comment]
ping @beat-github

**Comment by procrastinatio** [comment]
Nothing to do until the end of time. Closing.
