### ISSUE TITLE
Add LinktoObject Support for .json external data

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2810]
Hi all
since we have  now hydrodaten and Meteoschweiz data delivered via  .json we need in RE4 as well support for

- [x] link to Object as eg GWR (https://map.geo.admin.ch/?ch.bfs.gebaeude_wohnungs_register=141237_0) to enable center on feature
- [ ] parmeter search for activated json layer

-> json into DB for using as REST service .
Nice RE4 task

**Comment by loicgasser** [comment]
@davidoesch The first one has already been implemented

see:

https://map.geo.admin.ch/?ch.bafu.hydroweb-messstationen_gefahren=2004&showTooltip=true&lang=fr


Second I don't understand...

**Comment by gjn** [comment]
Second is feature search of geojson layer (via map.geo search box).

**Comment by davidoesch** [comment]
Seems not to see the case on int?
neither
https://mf-geoadmin3.int.bgdi.ch/?layers=ch.meteoschweiz.messdaten-foehn="EBK"&showTooltip=true&lang=fr
nor
https://mf-geoadmin3.int.bgdi.ch/?lang=de&topic=ech&bgLayer=voidLayer&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&layers=ch.meteoschweiz.messdaten-foehn=EBK&showTooltip=true

etc works

what am I doing wrong?

**Comment by loicgasser** [comment]
Meteo stuff is only on meteo_temp branch

**Comment by loicgasser** [comment]
The first link you put ="EBK" instead of =EBK

**Comment by loicgasser** [comment]
Try
https://mf-geoadmin3.int.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&ch.meteoschweiz.messdaten-niederschlag=CIM&showTooltip=true

**Comment by davidoesch** [comment]
Boys ... you are amazing.

**Comment by loicgasser** [comment]
Girl, thanks to @nadine-piveteau

**Comment by davidoesch** [comment]
OMG ..now I have a #metoo tag on my back

thanks @nadine-piveteau
