### ISSUE TITLE
swisssearch  "gdename" is empty

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2812]
The field "gdename" is always null since at least Sunday February 4.

Example URL (taken from the docs):
https://api3.geo.admin.ch/rest/services/api/MapServer/find?layer=ch.bfs.gebaeude_wohnungs_register&searchText=123164&searchField=egid&returnGeometry=false

{
	"results": [
		{
			"featureId": "1123164_0",
			"attributes": {
				**"gdename": null,**
				"strname1": "T\u00e4gernaustrasse",
				"gstat": 1004,
				"gdekt": "SG",
				"label": "T\u00e4gernaustrasse",
				"ggbkr": "0",
				"egid": 1123164,
				"dstrid": 1097087,
				"gdenr": 3340,
				"bgdi_created": "04.02.2018",
				"plz6": 864500,
				"gkplaus": 288,
				"plz4": 8645,
				"plzname": "Jona",
				"deinr": "13"
			},
			"layerBodId": "ch.bfs.gebaeude_wohnungs_register",
			"layerName": "Register of Buildings and Dwellings",
			"id": "1123164_0"
		},
	....
	]
}
-> issue in data or service?

**Comment by ltclm** [comment]
issue is in the data update script, fix is being prepared...

**Comment by beat-github** [comment]
it works

merci from a client!
