### ISSUE TITLE
Fix codepen example for current timestamp

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2841]
https://codepen.io/geoadmin/pen/MyYYXR?editors=0010

The example above is in the API doc.
All examples with current fail. (html css issue)

In order to change the example, you simply need to login with iwibot access in keepass.

**Comment by procrastinatio** [comment]
OK done (N.B. username is... _geoadmin_)

See https://codepen.io/geoadmin/full/MyYYXR/
