### ISSUE TITLE
Add address example reverse geocoding

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2845]
https://api3.geo.admin.ch/services/sdiservices.html#examples-of-reverse-geocoding

since addresses are free..can you add the example for addresses

**Comment by davidoesch** [comment]
@Sgachet do you have an ETA?

**Comment by p1d1d1** [comment]
I have one:

https://api3.geo.admin.ch/rest/services/api/MapServer/identify?mapExtent=0,0,100,100&imageDisplay=100,100,100&tolerance=1&geometryType=esriGeometryPoint&geometry=600968.625,197426.921875&layers=all:ch.bfs.gebaeude_wohnungs_register&returnGeometry=false

**Comment by davidoesch** [comment]
The tricky part is the tolerance parameter

**Comment by davidoesch** [comment]
ETA?  ping @Sgachet
