### ISSUE TITLE
situation plan: not downloadable

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2846]
https://s.geo.admin.ch/792c73d18c

try to download

I could download it
https://geodata01.admin.ch/download/722174466281897/egris_cadastre.pdf

an external user not

"pdf could not be downloaded"

a geoshop issue

**Comment by loicgasser** [comment]
We can use our proxy. It works.

**Comment by gjn** [comment]
If it's a geoshop issue, then they should solve it.

**Comment by procrastinatio** [comment]
Looks like it is working. Closing for now
