### ISSUE TITLE
migrate public.geo.admin.ch S3 buckets

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-chsdi3#2847]
After the problems we have faced when trying to work with instance profiles, we have decided to migrate the buckets for public.geo.admin.ch to the admin aws account.

This is the proposed migration procedure

1) dev/int

- [x]  lock puppet (varnish and chsdi)
- [x] separate traffic dev and int on both ELBs to test migration at varnish level
- [x]  change /etc/boto.cfg to remove the default profile (this will break the service)
  - [x] on dev
  - [x]  on int
- [x]  deploy chsdi (write to both places PR)
  - [x] on dev
  - [x]  on int
- [x]  sync S3
  - [x] on dev
  - [x]  on int
- [x]  route on new bucket (varnish level)
  - [x] on dev
  - [x]  on int
- [x]  deploy chsdi (use only instance roles PR)
- [x] reset ELBs with both machines for dev and int
- [x]  unlock puppet

2) prod 
- [x]  lock puppet (varnish and chsdi)
- [x] remove default profile
- [x] deploy chsdi A
- [x]  TEST with map.geo.admin.ch prod addresses
- [x]  S3 sync
- [x]  route on new bucket (varnish level)
- [x]  TEST  with map.geo.admin.ch prod addresses
- [x]  deploy CHSDI3 B
- [x]  TEST with map.geo.admin.ch prod addresses
- [x] commit boto samere
- [x]  re-enable puppet on all machines

ORIGINAL: 201803121121
SNAPSHOT A: 201803151635
SNAPSHOT B: 201803161310

**Comment by danduk82** [comment]
@loicgasser and @nadine-piveteau  please review this migration plan

**Comment by gjn** [comment]
I'm not so sure about this. Has this been discussed with Hanspi? Shouldn't we be able to handle multi-account policies better? I can see in the future a real need that we master this better.

I also have other questions regarding the migration (when we do the migration), as we should also adapt the structure of the 
bucket.

And I don't understand if we have downtime for certain services during the migration.

**Comment by gjn** [comment]
regarding structure in bucket: i think it's not a good idea as it would require an ugly varnis rewrite for existing links (that contain public.geo.admin.ch/fileatroot). so forget this. @danduck82

**Comment by loicgasser** [comment]
> Shouldn't we be able to handle multi-account policies better?

yes we do it for simple use cases. (There are a multiple of cross account policies already see JIRA ticket)

Great stuff cross account policies:
https://stackoverflow.com/questions/47654527/aws-s3-server-side-encryption-access-denied-erro

> I don't understand if we have downtime for certain services during the migration.

No downtime
We deploy on one instance at a time.
It really increases complexity to level you don't even imagine. this is not KISS
I think in this particular case there is really no reason to have it outside the admin account.

Since chsdi build is failing we should fix that ASAP.

> we should also adapt the structure of the bucket.

what should we adapt? nothing, it is 1 to 1

> regarding structure in bucket: i think it's not a good idea as it would require an ugly varnis rewrite for existing links (that contain public.geo.admin.ch/fileatroot)

?? no, we migrate all the content. takes about an hour for the 1.5 millions KMLs we have.
No rewrite.

Writing to both bucket is to have 0 downtime and not loose anything.
it's a 2 step deploy.

**Comment by gjn** [comment]
Discussed with Andrea.

We do it on Wednesday.

**Comment by danduk82** [comment]
@gjn , I was also thinking this morning that changing the structure would lead to some (hugly) varnish hacks...

but still, this does not mean that we cannot use a bit more structure in the future. In general we need less of entropy with the buckets, so this might not be the right thread to discuss it... There is also the problem with vectortiles, etc...

**Comment by loicgasser** [comment]
ORIGINAL: 201803121121
SNAPSHOT A: 201803151635
SNAPSHOT B: 201803151651

**Comment by danduk82** [comment]
@nadine-piveteau  and @loicgasser , the sync is finished, and varnish is now pointing to the new bucket.

As far as I have tested it, it seems all good to me. Please test again from your side, and then deploy the snapshot "B".

**Comment by nadine-piveteau** [comment]
I tested snapshot "A" in prod and snapshot "B" in int. Both seem to work fine. I suggest we deploy snapshot "B" to prod.

**Comment by danduk82** [comment]
ok, please go on, and test again.

**Comment by danduk82** [comment]
after the tests are passed, please ensure that the code repository is up-to-date in master branch

**Comment by danduk82** [comment]
@procrastinatio could you please also review the code after all this is over?

**Comment by danduk82** [comment]
Migration is finished, thanks a lot to @nadine-piveteau and @loicgasser . No downtimes, no errors, great job.
