### ISSUE TITLE
Public transportation stop:  wintertime not taken into account

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2864]
Issue:

> Ich weiss nicht. ob es ein Datenliefer- oder ein Umsetzungsproblem ist: Die Abfahrtszeiten auf map.geo.admin.ch werden nach Winterzeit umgerechnet angezeigt. Untenstehender Screenshot ist von 08:04 Uhr und es erscheinen Abfahrten der Linie 323 um 07:35 und 11:35. Nach Fahrplan fährt die Linie 30.323 um 08:35 und 12:35. Eine schnelle Lösung dieses Problems wäre angezeigt!            

 
![image](https://user-images.githubusercontent.com/4577727/38013452-7d4ff9d0-3265-11e8-894e-4d53417bdf38.png)
> 

Current situation
Die Abfrage auf den Service:

> <?xml version="1.0" encoding="UTF-8"?>
> <Trias version="1.1" xmlns="http://www.vdv.de/trias" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
>     <ServiceRequest>
>         <siri:RequestTimestamp>2018-03-28T08:36:11</siri:RequestTimestamp>
>         <siri:RequestorRef>EPSa</siri:RequestorRef>
>         <RequestPayload>
>             <StopEventRequest>
>                 <Location>
>                     <LocationRef>
>                         <StopPointRef>8507089</StopPointRef>
>                     </LocationRef>
>                     <DepArrTime>2018-03-28T08:36:11</DepArrTime>
>                 </Location>
>                 <Params>
>                     <NumberOfResults>5</NumberOfResults>
>                     <StopEventType>departure</StopEventType>
>                     <IncludePreviousCalls>false</IncludePreviousCalls>
>                     <IncludeOnwardCalls>true</IncludeOnwardCalls>
>                     <IncludeRealtimeData>true</IncludeRealtimeData>
>                 </Params>
>             </StopEventRequest>
>         </RequestPayload>
>     </ServiceRequest>
> </Trias>
> 
> 
> Führt zu folgender Antwort:
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Trias xmlns="http://www.vdv.de/trias" version="1.1">
> <ServiceDelivery>
>     <ResponseTimestamp xmlns="http://www.siri.org.uk/siri">2018-03-28T06:37:49Z</ResponseTimestamp>
>     <ProducerRef xmlns="http://www.siri.org.uk/siri">EFAController10.2.9.62-WIN-G0NJHFUK71P</ProducerRef>
>     <Status xmlns="http://www.siri.org.uk/siri">true</Status>
>     <MoreData>false</MoreData>
>     <Language>de</Language>
>     <DeliveryPayload>
>         <StopEventResponse>
>             <StopEventResult>
>                 <ResultId>ID-92427719-4F2B-4D3D-8750-46BA8B45A53C</ResultId>
>                 <StopEvent>
>                     <ThisCall>
>                         <CallAtStop>
>                             <StopPointRef>8507089</StopPointRef>
>                             <StopPointName>
>                                 <Text>Schwarzenburg</Text>
>                                 <Language>de</Language>
>                             </StopPointName>
>                             <PlannedBay>
>                                 <Text>1</Text>
>                                 <Language>de</Language>
>                             </PlannedBay>
>                             <ServiceDeparture>
>                                 <TimetabledTime>2018-03-28T06:48:00Z</TimetabledTime>
>                                 <EstimatedTime>2018-03-28T06:48:00Z</EstimatedTime>
>                             </ServiceDeparture>
>                             <StopSeqNumber>1</StopSeqNumber>
>                         </CallAtStop>
>                     </ThisCall>
> 
>

**Comment by davidoesch** [comment]
The times in the requests are probably our timezone (I assume you just did them, that’s why).

The times in the response are UTC (because of the ‘Z’ in the end). And they seem to be correct to me.

So it might be that we interpret it wrongly when displaying it.

**Comment by rebert** [comment]
hotfix: https://mf-chsdi3.dev.bgdi.ch/ltrea_tmp_fix_sommertime/shorten/7996c38183
https://github.com/geoadmin/mf-chsdi3/pull/2865

**Comment by rebert** [comment]
I'm investigating in a dynamic solution (not based on UTC+2)
