### ISSUE TITLE
Most of the Vermessung layers not available

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2878]
UC: open map.geo.admin.ch, topic Grundstückinformation, add the following layers:
ch.kantone.cadastralwebmap-farbe,ch
swisstopo-vd.geometa-nfgeom,ch
ch.swisstopo-vd.stand-oerebkataster
ch.swisstopo-vd.ortschaftenverzeichnis_plz
ch.swisstopo-vd.amtliche-vermessung

Result: no layer data displayed, map stays empty
Workaround: please check the data sources of these layers (geoshop and Amodb).

**Comment by ltclm** [comment]
seems to be a certificate issue, wms requests are working fine with http. i have just written an email to fsdi-emergency@googlegroups.com .

**Comment by mariokeusen** [comment]
ok, merci

**Comment by danduk82** [comment]
fixed with emergency deploy, we use again wms.geo.admin.ch until new order.

fixed with https://github.com/geoadmin/mf-geoadmin3/releases/tag/r_180416
