### ISSUE TITLE
offset param not documented

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2879]
@davidoesch @gjn @loicgasser do you remember why the offset param (paging stuff) of identify service is not documented?

**Comment by davidoesch** [comment]
Assumption:  back in the days when gwr/addresses request results were limited to 50 ?
-> you can document it.

**Comment by loicgasser** [comment]
Yes we tried to avoid data scraping.

**Comment by procrastinatio** [comment]
@danduk82  @ltkum Basically, where do we document _undocumented_ features?

**Comment by davidoesch** [comment]
Yeah I'm interested in that one as well

**Comment by loicgasser** [comment]
I think it was to avoid data scraping. You put the extent of switzerland and then you add more and more offset.
