### ISSUE TITLE
Fix  test_identify_order_by_distance 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2893]
Currently for an identify request we have 3 differents results on our 3 environments (with the same data?):

[dev](http://mf-chsdi3.dev.bgdi.ch/rest/services/all/MapServer/identify?layers=all%3Ach.bfs.gebaeude_wohnungs_register&imageDisplay=1920%2C765%2C96&mapExtent=641960.1008933608%2C163518.83578498938%2C646760.1008933608%2C165431.33578498938&geometry=643952.5%2C164121.24999999997&geometryFormat=geojson&geometryType=esriGeometryPoint&tolerance=50)
[int](http://mf-chsdi3.int.bgdi.ch/rest/services/all/MapServer/identify?layers=all%3Ach.bfs.gebaeude_wohnungs_register&imageDisplay=1920%2C765%2C96&mapExtent=641960.1008933608%2C163518.83578498938%2C646760.1008933608%2C165431.33578498938&geometry=643952.5%2C164121.24999999997&geometryFormat=geojson&geometryType=esriGeometryPoint&tolerance=50)
[prod](http://mf-chsdi3.prod.bgdi.ch/rest/services/all/MapServer/identify?layers=all%3Ach.bfs.gebaeude_wohnungs_register&imageDisplay=1920%2C765%2C96&mapExtent=641960.1008933608%2C163518.83578498938%2C646760.1008933608%2C165431.33578498938&geometry=643952.5%2C164121.24999999997&geometryFormat=geojson&geometryType=esriGeometryPoint&tolerance=50)

That breaks the test on int as reported by @rebert : 
```
======================================================================
FAIL: test_identify_order_by_distance (tests.integration.test_identify_service.TestIdentifyService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/vhosts/mf-chsdi3/private/snapshots/201805011435/chsdi3/code/chsdi3/tests/integration/test_identify_service.py", line 730, in test_identify_order_by_distance
	self.assertNotEqual(firstBefore, firstAfter)
AssertionError: u'75b' == u'75b'

```

So if it's normal we should fix the test otherwise the data.

**Comment by procrastinatio** [comment]
Sadly, we cannot assume data are always the same in the three environments.

**Comment by procrastinatio** [comment]
Closing
