### ISSUE TITLE
Create vec Service description in api.geo.admin.ch

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2903]
Inspiration 

https://www.mapbox.com/vector-tiles/specification/

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-chsdi3/pull/3060 and https://github.com/geoadmin/mf-chsdi3/pull/3062

**Comment by procrastinatio** [comment]
And also https://github.com/geoadmin/mf-chsdi3/pull/3120

**Comment by procrastinatio** [comment]
One of the above PR merged. Closing
