### ISSUE TITLE
Returned geometries SR is independent from the SR of the geometry to identify on

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2910]
From @RobertoMinelli at https://github.com/geoadmin/mf-geoadmin3/issues/4320  : 

I figured out that identify requests with returnGeometry=true always return geometries in LV03 spatial reference.

I believe it makes sense that the returned geometries have the same format of the geometries to identify on. If I specify geometries in sr=2056 it would be consistent that also the returned geometries are in sr=2056 and not in sr=21781.

Just my 2 cents.

Best,
Roberto

**Comment by procrastinatio** [comment]
@RobertoMinelli  Do you have any examples ?

**Comment by RobertoMinelli** [comment]
Hi,

If I am not mistaken, if you use a geometry in LV95 you get as a result geometries in LV03.

I’ll try to come up with an example ASAP.

Best,
RM

On 23 May 2018, at 11:37, Marc <notifications@github.com<mailto:notifications@github.com>> wrote:


@RobertoMinelli<https://github.com/RobertoMinelli> Do you have any examples ?

**Comment by procrastinatio** [comment]
These look OK:

* [identify](https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=2678250,1213000&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1391,1070,96&lang=fr&layers=all:ch.bafu.nabelstationen&mapExtent=2312250,-1077500,21007750,1457500&returnGeometry=true&tolerance=5&sr=2056)
* [find](https://api3.geo.admin.ch/rest/services/api/MapServer/find?layer=ch.bafu.bundesinventare-bln&searchText=Lavaux&searchField=bln_name&returnGeometry=true&sr=2056)
* [FeatureResource](https://api3.geo.admin.ch/rest/services/api/MapServer/ch.bafu.nabelstationen/RIG?sr=2056)
* [Search](https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=wabern&type=locations&sr=2056)

**Comment by RobertoMinelli** [comment]
Dear @procrastinatio and @oterral,

I finally understood the problems.

I managed to reproduce my problem using a find requests to the `ch.bfe.solarenergie-eignung-daecher` layer.

The only working version is by specifying the `sr` to `2056`. In this way the returned geometries are indeed in `LV95 (2056)`. [Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?contains=false&returnGeometry=true&lang=en&layer=ch.bfe.solarenergie-eignung-daecher&searchField=building_id&searchText=899274&sr=2056) is the working request.

The below versions are instead buggy:

- If you **do not** specify a `sr`, the returned geometries are in `LV03 (21781)` but the `spatialReference` field in the response states `"wkid": 2056`. [Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?contains=false&returnGeometry=true&lang=en&layer=ch.bfe.solarenergie-eignung-daecher&searchField=building_id&searchText=899274) is the corresponding buggy request.

- If you **do specify** a `sr= 21781`, the returned geometries are in `LV03 (21781)` but the `spatialReference` field in the response states `"wkid": 2056`. [Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?contains=false&returnGeometry=true&lang=en&layer=ch.bfe.solarenergie-eignung-daecher&searchField=building_id&searchText=899274&sr=21781) is the corresponding buggy request.

Best,
RM

**Comment by procrastinatio** [comment]
Hello thank you for the examples.
For  the layer `ch.bfe.solarenergie-eignung-daecher it looks like it is a DB issue, I did observe your problem only on the currently production DB; on the upcoming data currently in integration, it looks OK.
I also did a few test on radom layers, it looks OK.

**Comment by oterral** [comment]
Noxt deploy on wednesday it should be fixed . Thx for debugging @RobertoMinelli  and testing @procrastinatio

**Comment by RobertoMinelli** [comment]
Great, thanks @oterral and @procrastinatio for fixing this!

**Comment by procrastinatio** [comment]
@RobertoMinelli Could you test? Should be OK now.

**Comment by RobertoMinelli** [comment]
Dear @procrastinatio, sorry for my late reply. I confirm that now it works for the layer `ch.bfe.solarenergie-eignung-daecher`.

- If you **do not** specify a `sr`, the returned geometries are in `LV03 (21781)` and the `spatialReference` field in the response states `"wkid": 21781`. [Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?contains=false&returnGeometry=true&lang=en&layer=ch.bfe.solarenergie-eignung-daecher&searchField=building_id&searchText=899274) is the corresponding request.

- If you **do specify** `sr= 21781`, the returned geometries are indeed in `LV03 (21781)` and the `spatialReference` field in the response states `"wkid": 21781`. [Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?contains=false&returnGeometry=true&lang=en&layer=ch.bfe.solarenergie-eignung-daecher&searchField=building_id&searchText=899274&sr=21781) is the corresponding request.

- If you **do specify** `sr= 2056`, the returned geometries are indeed in `LV95 (2056)` and the `spatialReference` field in the response states `"wkid": 2056`. [Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?contains=false&returnGeometry=true&lang=en&layer=ch.bfe.solarenergie-eignung-daecher&searchField=building_id&searchText=899274&sr=2056) is the corresponding request.

Cheers,
Rob

**Comment by procrastinatio** [comment]
@RobertoMinelli So solved. 
Thank you for the feed back
