### ISSUE TITLE
BFE Windenergieanlagen tooltip with wrong power values

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#2921]
The handling of numerical values in [this layer](https://s.geo.admin.ch/7b1df89a19) is wrong.
See makos [here](https://github.com/geoadmin/mf-chsdi3/blob/d3fd371709e5726f3eb433066a43474b533d3cbf/chsdi/templates/htmlpopup/windenergieanlagen_facility.mako#L88) and [here](https://github.com/geoadmin/mf-chsdi3/blob/d3fd371709e5726f3eb433066a43474b533d3cbf/chsdi/templates/htmlpopup/windenergieanlagen_turbine.mako#L89)

This has the effect of cutting the last digits in some tooltips as in [this one ](https://api3.geo.admin.ch/rest/services/ech/MapServer/ch.bfe.windenergieanlagen/facility_CHA/extendedHtmlPopup?lang=de) where the "Installierte Leistung" is 30 kW  for the Anlage (wrong) and 3000 for the turbine (right). 
Note that the values in the service are both right!

**Please make the tooltip and extended tooltip show the power exactly as entered in the database!**

I think the main problem is that in the database the turbine power is entered as double but is a text in the facility table. Please handle numbers as numbers and not strings. The problem then originates in the database and cascades to the mako via the model

Please fix ASAP

**Comment by daguer** [comment]
Bug fixed.
Ready to merge: https://github.com/geoadmin/mf-chsdi3/pull/2922

Testlink:
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&zoom=6&wms_url=%2F%2Fwms-bgdi.dev.bgdi.ch%2Fxx%2F&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltgud_windenergieanlagen_bug&layers=ch.bfe.windenergieanlagen&layers_opacity=0.75&E=2569756.62&N=1224119.37

**Comment by AFoletti** [comment]
Thanks, that's already much better.
Bonus points if you can make the normal tooltip display exactly what's in the DB too. Now it's adding an unnecessary ".0" at the end. See [here](https://mf-chsdi3.dev.bgdi.ch/ltgud_windenergieanlagen_bug/shorten/7b1efb7b30)

**Comment by AFoletti** [comment]
Thanks!
