### ISSUE TITLE
SWISSIMAGE whole area calculation price - bug to fix

### ISSUE THREAD

**Issue by pauloamado** [geoadmin/mf-chsdi3#2975]
In the Shop: when calculating the price of the whole area of SWISSIMAGE 25cm, the price is calculated only with the resolution of 25cm. The the price is around 80'000.- more expensive than reality! (all elements of 50cm area are not considered...). 
All area (25cm + 50cm) = CHF 149'428.35
All area (25cm) = CHF 233495.75

It means that the cut service returns only the whole area in 25cm to the shop calculator.
It's good business ;-) but it should be corrected...

**Comment by procrastinatio** [comment]
It is even worse I think:

    curl "https://shop.swisstopo.admin.ch/shop-server/resources/products/price?layer=ch.swisstopo.swissimage-product&geometry=445500,38250,887000,302750"
   {"productPrice":5878695}

SWISSIMAGE 50cm ???

**Comment by pauloamado** [comment]
CHF 58786.95 is the price for the wholw area in resolution 50cm

**Comment by procrastinatio** [comment]
I don't get it... 
And there is no SWISSIMAGE 50 cm layer

_Allez, 40'000.- et on en parle plus_

**Comment by pauloamado** [comment]
Non il n'y a pas de layer 50cm, mais il y a des zones qui contiennent du 25cm et du 50cm dans le layer SWISSIMAGE. Le cut service de Loïc fait la part des choses: il renvoie au Shop la surface 25 et la surface 50 pour le calcul final du prix. Mais dans le cas du jeu de données complet, je sais pas pourquoi, Loïc renvoie le tout en 50cm, il ne sépare pas les zones.

_OK pour 40'000.- mais je t'offre un saucisson, ça me fait plaisir..._

**Comment by procrastinatio** [comment]
Aire 25/50cm https://s.geo.admin.ch/7d04265de1
Documentation 
 https://github.com/geoadmin/mf-chsdi3/blob/ee88d1b4323b27fbe4630434e833874aa4f841a5/tests/integration/test_features_service.py#L446-L576

**Comment by pauloamado** [comment]
Merci Marc, à voir maintenant comment envoyer les deux au Shoshop...
1000Thx & InZeMix

**Comment by loicgasser** [comment]
salut les jeunes.
c'est dificile a debuger car geoadmin n'appelle le service directement.
Un example de requete pour swissimage avec un bounding box.

http://api3.geo.admin.ch/rest/services/ech/GeometryServer/cut?geometryType=esriGeometryEnvelope&geometry=545000,145000,625000,210005&layers=all:ch.swisstopo.swissimage-product&groupby=resolution

Et donc pour le jeu de donnee complet on a:
http://api3.geo.admin.ch/rest/services/ech/GeometryServer/cut?layers=all:ch.swisstopo.swissimage-product&groupby=resolution

@procrastinatio voila la requete a debugger.
Le groupby n'est pas pris en compte.

Where it happens in the code
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/features.py#L483

totalArea is set here:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/lib/validation/geometryservice.py#L40

You should have all you need to debug it and add the right tests.

**Comment by ltclm** [comment]
thanks @loicgasser for the hints.
by design, it is not possible to get the total area grouped by resolution without sending a bbox to the cut service.
The following pseudo bbox ``geometry=0,0,9999999,9999999`` would return the total amount of available swissimage surface grouped by resolution:
```
http://localhost:9076/rest/services/ech/GeometryServer/cut?geometryType=esriGeometryEnvelope&geometry=0,0,9999999,9999999&layers=all:ch.swisstopo.swissimage-product&groupby=resolution

{
ch.swisstopo.swissimage-product: [
{
groupbyvalue: 0.25,
groupby: "resolution",
area: 31145.63,
},
{
groupbyvalue: 0.5,
groupby: "resolution",
area: 13899.38,
},
]
}
```

The sum is the same as totalArea returned without geometry:
```
http://localhost:9076/rest/services/ech/GeometryServer/cut?layers=all:ch.swisstopo.swissimage-product&groupby=resolution
{
ch.swisstopo.swissimage-product: [
{
groupbyvalue: null,
groupby: null,
area: 45045,
}
]
}
```

@pauloamado is the price service able to calculate the prize with the groupby response of the cut service (see first result above)?  For ch.swisstopo.swissimage-product the cut service should be called with parameter ``groupby=resolution`` (to be hardcoded in mf-geoadmin3)

**Comment by loicgasser** [comment]
I would do that in the backend since the shop is calling the service.

**Comment by procrastinatio** [comment]
The backend is already correct. The frontend/shop must only always send a geometry, either explicit (bbox) or implicit (commune, blatt, etc.)

**Comment by procrastinatio** [comment]
@pauloamado Can you test the shop with the branch https://mf-chsdi3.int.bgdi.ch/mom_fix_swissimage ?

**Comment by pauloamado** [comment]
I modified the parameters of the Shop Int with your fix-branch. It seems to be correct now :) I have to check further more with the topo. Thx !

**Comment by pauloamado** [comment]
It's ok, your calculation is correct now. Thx a lot for the job !
