### ISSUE TITLE
Unable to download tiles: CORS error

### ISSUE THREAD

**Issue by igghera** [geoadmin/mf-chsdi3#2980]
Hi,

I hope this is the right place to raise this issue. I have a website running geoadmin maps on this page https://ticino4580.netlify.com/mappe/.

Since last week, the tiles for the map are no longer loading, and the error in the console is clear:

Access to Image at 'https://wmts9.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/21781/14/0/1.jpeg' from origin 'https://ticino4580.netlify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ticino4580.netlify.com' is therefore not allowed access. The response had HTTP status code 403.

If I try to load the same page on localhost, it works fine.

I've copied the code from the example found in the docs: https://codepen.io/geoadmin/pen/qbeqPQ?editors=0010

What am I doing wrong? It used to work fine up to last week. 

Thanks in advance,
Andrea

**Comment by davidoesch** [comment]
Hi
the domain  https://ticino4580.netlify.com/
<https://ticino4580.netlify.com/mappe/> is not registered via
www.swisstopo.ch/webaccess and
https://www.geo.admin.ch/de/geo-services/geo-services/portrayal-services-web-mapping/programming-interface-api/order_form.html

Please do mind that third party hoster sub domain can not be registered:
you need to register a full domain which you actually own

Best regards

David

**Comment by procrastinatio** [comment]
May I close this?

```
curl -I -H "Origin: https://ticino4580.netlify.com/mappe/" https://wmts9.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/21781/14/0/1.jpeg
HTTP/1.1 200 OK
Accept-Ranges: bytes
Accept-Ranges: bytes
Access-Control-Allow-Origin: *```

**Comment by davidoesch** [comment]
Ping @igghera 

We will Close this issue

**Comment by igghera** [comment]
Yeah sure, thanks for the heads-up!
