### ISSUE TITLE
API returns invalid GeoJSON

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#3020]
e.g. this request:

http://api3.geo.admin.ch/rest/services/api/MapServer/ch.swisstopo.swissboundaries3d-kanton-flaeche.fill/1?geometryFormat=geojson

is invalid according to http://geojsonlint.com/:

1) response structure is not correct
2) coordinates do not follow the right-hand rule (see GeoJSON specs)

As far as 1) is concerned, the API returns the following structure (I filtered the coordinates out for readability):

https://gist.github.com/p1d1d1/af240b4261f8d0313d75ea56aae7d96e
This is valid JSON but invalid GeoJSON

You'll find a valid (I guess) GeoJSON here:
https://gist.github.com/p1d1d1/a33b090eefd7f2c883479d59b9e742aa

**Comment by procrastinatio** [comment]
@p1d1d1 See PR #3021 . Should be valid (Geo)JSON, but will break things for sure. Not a big fan.

**Comment by p1d1d1** [comment]
@procrastinatio I guess because of this?

https://github.com/geoadmin/mf-chsdi3/pull/3021/files#diff-3d6ec0899d4ddab81529319f9f6ee359L381

Won't be possible to have an IF THEN based on the value of the parameter "geometryFormat" ?

**Comment by pakb** [comment]
Still not totally covered, as state in the PR https://github.com/geoadmin/mf-chsdi3/pull/3021

**Comment by danduk82** [comment]
@davidoesch, do have some clients who could give a feedback on [this pr](https://github.com/geoadmin/mf-chsdi3/pull/3135)

**Comment by davidoesch** [comment]
@p1d1d1 we need to assess the potential side effects:
can you together with @danduk82 @procrastinatio screen the kibana logs and identify possible affected users in the last 4 months? the wen ened to establish a com and migration plan

**Comment by procrastinatio** [comment]
Please check again, but according to my investigations, in the last 3 month, about 21 millions of requests of this type (very difficult to filter out), no a single time was `geometryFormat` was specified, let alone `geojson`. So yes, basically, nobody cares.

**Comment by davidoesch** [comment]
Decision: since no impact observed:
-> go  for this PR https://github.com/geoadmin/mf-chsdi3/pull/3135 
if there is one: we can roll back ( "we break it we fix  @it")

**Comment by procrastinatio** [comment]
Merged. So closing
