### ISSUE TITLE
API: update  to OL5?

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#3043]

**Comment by danduk82** [comment]
personally I would like to announce an EOL for JS API and push for the usage of iframe.

@davidoesch and @gjn , what do you think?

**Comment by davidoesch** [comment]
negativ: we commited ourself to CMS VBS to deliver an API - notice time : 2 yrs
moreover: we  do not offer a JS API... ppl use the OL api

**Comment by danduk82** [comment]
what about `//api3.geo.admin.ch/loader.js?version=4.4.2` is this no js api?

**Comment by procrastinatio** [comment]
The default is still `3.3.6`, communicate that we'll upgrade to 4.
And if we need an OL 5 and 6, version, should be planned (easy to externalize)

But it is trivial to use pure OL 5, or Leaflet

**Comment by danduk82** [comment]
won't fix
