### ISSUE TITLE
Official 3D Example is not working

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#3061]
http://codepen.io/geoadmin/pen/zBEYGE?editors=0010

The example doesn't load the 3D tiles.

**Comment by danduk82** [comment]
@gjn you mean: buildings, trees and names?

@pakb this is one for you ;)

**Comment by danduk82** [comment]
because the terrain files are correctly loaded (in my browser)

**Comment by pakb** [comment]
That's a limitation only applied to Linux drivers by the 3D engine used by Cesium (works fine on W10 with EDGE for instance), is it worth it to investigate further?

**Comment by procrastinatio** [comment]
1/ tileset address is wrong (empty)
2/ codepen.io is forbidden by cloudfront.

**Comment by danduk82** [comment]
yes please

**Comment by danduk82** [comment]
it uses terrain0-4 not cloudfront

**Comment by danduk82** [comment]
and using `vectortiles0` instead of `vectortiles` is important

**Comment by procrastinatio** [comment]
So anyone with a valid referer may access the terrain and 3 tiles, right?

**Comment by procrastinatio** [comment]
Example updated.
