### ISSUE TITLE
update api3 documentation for 3d-tiles and terrain

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-chsdi3#3079]
There was a customer feedback that points that our documentation is not up-to date with the status of the data.
in particular `tileset.json` files for `/3d-tiles/` 

Will check and PR an update.

**Comment by danduk82** [comment]
Hi @rebert , can you please pass through the API3 doc, and check that the described resources for terrain and 3d are compliant with the ones used by map.geo.admin.ch? For example, 3d objects do not point to the correct tileset.
We might have a look toghether next week.
Ideally this docu patch should go live in next deploy in 2 weeks.

**Comment by rebert** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/3095
