### ISSUE TITLE
Link of layer ch.dritte.mobility-standorte does not work any more

### ISSUE THREAD

**Issue by rebert** [geoadmin/mf-chsdi3#3082]
The link of the tooltip in ch.dritte.mobility-standorte does not work any more. Propose a solution?

**Comment by AFoletti** [comment]
I think I can allow myself to tag @cype for that one ;)

**Comment by davidoesch** [comment]
It's all in https://jira.swisstopo.ch/browse/BGDIDI_KB-1377?jql=text%20~%20%22Ch.bfe.mobility%22

Jira is The place for data related issue.
@foa do we already have a migrated ticket?

**Comment by AFoletti** [comment]
No, we have not. I will create one.
But in the ticket I find just questions and no answer whatsoever. Anyways, this ticket can in my opinion be closed and we continue to look into the issue in the JIRA one
