### ISSUE TITLE
Add Makefile target to deploy statified layerConfig

### ISSUE THREAD

**Issue by boecklic** [geoadmin/mf-chsdi3#3083]
This is the counterpart of https://github.com/geoadmin/mf-geoadmin3/issues/4695 for the backend. 
1/ Services

Topics list (not localized)
https://api3.geo.admin.ch/rest/services [statified in geoadmin]
Layers config (localized)
https://api3.geo.admin.ch/rest/services/ech/CatalogServer?lang=en [statified in geoadmin]
Catalog (localized)
https://api3.geo.admin.ch/rest/services/ech/CatalogServer?lang=en [not statified in geoadmin]

2/ Bucket
Use the already defined` ${S3_MF_GEOADMIN3_INT}` and `${S3_MF_GEOADMIN3_PROD}`, but another folder (already behind CloudFront).
On dev everything is dynamically served by Apache, to ease developpment.

3/ Manamagement
Look at `s3deployprod`, `s3listprod` and `s3activateprod` for inspiration.. create a snapshot folder as we do for the code, and use a `activate` feature to copy the correct version in the same way that is done for mf-geoadmin3. Attention: the snapshot ID has to be in the release notes of `mf-chsdi3`.

**Comment by danduk82** [comment]
done in mf-geoadmin3
