### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#3092]
"Fäch" (Flurname) not in the search result list:

1) https://s.geo.admin.ch/7fc95c2b93
2) Search "Fäch" --> no result

![image](https://user-images.githubusercontent.com/1533649/51970218-9cfbcf80-2476-11e9-8ab8-e6c177da9c48.png)

**Comment by davidoesch** [comment]
![image](https://user-images.githubusercontent.com/4577727/51971312-23191580-2479-11e9-91a2-5da934dfc08c.png)

@ltclm why do we not have the additional point Fäch  as Flurname in the result list?

**Comment by ltclm** [comment]
there are two data sources for swisssearch (origins=gazetteer)
* swissnames3d
* dkm

In the search requests you only get the result of dkm, not the one of swissnames:

```sql
-- db stopo_prod
-- fäch results in dkm
SELECT * FROM tlm.dkm_search WHERE name like 'faech%' limit 10;

-- fäch results in swissnames
SELECT name, st_asewkt(the_geom) FROM tlm.swissnames3d_point WHERE name like 'Fäch' limit 10;
```

In the sphinx query the results of dkm have priority over the results of swissnames.
That's why you wont find any swissnames results here.

> Why make things simple when you can make them complicated?

**Comment by davidoesch** [comment]
For me solved

**Comment by p1d1d1** [comment]
Just to understand: if i search for Fäch (interface in DE) the second and the sixth hits are "Flurname swisstopo Fächt (VS) - Simplon" and "Flurname swisstopo Fächt (VS) - Simplon". The same string.
Is one of those coming from dkm and the other from swissnames? If yes then I also expect to find Fäch

**Comment by ltclm** [comment]
The second and the sixth hits are two different swissnames objects with different coordinates.
Fäch is on first position, it is coming from dkm.
as i already said, the swisssearch result is a mixture of dkm and swissnames, if there are results in dkm they will be displayed, regardless if their are the same objects / results in swissnames, in this case swissnames results will be skipped.

see also https://github.com/geoadmin/service-sphinxsearch/pull/275
