### ISSUE TITLE
[MVT] Provide getCap for vec tiles

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3098]
According to the documentation (here: https://tileserver.readthedocs.io/en/latest/endpoints.html#wmts-capabilities) TileServer generates a capability document but I’m not able to find it for vectortiles.geo.admin.ch

**Comment by ltkum** [comment]
As we are using the serve_rendered option as false (we do not provide raster generation), for performance purposes, wmts capabilities files are not generated and the enpoint is not available.

**Comment by davidoesch** [comment]
a pity 
cc @p1d1d1
