### ISSUE TITLE
Extend find service

### ISSUE THREAD

**Issue by stflustop** [geoadmin/mf-chsdi3#3104]
For checking addresses we need a find service that checks for more than just one attribute. For example street name and postal code. There are street names that occur more than 50 times in switzerland. Therefore the result (json) cannot be filterd. it makes no sense to set the limit higher than 50. Proposal: Implemnt <layerDefs> (https://developers.arcgis.com/rest/services-reference/find.htm) - parameter.
 @p1d1d1 please verify if it's conform to OGC documentation

**Comment by p1d1d1** [comment]
@stflustop the ESRI REST API is not an OGC standard, so OGC conformity is not possible

**Comment by davidoesch** [comment]
Well it's about http://www.opengeospatial.org/standards/requests/89
Which we followed

**Comment by p1d1d1** [comment]
This is dead

Inviato da iPhone

**Comment by davidoesch** [comment]
Well our whole REST API is based on it @gjn

**Comment by gjn** [comment]
It's based on the standard we publish since 2014.

**Comment by p1d1d1** [comment]
Yes I know. I was just trying to answer Stefan's question about
compatibility with OGC.
We just cannot compare apples and oranges

Il giorno ven 8 feb 2019, 21:37 Gilbert Jeiziner <notifications@github.com>
ha scritto:

**Comment by stflustop** [comment]
OK, so it's not OGC. Our service is based on the ESRI specification. So can we add the layerDefs - Parameter to our find service?

**Comment by stflustop** [comment]
@gjn what's your opinion? If so, what is the next step?

**Comment by procrastinatio** [comment]
`mf-chsdi3` API was _inspired_ by the ESRI REST API, it was never a real implementation of it, which was rather infortunate (you jsut don't call omthing which is not)

From http://api3.geo.admin.ch/services/sdiservices.html#api-rest-services
> Most services are implementing or are heavily inspired by ESRI GeoServices REST Specification or by the Open Geospatial Consortium (OGC).

**Comment by procrastinatio** [comment]
Waiting for instruction

**Comment by procrastinatio** [comment]
@stflustop please test

**Comment by eraymann** [comment]
_Find_ works fine, also with combination of attributes, wildcards and special chars like ÿ. Some test cases as json and a simple implementation in py3 to perform these tests here: [https://github.com/geoadmin/tool-pure/tree/develop/services/search](https://github.com/geoadmin/tool-pure/tree/develop/services/search).
_Identify_ not tested,

**Comment by danduk82** [comment]
ready for tomorrow, just remove the doc until we optimize it.

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-chsdi3/pull/3244 for the merged PR
