### ISSUE TITLE
Referencing GeoAdmin without loader.js

### ISSUE THREAD

**Issue by tpluscode** [geoadmin/mf-chsdi3#3107]
I was looking at the possibility to integrate the Swiss topo tiles with OpenLayer used directly.

The examples show a handy method to create a layer `ga.layer.create('ch.swisstopo.pixelkarte-farbe')`

Is there a way to import this code without the loader? I want to avoid polluting of the global namespace. Something like

```
import {layer} from `GeoAdmin`

const pixelKarte = layer.create('ch.swisstopo.pixelkarte-farbe')
```

For now I was even unable to find the source code which `loader.js` bundles

**Comment by procrastinatio** [comment]
@tpluscode 
The loader.js and the APi is based on OL3 and OL4.
You have a few oudated example on how to used OL3 directly: http://api3.geo.admin.ch/api/examples.html#openlayers-3-examples or 
https://codepen.io/procrastinatio/full/Jxavxv

Using WMTS layers and OL5 is not difficult: https://openlayers.org/en/latest/examples/?q=wmts

The source for `loader.js`is  https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/loader.py. It basically statifies the configuration for layers (https://api3.geo.admin.ch/rest/services/api/MapServer/layersConfig?lang=en)
The code for the API is https://github.com/geoadmin/ol3/tree/master/src/ga (OL3/4 based)

For the configuration use http://api3.geo.admin.ch/services/sdiservices.html#supported-projections

**Comment by tpluscode** [comment]
Okay, let's see if I understand correctly.

In order to provide a simple solution to use the Swiss WMTS layer directly, I would fetch the `MapServer/layersConfig` resource and simply pass the settings to the `WMTS` source as shown in the OL5 example? 

Looks like I may have to remap some of the properties if anything change between OL4 and OL5 but otherwise there isn't much more to it?

**Comment by tpluscode** [comment]
Oh, boy. Ok, using these layers is far from being as simple as it could be.

I managed to get a solid prototype with OL5 by adapting [this codepen](https://codepen.io/geoadmin/pen/MyYYXR?editors=0010)

It does work however there are questions I find difficult to answer:

1. You support 4 projections? Is each layer source compatible with each one? How do I choose the right projection? Sorry if this is basic GIS question, but I don't have much experience with this.
1. Another codepen shows the use of `XYZ` style layer with `EPSG:3857` projection. It apparently does not universally work for each source. Should it?
1. Why does the `ch.kantone.cadastralwebmap-farbe` require custom settings in the `All WMTS` example?

You pointed me to the python code, but it is not the one that interests me. I was asking for the actual JS which implements the `ga.layer.create` function. If you can share that source I should be able to update it to OL5 (or use as-is with OL4). Otherwise it feels like I'm forced to reinvent the wheel where each layer source is it's unique snowflake and I will keep bumping into irregularities.

**Comment by procrastinatio** [comment]
Do you really need all these layers? You may only use [these layers](http://api3.geo.admin.ch/api/faq/index.html#which-layers-are-available) and for now, you need to register.

The JS code to configure the map and layer: https://github.com/geoadmin/ol3/blob/master/src/ga/map.js

1. Projection. You have the local projection, the historical LV03 (EPSG:21718) and the new GPS compatible one, LV95 (EPS:2056). And the ubiquitous (GoogleMaps, BIngs, etc.) WebMercator (EPSG:3857). Depends on what you are doing. Yes, all layers are published in all four supported projection.
2. It should...
3. I would be glad if I knew the answer myself... But if you use LV95, I think all layers have the same order.

The `layersConfig`service is used by `map.geo.admin.ch` but is not supported or documented, so nobody is supposed to use it. So if something changes or breaks, we are just sorry. And you have to configure the pyramid manually, with requires some internal knowledge.
It is safer to use the OGC WMTS GetCapabilities document
https://wmts.geo.admin.ch/EPSG/{code}/1.0.0/WMTSCapabilities.xml with {code} in (21781, 2056, 4329, 3858)

You may use it directly with OL, it build the pyramid directly:
https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html?q=wmts

**Comment by tpluscode** [comment]
Thank. So the capabilities XML is a officially supported resource for initialising layers? I will try use that instead. Looks much less complicated from OL code too

> The `layersConfig`service is used by `map.geo.admin.ch` but is not supported or documented, so nobody is supposed to use it.

You yourself pointed me to it so 🤷‍♂️ 
And also it is used in the codepen example which is double confusing in all.

**Comment by tpluscode** [comment]
Anyway, I got all the answers I needed. Thank you @procrastinatio
