### ISSUE TITLE
Replace PyRSS2Gen

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#3137]
`PyRSS2Gen` does not support python 3.

**Comment by pakb** [comment]
https://pypi.org/project/PyRSS2Gen/ says it should work on python 3

**Comment by procrastinatio** [comment]
OK, but RSS is so 20th century

**Comment by davidoesch** [comment]
Alternativ to provide Feed? Atom Open search?

**Comment by procrastinatio** [comment]
OK, check it is working in `py3`. So closing.
