### ISSUE TITLE
 layer search does not work (Coord system?)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3172]
ALL OS ALL BROWSER

Open
https://test.map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.leichte-basiskarte.vt&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.amtliches-strassenverzeichnis&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&layers_opacity=1,1,1,1,0.85

search for 
"Melonenstrasse"

click on result

result:
https://test.map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.leichte-basiskarte.vt&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.amtliches-strassenverzeichnis&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&layers_opacity=1,1,1,1,0.85&lon=6.69675&lat=2.27750&zoom=12 

(Hello africa)

expected result:
you are in st  gall

**Comment by danduk82** [comment]
the bug is reproducible only with heavy traffic using default projection.

To test and debug use a dev or int instance and load it with yandex (attention to the DB...)

**Comment by procrastinatio** [comment]
curl -H "Host: api3.geo.admin.ch" "localhost/rest/services/luftbilder/MapServer/ch.swisstopo.lubis-luftbilder_schwarzweiss/20050660015630?sr=2056&geometryFormat=geojson"

**Comment by procrastinatio** [comment]
To add to the confusion, `SQLAlchemy` upgrade (#3167)  has an SRID related error

```
FAIL: test_feature_geojson (tests.integration.test_features_service.TestFeaturesView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins-slave/workspace/chtopo_igeb_mf-chsdi3_PR-3167/tests/integration/test_features_service.py", line 278, in test_feature_geojson
    self.assertGeojsonFeature(resp.json['feature'], 21781)
  File "/home/jenkins-slave/workspace/chtopo_igeb_mf-chsdi3_PR-3167/tests/integration/__init__.py", line 88, in assertGeojsonFeature
    self.assertBBoxValidity(feature['bbox'], srid)
  File "/home/jenkins-slave/workspace/chtopo_igeb_mf-chsdi3_PR-3167/tests/integration/__init__.py", line 107, in assertBBoxValidity
    self.assertLessEqual(maxx, grid.MAXX)
AssertionError: 2714673.367687391 not less than or equal to 900000.0
```

2714673.367687391 is clearly LV95

**Comment by procrastinatio** [comment]
Maybe related to this https://github.com/geoadmin/mf-chsdi3/issues/2965 (wkid issue)

**Comment by danduk82** [comment]
need a deep rethinking of chsdi...

**Comment by procrastinatio** [comment]
Please test, should be fixed.

**Comment by davidoesch** [comment]
fixed
