### ISSUE TITLE
Öreb-Service: bug 

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#3175]
1) https://mf-chsdi3.int.bgdi.ch/shorten/8194041180 
2) click close to a border between two parcels
3) Two geometries are selected and there are two tooltip, which is ok, but 
4) the two EGRID numbers from the two parcels are available in both tooltips

![oereb](https://user-images.githubusercontent.com/1533649/56891021-633d6380-6a7b-11e9-8f28-7f1102d45819.png)

**Comment by rebert** [comment]
@p1d1d1 it is all about the clickpoint... evtl. the service of the canton uses a bbox arround the click

**Comment by p1d1d1** [comment]
@rebert you're right. Cantonal services seem to use a tolerance.
I'm sorry for the noise!
