### ISSUE TITLE
Search: wrong english translation for Zollamt

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#3179]
Customer Feedback:

1) open map.geo.admin.ch
2) switch to english
3) search for zoll
4) change "Costume office" to "Custom office"

![image](https://user-images.githubusercontent.com/1533649/57213961-a900ab80-6fe8-11e9-8d9f-3304789d3bc0.png)

**Comment by davidoesch** [comment]
Funny one. 
@ltclm can use fix this?

**Comment by ltclm** [comment]
yes, will be fixed with https://github.com/geoadmin/mf-chsdi3/pull/3178 next week.
