### ISSUE TITLE
Search on mobile :stalls

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3180]
Samsung Galaxy S7, Android 8.0.0 Chrome browser of @hpchrist 

How to reproduce

https://photos.app.goo.gl/fmE815k8FxtyMFVi6

Workaround;

use firefox on same device, works

Exzernal customer
Customer feedback ID : 2019031615032643
Customer feedback ID : 2019032614260223
Customer feedback ID : 2019042614065590

**Comment by danduk82** [comment]
@ltclm, can you reference here the PR that fixes this issue please

**Comment by ltclm** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/3145

**Comment by ltclm** [comment]
2019042614065590 is not related to sphinxsearch, it seems to be a frontend issue.
please open an issue in mf-geoadmin3

**Comment by ltclm** [comment]
@davidoesch 
i have changed the pr / testlink.
the performance is now a little bit better. wildcard search is activated only if the searchtext has more than one characters.
the response time for the first character search ``1`` is reduced from 1.2s to 160ms (measured on desktop). For the following characters it stays more or less the same.

**Comment by davidoesch** [comment]
Kunden Customer feedback ID : 2019032614260223 und Customer feedback ID : 2019042614065590 testen diesen
