### ISSUE TITLE
Identify requests fail for ch.bakom.mobil-antennenstandorte-* with "No GeoTable was found"

### ISSUE THREAD

**Issue by one-github** [geoadmin/mf-chsdi3#3193]
Identify requests fail for all ch.bakom.mobil-antennenstandorte-* layers with an error message  e.g. "No GeoTable was found for "ch.bakom.mobil-antennenstandorte-5g" for the layer ch.bakom.mobil-antennenstandorte-5g.

HTTP GET request:
`https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=2713321.58%2C1221191.79%2C2743321.58%2C1251191.79&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=1920%2C852%2C96&layers=all%3Ach.bakom.mobil-antennenstandorte-umts&mapExtent=2420000%2C1350000%2C2900000%2C1030000&tolerance=0&returnGeometry=true&sr=2056`

HTTP response status code 400:
`{"status":"error","code":400,"detail":"No GeoTable was found for ch.bakom.mobil-antennenstandorte-umts"}`

This error currently happens with all ch.bakom.mobil-antennenstandorte-* layers:
- ch.bakom.mobil-antennenstandorte-5g
- ch.bakom.mobil-antennenstandorte-lte
- ch.bakom.mobil-antennenstandorte-umts
- ch.bakom.mobil-antennenstandorte-gsm

Other layers (like ch.bfs.gebaeude_wohnungs_register) behave correctly.

**Comment by AFoletti** [comment]
Works as defined. Those are geoJSON layers and not available in our API services.
To know which layer can be queried via an "identify" request please refer to [the API documentation](http://api.geo.admin.ch/api/faq/index.html#which-layers-have-a-tooltip)

**Comment by one-github** [comment]
This used to work in the past, the response was like this:

```
 {
  "results": [{
    "geometry": {
      "type": "Point",
      "coordinates": [585102.0, 201503.0]
    },
    "layerBodId": "ch.bakom.mobil-antennenstandorte-gsm",
    "geometryType": "Feature",
    "bbox": [585102.0, 201503.0, 585102.0, 201503.0],
    "featureId": 5123,
    "layerName": "Antennenstandorte GSM",
    "type": "Feature",
    "properties": {
      "powercode": "P3",
      "label": "P3",
      "bgdi_created": "2015-02-17T23:00:35.808189"
    },
    "id": 5123
  }]
}
```

**Comment by AFoletti** [comment]
Yes, 3 of them were available in the services until April 2018. The 5G has never been available in the services though.
We had to switch to geoJSON because of stability issues under heavy load no our WMS.

@davidoesch maybe is worth to consider a way to have geoJSON layers in the services too?

**Comment by procrastinatio** [comment]
Hmm, `htmlPopup` and `identify` is a way to get info on raster data. It is a bit strange to use them on a vector dataset.

**Comment by procrastinatio** [comment]
@danduk82 We cannot do anything. Closing.

**Comment by one-github** [comment]
We actually show these four layers via WMS:

https://wms.geo.admin.ch/?LAYERS=ch.bakom.mobil-antennenstandorte-umts&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A2056&BBOX=2654031.58,1187986.31,2659151.58,1193106.31&WIDTH=256&HEIGHT=256

I suspect from your answers that this should be done via GeoJSON instead. How do I get these vectors via GeoJSON?

Thanks.
