### ISSUE TITLE
WMTS GetCap fees/constraint missing

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3196]
Feedback from Geoseer "The WMTS GetCap doc seems be be wrongly claiming that there are no Fees/AccessConstraints. There are fields for both of these at the Service level of the GetCap doc but they're both set to "None". They should probably point to the pertinent documents so users know about the restraints"
Proposal - let's point them to www.swisstopo.admin.ch/webaccess

**Comment by davidoesch** [comment]
Can you state here your opinion @p1d1d1 and then proceed with@ltclm

**Comment by p1d1d1** [comment]
@davidoesch both are free text. What about:

AccessConstraints: Free access up to 25'000 megapixels/year
Fees: www.swisstopo.admin.ch/webaccess

**Comment by davidoesch** [comment]
+1
@ltclm  can you proceed like this?

**Comment by p1d1d1** [comment]
Translations, in case:

deu: "Frei bis 25'000 Megapixel/Jahr"
fre: "Gratuit jusqu'à 25'000 mégapixel/an"
ita: "Gratuito fino a 25'000 Megapixel/anno"

**Comment by ltclm** [comment]
fee and accessconstraint translations have been added to bod
testlinks are in chsdi pr https://github.com/geoadmin/mf-chsdi3/pull/3197

**Comment by p1d1d1** [comment]
@ltclm @davidoesch not related to this issue:

- why keywords are missing from lang=it?
- why ServiceIdentification-->Abstract is set to "None"?

**Comment by ltclm** [comment]
because we never got these information.
if you want, you can fill the missing information directly in this table:
bod_master.public.wms_metadata (pk_map_name=wmts-bgdi) in the following columns:
* abstract
* keywords

**Comment by p1d1d1** [comment]
@ltclm 

Keywords for IT: 
[keywords-wmts-it.txt](https://github.com/geoadmin/mf-chsdi3/files/3227890/keywords-wmts-it.txt)

Abstracts:
[abstracts-wmts.txt](https://github.com/geoadmin/mf-chsdi3/files/3227892/abstracts-wmts.txt)

**Comment by ltclm** [comment]
thank you @p1d1d1 the metadata has been integrated to bod, see testlinks.

**Comment by p1d1d1** [comment]
@ltclm sorry I missed to provide you the "en" string for AccessConstraints. Could you please add it? Thanks and sorry again:

"Free up to 25'000 megapixel/year"

**Comment by ltclm** [comment]
salut @p1d1d1 
no problem. i have updated the bod.

**Comment by procrastinatio** [comment]
WMS BGDI is only free up to 25'000 megapixel/year. This is new.

**Comment by davidoesch** [comment]
Access constraint: you need to register
 Fee: some layers are free, other not. Freemium tier up to 25'000 megapixel/year for the non free layers.

**Comment by p1d1d1** [comment]
Are we sure 25K megapixels apply only to non-free layers?
And yes, Marc is right.
@ltclm I'm sorry for the "noise"

**Comment by p1d1d1** [comment]
by the way "you need to register" doesn't help to much without a link

**Comment by davidoesch** [comment]
Yes only non free. 
Link to register https://www.geo.admin.ch/de/geo-services/geo-services/portrayal-services-web-mapping/programming-interface-api/order_form.html (there is even a vanity URL @paoloamado can help)

**Comment by p1d1d1** [comment]
@davidoesch please suggest a vanity URL

**Comment by davidoesch** [comment]
There is one already.... We will look it up next week

**Comment by ltclm** [comment]
i have reset the access constraints and fee entries in the bod.

**Comment by p1d1d1** [comment]
@davidoesch @ltclm @procrastinatio can we agree on the following? And please also check the translations.

* EN 
AccessConstraint: Registration needed: www.geo.admin.ch/api-signup
Fees: Some layers are free, other not. Freemium tier up to 25'000 megapixel/year for the non free layers

* DE 
AccessConstraint: Anmeldung erforderlich: www.geo.admin.ch/api-signup
Fees: Einige Layer sind frei, andere nicht. Freemium Tier bis zu 25'000 Megapixel/Jahr für die nicht freien Layer

* FR 
AccessConstraint: Inscription nécessaire: www.geo.admin.ch/api-signup
Fees: Certaines couches sont libres, d'autres pas. Freemium jusqu'à 25'000 mégapixels/an pour les couches non libres

* IT 
AccessConstraint: Registrazione necessaria: www.geo.admin.ch/api-signup
Fees: Alcuni livelli sono liberi, altri no. Freemium fino a 25'000 mégapixels/anno per i livelli non liberi

**Comment by davidoesch** [comment]
+1

**Comment by procrastinatio** [comment]
@p1d1d1 OK, for me. Nice short link.

**Comment by p1d1d1** [comment]
@ltclm could we please proceed with this?

**Comment by ltclm** [comment]
bod has been updated and deployed to dev.
will be deployed this week:
https://mf-chsdi3.dev.bgdi.ch/1.0.0/WMTSCapabilities.xml

**Comment by ltclm** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/3217

**Comment by p1d1d1** [comment]
@ltclm could you please check the chars encoding? there is an issue with special chars. thanks

**Comment by ltclm** [comment]
> @ltclm could you please check the chars encoding? there is an issue with special chars. thanks

yes that's fixed in this pr, use the testlink here
https://github.com/geoadmin/mf-chsdi3/pull/3217
