### ISSUE TITLE
Sphinx paging for spatial queries sometimes too low

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#3218]
See customer email in webgis: 23. Juni 2019 um 10:42 (Betreff: Grundstück Nummer finden)

**Situation:**
Sometimes a search query with a searchText **AND** a bbox does not return any result. The example is proposed with a parcel search.

**Steps to reproduce:**
Based on two locations
1. [here](https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.kantone.cadastralwebmap-farbe&E=2538177&N=1165702&zoom=11&crosshair=marker) (OK)

2. [here](https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.kantone.cadastralwebmap-farbe&E=2538525&N=1165844&zoom=11&crosshair=marker) (NOK)

- Open [this search query](http://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=Echallens&origins=parcel&type=locations&bbox=2538177,1165702,2538177,1165702&sr=2056) corresponding to point 1. A result is returned
- Open [this second search query](http://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=Echallens&origins=parcel&type=locations&bbox=2538525,1165844,2538525,1165844&sr=2056) corresponding to point 2. No result is returned even if the point finds itself in the same parcel as the first one

**Expected result:**
- The second query returns exactly the same result as the first one.

**Initial analysis:**
Today @ltclm already had a look at the issue. Here the first findings:
- Both points are in the same parcel. See

```SQL
-- identify
SELECT * FROM vd.view_os_realestate_cwm WHERE st_intersects(the_geom,st_setsrid(st_point(2538525,1165844),2056)) -- 92951298
SELECT * FROM vd.view_os_realestate_cwm WHERE st_intersects(the_geom,st_setsrid(st_point(2538177,1165702),2056)) -- 92951298

-- search
SELECT * FROM vd.parzellen_sphinx WHERE id = 92951298
"BOX(2536789.688 1164864.794,2539019.757 1166924.984)"
```
thus both requests should return the same result
- Sphinx passes only 50 results to chsdi from the text search to evaluate against the geometry. If the match is not among those first 50 results, nothing is found

**Solution ideas:**
- order the sphinx results by proximity to the BBOX center before passing them to chsdi?

**Comment by procrastinatio** [comment]
Sphinx does not support spatial filter. We add some quadtree index for that purpose, but it is fuzzy (it was defined as such).

Your two queries translates as 

    bbox [538525.0, 165844.0, 538525.0, 165844.0]
    quadindex '020331333201123103201'

and 

    bbox [538177.0, 165702.0, 538177.0, 165702.0]
    quadindex '020331333202001110021'

On the other hand, the big parcel geometry is defined as quadindex '02033'

**Comment by procrastinatio** [comment]
Deployed and nobody complained ever since. Closing.
