### ISSUE TITLE
Search service doc and service behavior do not correspond

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#3219]
In the [API doc](http://api.geo.admin.ch/services/sdiservices.html#search) for the Search server, the _searchText_ and _bbox_ parameters are both described as optional, provided that at least one of the two is correctly set.

Now, in my experience (and with @ltclm confirmation) in reality it is just _bbox_ which is optional. If a _searchText_ shorter than 1 character is passed, no query is made and the result is automatically empty.

Is it really so?
If yes, do we need to fix the doc or the service behavior?

**Comment by loicgasser** [comment]
http://api.geo.admin.ch/rest/services/api/SearchServer?bbox=551306.5625,167918.328125,551754.125,168514.625&type=locations

`searchText` is optional if `bbox` is defined. The request above is taken from the doc. Note that this bbox parameter is not very accurate and is based on quad-indexes.

**Comment by AFoletti** [comment]
Heya @loicgasser ! Thanks for your answer.
We (@ltclm and me) do not understand then why [this query](http://api3.geo.admin.ch/rest/services/api/SearchServer?origins=parcel&type=locations&bbox=2538525,1165844,2538525,1165844&sr=2056) does not return any answer.
We know there is a parcel at the point (see [here](https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&E=2538525&N=1165845&zoom=10&layers=ch.kantone.cadastralwebmap-farbe&crosshair=marker)) This is bound to https://github.com/geoadmin/mf-chsdi3/issues/3218

**Comment by loicgasser** [comment]
Hello!

Filtering on the search service with a bounding box (actually a point in this case) is not an exact science. It is based on quadindexes...

It is meant to be used with "large" bbox.
One of the 2 points you defined is simply in another window defined by the quadindexes.

Relevant code in chsdi:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/search.py#L222

If you want an exact result you should use the identify service, but I think I recall that the parcels where "protected".

Another solution would be to limit the maximal resolution of the generated quadindex in the service.

**Comment by procrastinatio** [comment]
Note, depending on what you are searching for, it is better to use the `find` or `identify` services, as they relies on PostGIS and _real_ geometries.

**Comment by AFoletti** [comment]
Ok, it's not exact science. But even if one of the two points is not in the same quadindex window, why does a geographical search using a point well within CH and no text not return any result?

**Comment by procrastinatio** [comment]
Examples please.

**Comment by AFoletti** [comment]
Hello @procrastinatio 
This was "solved" with https://github.com/geoadmin/mf-chsdi3/pull/3222
