### ISSUE TITLE
SearchServer Service : add Geojson Support

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3258]
Situation
https://api3.geo.admin.ch/rest/services/api/SearchServer  returns a JSON

Request:
as for Identify Features" https://api3.geo.admin.ch/rest/services/api/MapServer/identify"
in addition to JSON a  GeoJSON  can be requested

**Comment by procrastinatio** [comment]
Merged and deployed. Probably solved
