### ISSUE TITLE
Errenous filtering of results from find with layerDefs

### ISSUE THREAD

**Issue by kaelinu** [geoadmin/mf-chsdi3#3267]
The additional filtering of the find-request (https://api3.geo.admin.ch/rest/services/api/MapServer/find) with layerDefs does not work correctly if multiple conditions are joined with an **OR**. The filter from find seems not to be applied to the second condition.

Example:
```
params = {
    "layer": "ch.swisstopo.amtliches-strassenverzeichnis",
    "searchText": "Studerweg",
    "searchField": "label",
    "returnGeometry": "false",
    "layerDefs": {"ch.swisstopo.amtliches-strassenverzeichnis": "gdename = 'Olten' or gdename = 'Sattel'"}
}
```

The result is expected to have 2 features. One "Studerweg" in Olten and one in Sattel.
The result you get is the "Studerweg" in Olten, and all existing features in Sattel.

**Comment by procrastinatio** [comment]
Both filters are applied, the trouble is more how all conditions are linked together. The query translates as "WHERE xxx AND yyy OR ZZZ" when it should be "WHERE xxx AND (yyy OR zzz)"
