### ISSUE TITLE
update search docu for sr=3857 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3315]
hi Marc

can you update api.geo.admin.ch docu
for
https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=bern&type=locations&sr=3857&geometryFormat=geojson

The documentation says, that only EPSG:21781 and EPSG:2056 are valid sr parameters.  sr=3857 is missing

**Comment by procrastinatio** [comment]
Is it official now?

**Comment by davidoesch** [comment]
It is - blame me
