### ISSUE TITLE
Layer search service and geometryFormat

### ISSUE THREAD

**Issue by fredj** [geoadmin/mf-chsdi3#3351]
Hi all,

According to the documentation and the examples in #3268 description, it should be possible to search for layers with the `geometryFormat` as `geojson`.

Is it the case? I'm receiving HTTP 500 errors with:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=layers&searchText=aerial&geometryFormat=geojson

**Comment by davidoesch** [comment]
@procrastinatio  is looking into that
