### ISSUE TITLE
[swisssearch] examples with special character between multilingual names

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#3352]
Upon user observation:
UC open app, search for "Murten" or "Morat"
Result: name search result is "Lieu Murten§Morat (FR) - Murten"
![image](https://user-images.githubusercontent.com/4577749/71085611-34a20380-2198-11ea-8b81-cb63fa8a8488.png)
Expected: entry without special char
I

**Comment by procrastinatio** [comment]
Looks like an issue in the data, or has the "§" character a special meaning in the "search" context?

https://api3.geo.admin.ch/1912100956/rest/services/ech/SearchServer?sr=2056&searchText=morat&lang=en&type=locations

**Comment by davidoesch** [comment]
Is a CR Char used by multi ling place names

**Comment by ltclm** [comment]
this character comes with the data delivery of karto. It is as a delimiter for line feeds. I have discussed it with marian and we have decided that we will replace this character with a space.

im updating the index on dev, int, prod now.

**Comment by ltclm** [comment]
it is for line feeds not a language separator
