### ISSUE TITLE
KML sharing down

### ISSUE THREAD

**Issue by ltkum** [geoadmin/mf-chsdi3#3428]
Currently on master, drawing kmls works, but trying to fetch them does not.

The difference lies here : 
current prod layer parameter after redirect (working) : 

layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2Fa_yfiZ6fSDWyNNKIbw5w8g

current master (not working) : 

layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege

the kml is not fetched.

**Comment by davidoesch** [comment]
Hi :
 this is  a showstopper, currently on prod it works and it is heavily used

under no circumstances break it with  the deploy --- because currently used by several orgs to mitigate covid19

**Comment by ltkum** [comment]
Do not worry, We are not planning to deploy this to prod as it is. I'm already on it.

apparently, the problem lies with the authorizations to the s3 buckets. When trying to access resources created with the current master, (https://public.geo.admin.ch/ghIyv93bQnOvWaz7B7p3iw for example), we have a 403. 

I'm investigating it ^^.

**Comment by ltkum** [comment]
So, authentication error was a wrong path (I was trying to access a non existing kml in s3, and it returns a 403 instead of a 404, but I managed to reproduce the initial problem (only the first drawing of a kml is shared. The cause of the access was that geoadmin was trying to access the prod bucket, while the api wrote in the dev bucket. My bad.). 
It seems it is linked to the update of data not being made correctly. I'm investigating the kml update functions.

**Comment by ltkum** [comment]
The fix is currently deployed on int, we're going to test it further tomorrow morning before deciding to go to prod.

**Comment by procrastinatio** [comment]
OK, this one was only an issue in our test environment.
