### ISSUE TITLE
WMS layer are not queryable / empty getfeatureinfo

### ISSUE THREAD

**Issue by edigonzales** [geoadmin/mf-chsdi3#3440]
As requested by one of our customers:

**not queryable:**
* `ch.blw.hang_steillagen`: "Wunschwerte: Hanglageklasse wie in Legende z.B. "Handneigung < 18%"
* `ch.blw.landwirtschaftliche-zonengrenzen`: "Wunschwerte: Zonenbezeichnung inkl. Zahlenwert"

**empty getfeatureinfo:**
* `ch.blw.bodeneignung-kulturtyp`: "Wunschwerte: wie in der Legende z.B.  "Ackerbau, Naturfutterbau: +; Kunstfutterbau: +/-"

**Comment by davidoesch** [comment]
We will talk to blw —

**Comment by davidoesch** [comment]
we will activate this in the next releaese (mai) see milestone

@mariokeusen IMHo you can close this
