### ISSUE TITLE
[copyright tool] Links to data owner BFE produce 404

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#3497]
UC: open application, load a layer from ch.bfe*, click on the data owner link on the bottom right for BFE
Result: page does not exist anymore (404)
Expected: correct link to BFE page

Workaround: replace URLs to BFE for attribution ch.bfe. Here are the new URLs:

- DE: https://www.bfe.admin.ch/bfe/de/home.html 
- FR: https://www.bfe.admin.ch/bfe/fr/home.html
- IT: https://www.bfe.admin.ch/bfe/it/home.html
- EN: https://www.bfe.admin.ch/bfe/en/home.html 
- RM: https://www.bfe.admin.ch/bfe/de/home.html 

Thanks in advance & Gruss
Mario

**Comment by ltclm** [comment]
Bod has been updated. The new links will be published with the next deploy.

**Comment by mariokeusen** [comment]
great thanks
