### ISSUE TITLE
shortener restriction :toolong

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3506]
Hi Marc
We have  a "toolong" warning in the shortener
According to 
https://github.com/geoadmin/mf-chsdi3/blob/0d1d6785eb57aa3ed5f948b072b4d75a0821fcbc/chsdi/views/shortener.py
this is due to limitations of DynamoDb?
-> Did we change this lately?

- [X] We should support URLS up to lenght of 2,048 characters  ( IE Limits)
- [X ]we must support  URLS up to 100 char

**Comment by procrastinatio** [comment]
@davidoesch It has been `2046` characters for the last 6 years. The last change was the upgrade to `boto3` 4 months ago.
We can go up to `2048`, but it's a hard DynamoDB Index limitation. 
Alternatively, we could no index long URL, because change of reusing them are slim.

**Comment by davidoesch** [comment]
Thx 

Works as defined in this case
