### ISSUE TITLE
[BOD updates, data status, metadata] not as rapidly visible as usual

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#3518]
UC: open the infobox of a layer with e.g. dailiy updates (p. ex. https://s.geo.admin.ch/8a86f2b829 )
Result: data status is 16.07.2020 instead of 17.07.2020 (automated update works, while @rebert and me observed the same already yesterday (15.07. instead of 16.07.)
Then I have imported a diff from geocat (a new download link) for this layer yesterday, which is still not visible today morning.

Expected: new data stati and geocat content is visible within 1h as usual

May this be some cloudfront issue? Thanks for having a look

**Comment by ltclm** [comment]
yes it is a cloudfront issue.
https://api3.geo.admin.ch/rest/services/all/MapServer/ch.astra.skatingland-sperrungen_umleitungen/legend?lang=de
The `cach-control` header is empty, maybe that's a problem but im not sure.
@procrastinatio could have a look at this?

the uncached response seems to be correct:
http://mf-chsdi3.prod.bgdi.ch/rest/services/all/MapServer/ch.astra.skatingland-sperrungen_umleitungen/legend?lang=de

**Comment by mariokeusen** [comment]
Confirmed: the uncached infobox is correct.

**Comment by procrastinatio** [comment]
Please note, cache setting are very different amount environment (value, CF or not CF)

`identify` has the default cache setting, so half-hour
`htmlPopup` is cached for one year.

So if a geometry is added or removed, after about half-hour it's OK
If the popup is changed, you have to wait or empty your cache

**Comment by davidoesch** [comment]
Will  be solved with https://jira.swisstopo.ch/browse/BGDIINF_SB-1284 on 16.9 deploy
