### ISSUE TITLE
Versioning missing on gwr models

### ISSUE THREAD

**Issue by blacksun777** [geoadmin/mf-chsdi3#3569]
Because of the release on the 28th: https://api3.geo.admin.ch/releasenotes/index.html#release-20201028-wednesday-october-28th-2020 
The BFS layer ch.bfs.gebaeude_wohnungs_register had a braking change causing havoc in an application of mine. 
At the moment I can't find a versioning system or hints to any existing release forecast to anticipate this change. 

Are there any different versions deployed?
Is there a upcoming release schedule and a testing environment? 
problem form commit: ea3276bf3140199a33457f45e611325117ceef3c in chsdi/models/vector/edi.py
#3549

**Comment by davidoesch** [comment]
Hi
Sorry we did break your application
we do not have (yet) versioning in place - 
so far we announced this model change first on july https://api3.geo.admin.ch/releasenotes/index.html#release-20200701-wednesday-july-1st-2020 via our release notes  and as well via our  GeoAdmin API Forum http://groups.google.com/group/geoadmin-api to which we urge user to subscribe to while signing up to the api via https://www.geo.admin.ch/api-signup 

thx

**Comment by blacksun777** [comment]
On a different note.
How do you know a field is a list or a single value, how is that marked in the "schema" (pdf document)? Is there a xsd model or openApi definition somewhere?

**Comment by davidoesch** [comment]
@mariokeusen do we have an Interlis model?
