### ISSUE TITLE
Wrong/lower weight for exact match than for fuzzy match in search service

### ISSUE THREAD

**Issue by eraymann** [geoadmin/mf-chsdi3#3573]
### Reproduction
Search for __Waldhofstrasse 1 8400 Winterthur__ in search field on map.geo.admin or
search via api
https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=waldhofstrasse+1+8400+winterthur&type=locations&limit=2

### Expected Result
An exact match with the search text has the highest weight.

### Actual Result
Fuzzy match Waldhofstrasse **1.1** is higher weighted (6) than the exact match Waldhofstrasse **1** (5). 
```
{
  "results": [
    {
      "id": 13167338,
      "weight": 6,
      "attrs": {
        "origin": "address",
        "geom_quadindex": "030010211201011310012",
        "zoomlevel": 10,
        "featureId": "201036223_0",
        "lon": 8.7123384475708,
        "detail": "waldhofstrasse 1.1 8400 winterthur 230 winterthur ch zh",
        "rank": 7,
        "geom_st_box2d": "BOX(695970.426680792 261547.250404897,695970.426680792 261547.250404897)",
        "lat": 47.49767303466797,
        "num": 11,
        "y": 695970.4375,
        "x": 261547.25,
        "label": "Waldhofstrasse 1.1 <b>8400 Winterthur</b>"
      }
    },
    {
      "id": 13000452,
      "weight": 5,
      "attrs": {
        "origin": "address",
        "geom_quadindex": "030010211201130211233",
        "zoomlevel": 10,
        "featureId": "1152484_0",
        "lon": 8.713351249694824,
        "detail": "waldhofstrasse 1 8400 winterthur 230 winterthur ch zh",
        "rank": 7,
        "geom_st_box2d": "BOX(696047.792210035 261485.919570854,696047.792210035 261485.919570854)",
        "lat": 47.497108459472656,
        "num": 1,
        "y": 696047.8125,
        "x": 261485.921875,
        "label": "Waldhofstrasse 1 <b>8400 Winterthur</b>"
      }
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/29711349/98006920-13b7c080-1df3-11eb-9f3e-8d7b453733a3.png)

### Consequence
Service cannot be reliably used for geolocation.

**Comment by davidoesch** [comment]
@ltclm  this seems a tricky one. Affected are addresses with decimals 
Fixeable?

**Comment by eraymann** [comment]
In the json extract above the first hit at attrs/num is 11, but the house number is 1.1. This is definitely wrong.  This also makes a workaround impossible to additionally check the desired house number for matching with attrs/num regardless of the weight. Thus, the search service is useless for most purposes.
Apparently all non-numeric characters are removed for attrs/num during import/indexing. A solution strategy could be to NOT do this anymore for this attribute. Or else to remove only the decimal places (1.1 -> 1, not 1.1 -> 11).
Please also consider that there can be house numbers with letters.

**Comment by ltclm** [comment]
@eraymann please test here:
https://mf-chsdi3.dev.bgdi.ch/feature_BGDIINF_SB-1400/shorten/8cc872a6ca

**Comment by eraymann** [comment]
@ltclm looks good! Many thanks for the super fast fix!

**Comment by davidoesch** [comment]
We identified an mayor issueintroduced with https://github.com/geoadmin/mf-chsdi3/pull/3581/files
Next: update on lunchtime 11.12.2021

**Comment by ltclm** [comment]
@davidoesch @eraymann 
the exact match results from this fix, which have higher priority over the wildcard match results have a lower weight, they all have a weight of 1. Priorizing them over the wildcard results with higher weights of the same objects has introduced the  referenced mayor issue.

I will have to revert this pr. we will have to find a solution which is preserving the weights.

**Comment by davidoesch** [comment]
Thx ,
Ok for revert

**Comment by davidoesch** [comment]
Rollback is in progress...
