### ISSUE TITLE
API FAQ  "which- layers" list are now empty

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3649]
Hi Marc 

https://api3.geo.admin.ch/api/faq/index.html#which-layers-are-available
https://api3.geo.admin.ch/api/faq/index.html#which-layers-have-a-tooltip
https://api3.geo.admin.ch/api/faq/index.html#which-layers-are-searchable
https://api3.geo.admin.ch/api/faq/index.html#which-layers-are-queryable

are now showing no results

IMHO this related to https://github.com/geoadmin/mf-chsdi3/pull/3628#issue-572583701

**Comment by davidoesch** [comment]
fyi @p1d1d1 @mariokeusen  (gosh it is my day off....)

**Comment by procrastinatio** [comment]
Tested, merged, and deployed.
