### ISSUE TITLE
Different GetCapabilities respone with same (?) request

### ISSUE THREAD

**Issue by edigonzales** [geoadmin/mf-chsdi3#3688]
- https://wms.geo.admin.ch/?service=WMS&request=GetCapabilities&version=1.3.0
- https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

One links to https://wms.geo.admin.ch/? in the online resources, the other one to http://wms-bgdi.prod.bgdi.ch/?. Latter one gives mixed contents errors in web clients.

**Comment by davidoesch** [comment]
we will track this with the internal ticket BGDIINF_SB-1811

**Comment by davidoesch** [comment]
Gefixed

@edigonzales

**Comment by edigonzales** [comment]
@davidoesch Aber noch nicht ausgerollt?

**Comment by davidoesch** [comment]
Doch, https://wms.geo.admin.ch/?service=WMS&request=GetCapabilities&version=1.3.0 

-> kannst du deinen cache invalideren, und falls Problem besteht deinen CURL   uns schicken?

**Comment by edigonzales** [comment]
1. curl "https://wms.geo.admin.ch/?service=WMS&request=GetCapabilities&version=1.3.0" > foo.xml
2. vi foo.xml. Siehe xlink:href="http://wms-bgdi.prod.bgdi.ch/?"

![Screenshot 2021-06-02 at 13 54 29](https://user-images.githubusercontent.com/2767800/120475757-0de68580-c3aa-11eb-8cf3-ebe020835790.png)

**Comment by davidoesch** [comment]
thx

**Comment by davidoesch** [comment]
quick update: we are working on it .....

**Comment by davidoesch** [comment]
@edigonzales can you give it a try after 1200 today? should be fixed

**Comment by edigonzales** [comment]
Works for me. Merci.
