### ISSUE TITLE
WMS swissimage requests response with 503

### ISSUE THREAD

**Issue by edigonzales** [geoadmin/mf-chsdi3#3785]
Approx 1/4 of all wms requests end up with a 503 response (see attached image). Client is qgis-server.

Sample request: https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2600464.645497661084,1228124.903536689701,2601734.180220951326,1229395.000001007691&CRS=EPSG:2056&WIDTH=2000&HEIGHT=2000&LAYERS=ch.swisstopo.swissimage&STYLES=&FORMAT=image/png&DPI=200&MAP_RESOLUTION=200&FORMAT_OPTIONS=dpi:200&TRANSPARENT=TRUE

@schmandr can be contacted if you need some live requests for checking log files etc.

<img width="1520" alt="Screenshot 2021-12-21 at 10 07 24" src="https://user-images.githubusercontent.com/2767800/146923156-b7732bdf-2fa7-47c2-924b-aedafccff34c.png">
.

**Comment by davidoesch** [comment]
we will track this internally with https://jira.swisstopo.ch/browse/BGDIINF_SB-2116 and come back to you

**Comment by davidoesch** [comment]
@edigonzales should be fixed, pls reopen in case you still have this issue

**Comment by edigonzales** [comment]
@davidoesch Thanks. Yes, seems to work.
