### ISSUE TITLE
add exact click coordindates to htmlPopup Service URL

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#565]
When clicking on the map in re3 for now only the mapExtent is sent to the htmlPopup Service.
In several tooltip makos **we have to know the exact coordinates of the mouse click, as we did in re2**. For now this information is not available and a lot of tooltips (p.e. cadastralwebmap @daguer) make no sense.
Currently the htmlpopup service is called with the following parameters:
http://map.geo.admin.ch/main/1395325054/rest/services/ech/MapServer/ch.kantone.cadastralwebmap-farbe/7/htmlPopup?imageDisplay=1920,592,96&lang=de&mapExtent=180000,42000,1140000,338000

this should be changed to:
http://map.geo.admin.ch/main/1395325054/rest/services/ech/MapServer/ch.kantone.cadastralwebmap-farbe/7/htmlPopup?imageDisplay=1920,592,96&lang=de&mapExtent=180000,42000,1140000,338000&x=600000&y=200000
or we create, as in re2, a bbox around the click coorindate with a buffer of some meters:

http://map.geo.admin.ch/main/1395325054/rest/services/ech/MapServer/ch.kantone.cadastralwebmap-farbe/7/htmlPopup?imageDisplay=1920,592,96&lang=de&mapExtent=180000,42000,1140000,338000&clickExtent=599950,199950,600050,200050

**Comment by ltclm** [comment]
This was the discussion about the htmlpopup Service and Click Coordinates

**Comment by cedricmoullet** [comment]
I stated: "A new parameter clickPoint will be always send to the MAKO and can be used if needed.", so please do.

**Comment by ltclm** [comment]
We should send the scale / zoomlevel too.

**Comment by procrastinatio** [comment]
Each canton has a different set of parameter, with other you have to compute them, also incorporating `scale`or `resolution`.
