### ISSUE TITLE
Protect the geometries of ch.bfs.gebaeude_wohnungs_register

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#886]
The geometrical information for this layers should be protected. No service shall return them.

e.g.
/rest/services/ech/MapServer/ch.bfs.gebaeude_wohnungs_register/490830_0
rest/services/ech/MapServer/find?layer=ch.bfs.gebaeude_wohnungs_register&searchText=berges&searchField=strname1

Did I miss some?

**Comment by cedricmoullet** [comment]
@procrastinatio could you please fix this ?

**Comment by procrastinatio** [comment]
Review, check, test and merge PR https://github.com/geoadmin/mf-chsdi3/pull/1132. Should do the trick.

**Comment by loicgasser** [comment]
@gjn outdated comment is still valid to me...

**Comment by procrastinatio** [comment]
@loicgasser which comment ?

**Comment by procrastinatio** [comment]
So merge and deploy PR#1132, the varnish settings are done überall

**Comment by gjn** [comment]
Thanks alot.
